### ISSUE TITLE
Consider removing settings migration code

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1009]
Importing browser-specific settings from other browsers is debatable at best. We should limit ourselves to migrating content-focused data only.

**Comment by janekptacijarabaci** [comment]
IMHO: Is it this setting or is it part of the whole (cookies)?
https://bugzilla.mozilla.org/show_bug.cgi?id=260274

**Comment by wolfbeast** [comment]
...? Sorry I don't understand -- are you expressing an opinion? if so, which opinion? or are you just asking a question?

**Comment by janekptacijarabaci** [comment]
I'm sorry...

Is it this setting or is it part of the whole (cookies)?
https://bugzilla.mozilla.org/show_bug.cgi?id=260274

Whatever you decide to do, I suggest:
I'd rather not delete the entire code (Settings()) because it can be used later:
https://hg.mozilla.org/mozilla-central/rev/0027b2bfafaf#l1.12

**Comment by wolfbeast** [comment]
It is importing browser-specific settings. That includes per-site cookie handling and anything else that isn't directly content related. There's no real point in doing a half job here.
