### ISSUE TITLE
Add JPEG-XR support

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#105]
As an alternative and standardized format for images, JPEG-XR (extended range jpeg, especially suitable for HD photography, wide-gamut images, and a superior compression format compared to standard JPEG) would be good to have. This format was rejected by Mozilla based on mostly political reasoning. Adding this alongside WebP should provide maximum choice for Pale Moon users.
A basic implementation with decode-after-load should be straightforward.

On hold for the moment as I communicate with the original coder and/or MS OpenTech to get a suitable implementation for our code base.

**Comment by wolfbeast** [comment]
Clearing the milestone for now since after initial communication, both the dev and MSOT have become completely unresponsive. :-1: 
Do they want their format to be adopted, or not...?

**Comment by wolfbeast** [comment]
I got a reply from MSOT, and a repo was committed for the decoder as-written for them, and released to the public that way, building on jxrlib and published under the Community Promise.
This means we can go forward. I'm keeping myself assigned to this since adding decoders is still fresh in memory.

**Comment by wolfbeast** [comment]
Well, it looks like the code dump supplied by MSOT is mostly useless.
The build system files are incomplete, e.g. there are NO symbol&header exports listed, and trying to add them manually, both by adopting the library properly in /media/libjxr and as-supplied in /image fails with unresolved externals. I've wasted 2 days on this and can't get it to work, so maybe someone with the appropriate knowledge can look at this.

Repo of jxr FF code:
https://github.com/wolfbeast/ff-jpegxr
Integration commit (separate branch): Commit: 307b09bcba21f42fdd4cfac196182db9efe855ec

**Comment by wolfbeast** [comment]
Clearing milestone - doesn't look like the existing files are of any help (including the VSO file dump I received end of Aug). Looks like it will not make it into 26.0

**Comment by wolfbeast** [comment]
if we want this, it will have to be a completely new implementation.

**Comment by wolfbeast** [comment]
Bounty-candidate.

**Comment by rhinoduck** [comment]
I couldn't sleep last night so I took a look at this. Putting the code together was messy business, but once I actually got it to compile, I was met with a pleasant surprise of an image loading fine on the first run.

This is still just a preview; it is the first working version on which I did close to zero testing. I still want to (and need to) look at how and why things actually work, if they will work well in all (or most important) cases, if something can be improved... and I need to clean up a bit (including some of those rants I put into comments out of frustration; some of which may soon in turn ironically make me look like an idiot in hindsight). I'm placing this here so that you know that something is happening and that there are actual results. There's still work ahead though.

In the following branch, you can find what's been done so far; hopefully, I'll be able to continue with what I outlined above in the following days. Also provided, is a test page with one small and one large jxr image.

Preview branch: https://github.com/rhinoduck/Pale-Moon/tree/jxr-test
Test page: http://rhinoduck.net/palemoon/github/issues/105/dogontrain.html

The images were converted using the following EncApp.exe example command (don't try to judge quality though, the originals came from plain JPEG files):

```EncApp.exe -i input.bmp -o output.jxr -q 10```

Misc Info:

 - Pale Moon code was based on the master branch (Tycho)
 - jxrlib code was taken from wolfbeast's repo linked above in this issue
 - integration was done from scratch (all things considered, personally, I perceived it as easier than trying to merge a year old effort that I didn't know with a living branch)
 - Mozilla Build 1.10 was used (I don't know what you use with Tycho; this worked for me after fixing a small build issue with the installer/uninstaller scripts)
 - mozconfig settings were taken from the buildconfig.html file of 27.0.0b2

Here they are for easy access:
```
mk_add_options MOZ_CO_PROJECT=browser
WIN32_REDIST_DIR=$VCINSTALLDIR/redist/x86

ac_add_options --with-distribution-id="MCP-beta"
ac_add_options --with-branding="browser/branding/unstable"
ac_add_options --enable-application="browser"
ac_add_options --enable-optimize="-O2 -GS- -Qfast_transcendentals -Qpar -Qpar-report:1"
ac_add_options --enable-jemalloc
ac_add_options --enable-shared-js
ac_add_options --disable-debug
ac_add_options --disable-tests 
ac_add_options --disable-mochitests
ac_add_options --enable-strip
ac_add_options --disable-updater
ac_add_options --disable-crashreporter
ac_add_options --disable-accessibility
ac_add_options --disable-parental-controls
ac_add_options --disable-maintenance-service
ac_add_options --disable-sandbox
```

I suppose I could also provide a binary if you wanted one, though I would probably have to recompile with branding turned off.

I hope I'll have better luck with dropping dead tonight and enjoying quite a few hours of sleep, so, if lucky, I will not be responding during that time.

**Comment by mattatobin** [comment]
Tycho should be built with MozillaBuild 2.0 (2,1 may work but not sure about anything higher) that will solve your NSIS issues.

**Comment by wolfbeast** [comment]
I've been building with 2.1.0 thus far.
Also, the jxrlib should probablt be placed in /media with all the other image decoder libs, but first things first would have to be a working implementation.

**Comment by wolfbeast** [comment]
We'd probably need a few test images to throw at this:
- Lossy jxr
- Lossless jxr
- jxr with transparency
- Progressive jxr (is this a thing, anyway?)

**Comment by mattatobin** [comment]
The glue should live in **image/decoders** preferably as one source file and one header file

As Moonchild said, the lib it's self should live in **media/libjpeg-xr**.

This may add an extra wrinkle because on Windows we are going back to building all media libs as a shared lib (gkmedias). So I am not sure what the impacts on the glue will be.

I wonder though, is the added depth of the directories for the lib required or could they be flattened at all? Are there any naming conflicts we may have? Also, are we exporting any headers that may need to be exported to a subdirectory of dist/includes. Have to be careful about collisions.

**Comment by wolfbeast** [comment]
Setting this as assigned since @rhinoduck is obviously working on it.

**Comment by rhinoduck** [comment]
Alas, this wasn't as much sleep as I was hoping for given that I skipped a night.

Thanks for the info, I'll switch to MB 2.1 for my next full tree rebuild to jump on board with the crowd.

> ..., but first things first would have to be a working implementation.

and

> "We'd probably need a few test images to throw at this..."

Indeed, the first step was to get it into a basic working state so as to have a PoC and so that we have a base point we can return to if things start going awry. Now, we can safely start breaking stuff and start adding complexity :) Or rather removing... depends on the PoW really.

I welcome all the feedback on where you'd want things to live in the source tree and in what form. This is definitely something I don't have a mental map of yet. I concur with moving things around as one of the messy parts of this task was merging the directory structure which I already complained about in one of my not so nice comments.

```
# TODO: [rhinoduck] This will probably be reorganised. The directory structure
#       in moz.build files coming from the jxr example looked more like abstract
#       art than an attempt at placing things in sensible locations and actually
#       have them work at all.
```

I suppose when you talk about glue in the context of PM, you mean the nsJPEGXRDecoder.h and nsJPEGXRDecoder.cpp files? Because what currently lives in the jxrlib/jxrglue directory seems to be a different beast (read as: not Mozilla specific) which I'd rather keep as part of the library and as separate files.

As for exporting includes, JXRGlue.h is the only header that's directly included, and JXRMeta.h and windowsmediaphoto.h seem to be the only other headers it drags along with it as things stand now.

I will definitely be making changes to the directory structure of the lib, though I am wondering, is there any real advantage in flattening it completely? I'll draw inspiration from what's already present in media/, and come up with something I will consider reasonable; then, let's see if it's something you like or something you'd want me to change.

The name of the library is jxrlib and I am inclined to adding it to the media/ directory under this original name as to me, it is less confusing, and will cause no trouble should a libjpeg-xr pop up in the future (or should it already exist). Although, if you have a naming policy in place (or simply a preference) which favours adding it as libjpeg-xr, I will use that.

More testing images/scenarios will be coming as I get more familiar with the format. Keep throwing your thoughts and wishes at me, it is valuable information and it helps me with where I should look next and what I should focus on.

Also, if you have some early pointers or observations about what I should beware of for the Linux build, the sooner I am aware of these, the better. So far, I have been focusing on Windows only and, as even there it takes me over 3 hours to do a full source tree rebuild on my trusty old machine, I suspect that, in a VM, this will truly take a whole night. That's why I'd rather take precautions now than hunt silly things over several days later on.

**Comment by mattatobin** [comment]
Well.. you don't have to be burdened on build.. As I can complete builds in 30-40 minutes I can sure play tryserver for you on both Windows and Linux.. As for mozillaness of the file locations and stuff like that I kinda "own" the build system and am obsessed with tree structure so I can also help with that as well..

While we can do this here in the issue no problem if you want a more direct 2-way conversation you can always stop by our IRC channel. Up to you really..

**Comment by wolfbeast** [comment]
Obsessions aside, there's no real reason to flatten everything completely. I'd rather keep some hierarchy in it. Considering the jxrlib is laid out the way it is and it's a 3rd party library, we _should not_ mess with its structure. That's just wholly unnecessary.

@mattatobin: The `jxrglue/*` is part of the jxrlib itself; it provides the exposed API AFAICT, and should live in the jxrlib location. The only thing we don't agree on is the actual location of `jxrlib/*` as a whole living in `/image` instead of `/media`.

**Comment by rhinoduck** [comment]
> Considering the jxrlib is laid out the way it is and it's a 3rd party library, we should not mess with its structure. That's just wholly unnecessary.

I actually came to the same conclusion and already have it that way in my local repo. The whole "everything in the image folder and various strange additional subfolders" thing came from the fact that it was used that way in the jxr example and their moz.build files, and from my lack of understanding at the time; I was just trying to follow what they were doing as it was the easiest starting point when trying to make it work.

Discussing things here seemed sufficient to me until now and I like that everything gets nicely archived in one place, but I do have a few questions on the side which are better suited for IRC so I will drop by eventually. My only issue with IRC is that I get very easily caught up in conversations which have nothing to do with the work that needs to be done; not that I don't enjoy them, it's just that there isn't much progress as a result :)

**Comment by mattatobin** [comment]
I'm sorry you already had decoder cpp in decoders directory.. I must have been sleepy when I was poking at it.. Yeah seems the only thing is move the jxrlib code  as-is to media and deal with gkmedias.

**Comment by rhinoduck** [comment]
I randomly glanced upon an access to the Pale Moon testing files in my
Apache logs today and realised that I have now already earned a sweet
reputation of another who promises but does not deliver. As things have
truly stalled on my end, I am pushing everything as it were the last
time I worked on it; which I should have done a long time ago as some
of the outstanding issues will be resolved much easier with your input.

As of now, the TODO point 1. is a stopper for a merge and the MIME type
questions need to be resolved. When those things are out of the way,
I could create a pull request if you'd rather have the code in the main
repository already; I'd still call it experimental, but I'd consider it
a complete basis for testing and further improvement.

The current version can be found in the
https://github.com/rhinoduck/Pale-Moon/tree/jxr-review branch. If there
are still some issues with naming or where things are placed, raise
them and I will fix up the commits. Sadly, I cannot guarantee that what
I am pushing now will compile as I did not have time to run the build,
but if something pops up, it should be only silly easy to fix errors; I
will let the build run over night and see in the morning :)

There are various images to test with at
https://rhinoduck.net/palemoon/github/issues/105/ and in subdirectories
there; sorry for the mess, hopefully, I will organise it a bit better
in time.

Here is a full summary of current state...

### Done

1. Integrate jxrlib
On Windows, jxrlib is linked into gkmedias.dll. The MOZ_JXR build flag
enables/disables JXR support (enabled by default). The
media.jxr.enabled pref enables/disables JXR support at runtime
(disabled by default). Linux build compiled and ran fine last time I
tried as well. For JXR support advertising in HTTP headers, see the
questions section. The libary code has been included in the repository
as is (i.e. no changes, no whitespace normalisation) to make
diffs/upgrading less confusing.

2. Research possible missed patches
Due to the fractured/half-abandoned nature of the project it was not
clear what the definitive version was. But, after doing a bit of
digging, nothing from the little that is missing from the MS OpenTech
branch (which is equivalent with what is in the PM fork except for
licence headers being added in two files) seems to be a concern for
Pale Moon.

### Deferred or Abandoned

1. Add MOZ_NATIVE_JXR
This turned out to be too much of a PITA (missing header in the Ubuntu
package for example; though the main issue were differences in the API
between versions) and not worth the time in my opinion.

2. Testing of jxrlib with a fuzzer
Not a requirement for experimental support, but it might be worthwhile
at least because of the mention of jxrlib **at the bottom** of this
page: https://cxsecurity.com/issue/WLB-2015040090

3. Fix artefacts appearing in one image
The image in which the artefacts appear:
http://rhinoduck.net/palemoon/github/issues/105/imgout/cloud_spatial_lossless_interleavedalpha.jxr
A screenshot documenting the artefacts:
https://rhinoduck.net/palemoon/github/issues/105/jxr-artefact.jpg

### Current TODO

1. Add a pref-changed listener for media.jxr.enabled
So that the JXR MIME type is added to/removed from the HTTP Accept
header when the setting changes. *This needs to be done or else Pale
Moon will always advertise JXR support in its HTTP Accept header.*

2. Fix a crash
The decoder wrapper does not like to be interrupted; try loading
https://rhinoduck.net/palemoon/github/issues/105/slow/imgout/cloud_lossless.jxr .
What probably is a bug in Apache or its mod_dialup (or just my
misconfiguration somewhere) cuts the connection for some reason after
sending 7000 bytes and makes Pale Moon fall down from the clouds.

3. Better integrate the nsJPEGXRDecoder class
Add debug logging as seen in the other decoders, and generally go over
the code properly at least once.

4. Fix alpha channel issues
Transparent areas in tiled backgrounds are black; when loading certain
types of images with planar alpha, transparent areas are black until
the image is fully loaded.

5. Add JXR content sniffing
Is it desired or not though? See also question 1.

### Questions

1. Which MIME type to use?
There are two MIME types for the JXR format according to
https://en.wikipedia.org/wiki/JPEG_XR . The older vendor-specific
image/vnd.ms-photo and the newer image/jxr proposed for standardisation
but not standardised yet. See:
http://www.iana.org/assignments/provisional-standard-media-types/provisional-standard-media-types.xhtml
MS Edge/IE send image/jxr in the header, I think it would be the better
choice for Pale Moon as well (even though image/vnd.ms-photo is in the
code now becaue that is what I set up for testing). Either way, PM
should probably recognise both, but from what I have seen, to achieve
that, it would either have to be done through content sniffing or as a
hack around the MIME type resolution code; suggestions/better insight
are very welcome here.

2. Which HTTP requests should advertise JXR support?
Chrome sends image/webp in the Accept header of both image and general
requests, Edge/IE does the same with image/jxr. Pale Moon only
advertises support for image/webp in image requests; is this by
concious choice? So far I followed the PM style and added the MIME
type only to image requests.

**Comment by rhinoduck** [comment]
A couple of things pushed into the jxr-review branch...

The media.jxr.enabled pref no longer triggers an assertion in debug builds; also, it now amends image.http.accept based on the values of media.jxr.autoaccept and media.jxr.advertised_mime_type (see the comments in libpref/init/all.js). It might have been better to use a built-in parser for the Accept field if one exists, but these prefs and related code should be just temporary anyway.

Both MIME types are now supported in what seems to be the optimal way, but my knowledge of the Mozilla codebase is still at its infancy; the above-mentioned prefs have been provided for testing variations. At the following URL, it is possible to test conditional serving based on the Accept header: http://rhinoduck.net/palemoon/github/issues/105/conditional-serving

Subdirectories for both MIME types are present; there is also a subdirectory for WebP, so a comparison of behaviour can be made. This is an example of the configuration used on the Apache side:
```
AddType image/jxr .jxr
RewriteCond %{HTTP_ACCEPT} image/jxr
RewriteRule (.+)\.(jpe?g|png|gif)$ $1.jxr [T=image/jxr,E=accept:1]
Header append Vary Accept env=REDIRECT_accept
```

As of what is to come, I am half-way through rewriting the Mozilla side of the decoder to make it clearer what the flow is and what has been finished and what has not; I know what was causing the crash in the original code, but revising the paths the execution takes seemed like a saner thing to do than adding more "what if" branches to the thing and hoping for the best.

**Comment by wolfbeast** [comment]
I'll hook it up as a remote, make a build and have a look how it works :) When was your last fork-off point?

**Comment by wolfbeast** [comment]
As for your questions... 

1. Using the mimetypes resolution should ot require sniffing. that's the whole point of mime types. Having multiple mime types be the same internal type is done all the time in the browser, so you can just do the same for jxr.
2. Only the image request headers should advertise image support. Other requests in non-image elements shouldn't advertise this support because other elements don't support that kind of content. That is by conscious choice - just blatantly sending it with all requests is nonsense and too naive -- and I even think it may not be according to spec.

**Comment by wolfbeast** [comment]
As for point 2: RFC 2616 says:

> 14.1 Accept
>
>The Accept request-header field can be used to specify certain media types which are acceptable for the response.

Since non-image requests in general don't have image data as an acceptable response to the request, specifying explicit image formats as preferred over "any" content makes very little sense. The only exception would be top-level images, but those are generally to explicit files.

**Comment by rhinoduck** [comment]
> When was your last fork-off point?

I rebased before the push after the long break; I did not do so at any later point in the recent days because I try to avoid large recompiles. Though I think rebasing on master locally should not bring up many conflicts for you, if any at all; the only thing I dealt with after all that time was one thing git perceived as a conflict in all.js.

> Having multiple mime types be the same internal type is done all the time in the browser, so you can just do the same for jxr.

For some reason, it did not occur to me I could just add the second MIME type as a second define when I was writing the questions, silly me.

> Only the image request headers should advertise image support. Other requests in non-image elements shouldn't advertise this support because other elements don't support that kind of content.

Well, there are standards, and then there are also all the beasts lurking in the wild... and all the shades inbetween. I agree that it does not make sense apart from the case with top-level images. And, in that case, there actually is a little inconsistency when you decide not to do it and you come across a server which does conditional serving; you see the image type as JXR in both the HTTP headers and in the image info (when requested as part of a document), but when you go to save the image (or go to its URL directly), you get a JPEG (or whatnot). This might be a nuisance if the images actually differ in quality significantly and you want the better one. But I suppose that's more of an (un)expected result of conditional serving than anything else, and probably should not weight in much. I was mostly just asking because both major browsers which advertise these new formats do so in their general requests too, so I was wondering if there was more to it.

As for the state this is currently in: I did just the integration; nsJPEGXRDecoder is still the MS OpenTech implementation. It is a working one as it is when looking from the outside, but with the hiccups and uncertainties mentioned above in this thread. I might feel better about it once I dissect it completely, by which time I will probably have rewritten it though. I did all the quacking around with prefs to allow this to be merged and subsequently tested without having to worry about it being directly exposed, but that will also make more sense once it takes a closer to final form. For now, I would mainly like to avoid doing something stupid, so if you have the time to follow this and give me a nudge where I'm straying off the path, it will be appreciated. If not, I will probably add a few more "Oh my God, I am an idiot!" moments to my collection, but eventually get to where I need to go too :)

**Comment by wolfbeast** [comment]
Well, for the record, Mozilla has always used separate "accept" request headers for images, that's not "just us" and I've seen no reason to change that.

> This might be a nuisance if the images actually differ in quality significantly and you want the better one.

I'd actually call that a web design problem rather than a browser problem. It can even be argued that it offers extra implicit content protection for website owners ;) For that corner case, if you really need it, you can always change `network.http.accept.default` to include media formats you prefer in all requests.

As for the state this is in, dissecting this and rewriting it is a good final goal, but it also makes it a moving target. I would rather see that as a post-implementation enhancement, but the "quacking around" as you call it with prefs would make this merge-able as experimental support at a much shorter notice, which I'd prefer at this point, unless you think it's better to wait for this support until you've re-written it to something more solid than the MSOT implementation.

Unlike WebP, there's less of a hurry here, although I would like to get it in before the summer, if you get my drift.

**Comment by wolfbeast** [comment]
When deciding what to advertise, `image/vnd.ms-photo` is likely less common than `image/jxr`, and if Edge/IE uses `image/jxr` then we should make Pale Moon have parity with that. Nothing is preventing us from adding both to the accept-header if needed, of course, if we get a final implementation in that is always-on it can just be added as-necessary; care should be taken not to make these header fields too long though, and any conditional serving web application should be able to determine on the server-side that `image/vnd.ms-photo` should be supported if `image/jxr` is advertised in the headers.

**Comment by wolfbeast** [comment]
After some preliminary testing, I'd say we can most definitely use it in its current state as experimental support, so I'm tentatively marking this for the 27.2 milestone.

**Comment by wolfbeast** [comment]
@rhinoduck could you please make a pull request against our current trunk (master) so we can merge in the current state of your work and slate it for 27.2?

**Comment by rhinoduck** [comment]
Will do.

I was exploring one more issue. It turns out there actually is a little problem with not advertising the type in both kinds of HTTP requests (or rather a problem which is revealed as a result). If the mime type is present in Windows registry, the default extension deduced for that mime type coming from there will be forced in the Save Image As dialog. I.e. you get offered to save the file as image.jpg.wdp and it will display the, now wrong, mime type it pulled from the image cache. The data will be JPEG in the end though, because that's what the server will serve on a separate request (I didn't get to see if, where, and how http caching possibly enters this yet, and if it would make any difference; so far, my observations are that the image data always gets pulled from the server). In a default Windows installation, the image/vnd.ms-photo format is present in the registry, so the issue will always appear when this mime type is conditionally served if it is only adverstised in the image requests; this is also the case with conditioally serverd image/png which Pale Moon currently includes in the image Accept header as well. As the mime type and possible extesions are determined before any connection to the server is made, it is currently impossible to know what the server will send and what should the Save As dialog display. In the case of webp, this works out "ok", because image/webp (or image/jxr) is not in the windows registry, and Pale Moon will thus end up deducing the image/jpeg mime type from the jpg extension only. I wasn't able to think of an optimal solution to this yet, but that can be done later.

Before the merge, one last thing I would like to do is unify naming. Right now, JXR and JPEGXR/JPEG_XR are all used in various places. My preference is to have only JXR as it is prevalent in the libs, it is in the MIME type, and it is shorter; so there would be nsJXRDecoder, IMAGE_JXR, and so on. Do you agree with this, have other preference, or should I just leave it alone?

Everything else should be ok to change in-tree post-merge without introducing messiness, so when this is decided, I will rebase, squash, add your tests, and create the pull request.

I also "fixed" the crash, and fixed the transparency issues in the MSOT code as it was simple now that I know what's going on; I didn't give it a very thorough testing run though. The jxr prefs should now behave a bit better as well.

**Comment by rhinoduck** [comment]
Created pull request https://github.com/MoonchildProductions/Pale-Moon/issues/885 (I suppose the automatic cross-referencing would have been enough here, I might leave the links out next time). It includes the renaming I mentioned in my previous post; if you do not want it, I can rip it out.

The unsquashed commits can still be seen in the jxr-review branch if you want to follow the trail (but the latest additions were basically just the renaming).

**Comment by rhinoduck** [comment]
> but the latest additions were basically just the renaming

Actually, that is not true unless you've already looked today. Either way, the jxr-review shows things piece by piece if needed.

**Comment by wolfbeast** [comment]
Renaming `JPEGXR` and `JPEG_XR` to just `JXR` is fine - it's still clear what is being referred to since it's not ambiguous in our tree.
I'll merge #885 in and build a new unstable build today to have it included, and we can go from there.

**Comment by trav90** [comment]
While in my (very limited) testing thus far it appears to be working, some versions of GCC throw almost 200 lines worth of warnings when compiling the JXRDecoder which you can see in this gist:

https://gist.github.com/trav90/a89f39afeb7650b3d52ac445c47354db

(I am only mentioning due to it being such a high number of warnings generated).

**Comment by rhinoduck** [comment]
That would be the MSOT code. As I stated above, I did not modify it beyond the fixes needed to make it compile and observably work so that some form of JXR support could be included now as requested. Though, at a glance, I don't see anything problematic the warnings point to except not checking the return values in `err`. Anyway, the not-so-easy-to-follow flow, state meaninglessly scattered across many variables, and the general notion of this being rushed and never finished and fully tested are exactly the reasons why I am already in the process of rewriting it piece by piece; that will do away with the warnings as well.

If they should be bothersome in the meantime, let me know, and I'll get rid off them.

**Comment by trav90** [comment]
They aren't particularly bothersome to me, since (as you mention) this code is a bit rushed and not fully tested yet and it does appear to be working in my (so far) limited testing. I was just a little surprised to see a large increase in compiler warnings today, so just thought I'd mention it more as a FYI than anything.

**Comment by rhinoduck** [comment]
Thanks for mentioning them, it would definitely be good not to have them pop up. I just didn't go looking for warnings given the current plan.

> I was just a little surprised to see a large increase in compiler warnings today

This is actually what I mostly meant by bothersome; especially if you are inspecting the list of warnings regularly (Obviously, I didn't start doing so yet :). So, if you want them gone, just say so.

**Comment by trav90** [comment]
While I can live with them myself, I do think it would be best in the long run if they could be fixed (if nothing else to prevent users from asking about it once they start building 27.2.0 themselves).

**Comment by wolfbeast** [comment]
So, has anyone been able to give this a good test on a selection of sample images yet?
I gather the code itself is stable enough since it's been baking on trunk for a little while now; just need functional feedback.

**Comment by rhinoduck** [comment]
This is what I used for testing:
http://rhinoduck.net/palemoon/github/issues/105/imgout/
(Only `cloud` and `rock_transparent` have transparecy. The `more` subdirectory contains the same images in various qualities.)

This I used to test the problem with transparent areas in tiled backgrounds being black:
http://rhinoduck.net/palemoon/github/issues/105/bgtest/

This I used to test whether disrupted connection/incomplete data no longer crashes the decoder:
http://rhinoduck.net/palemoon/github/issues/105/slow/
(The images under this folder are expected not to load; and the browser is expected to hold.)

What I did not test yet are the CMYK formats and embedded colour profiles.

It would be nice if we had a real-world gallery to test on; unfortunately, I don't know of any.

**Comment by wolfbeast** [comment]
I've been wanting to verify implementation with these links but your bgtest links are broken.

**Comment by wolfbeast** [comment]
othe rimages with different encodings all verify correctly, so considering this otherwise solved and ready for bounty payment. Please send your paypal e-mail address to moonchild@palemoon.org and we'll get that going.

**Comment by rhinoduck** [comment]
> I've been wanting to verify implementation with these links but your bgtest links are broken.

The HTML documents in the directory the link leads to should have the cloud image tiled in the background, the link works for me and the background shows. Maybe I could have amended the HTML a bit more though (sorry) as the foreground image src and link is broken. What was the problem you had?

---

CMYK format and embedded colour profiles work, here are the images I tested with:

[CMYK32](http://rhinoduck.net/palemoon/github/issues/105/temp/dog_cmyk.jxr)
[BGR24 + embedded colour profile](http://rhinoduck.net/palemoon/github/issues/105/temp/dog_with_color_profile.jxr)
[PBGRA32 (planar) + embedded colour profile](http://rhinoduck.net/palemoon/github/issues/105/temp/rock_transparent_spatial_planaralpha_withcolorprofile.jxr)
[PBGRA32 (interleaved) + embedded colour profile](http://rhinoduck.net/palemoon/github/issues/105/temp/rock_transparent_spatial_interleavedalpha_withcolorprofile.jxr)

The colour profile ([source](http://www.brisk.org.uk/photog/profile3.html)) basically swaps reds and greens so the difference should be easily observable. I noticed that the MSOT code does not honour the `gfx.color_management.mode` pref, it just always behaves as if the value was 2 (color management is on for images which have embedded profiles); the rewrite already honours the pref.

---

I also (finally) realised that the (public) `slow` folder never actually worked (because of the interrupted transfers), so I created the [slow-transfer](http://rhinoduck.net/palemoon/github/issues/105/slow-transfer/) folder which has the transfer speed capped at 32 kbps so that the progressive/chunked decoding can be triggered and seen.

During this, I noticed there was a difference between how the cloud image with [interleaved](http://rhinoduck.net/palemoon/github/issues/105/slow-transfer/bgtest/cloud_spatial_lossless_interleavedalpha.html) and [planar](http://rhinoduck.net/palemoon/github/issues/105/slow-transfer/bgtest/cloud_spatial_lossless_planaralpha.html) alpha shows up; the rewritten version does not have this problem. 

---

Since the rewrite is almost done, I'd prefer finishing it to fixing the above-mentioned things in the MSOT code. But, besides those two, as of this moment I am not aware of any other issues in the currently commited Pale Moon side of the decoder, so this is a usable version as well; I just find the code rather hard to navigate.

---

Lastly, as a funny sidenote, Edge and IE advertise `image/jxr`, but they do not recognise the `image/jxr` MIME type when they receive a response from the server, they only decode what comes back as `image/vnd.ms-photo`; I really can't say I know what the though behind that was. Anyway, Pale Moon recognises both MIME types so that should cover all sane and insane variations.

**Comment by rhinoduck** [comment]
A quick fix for some needless ugliness which can be applied now: https://github.com/MoonchildProductions/Pale-Moon/pull/958

I don't know how far on the way to the door 27.2 is, but the rest should probably not be waited for; unless that is what you will want.

**Comment by wolfbeast** [comment]
27.2 is pretty much on the doorstep - I'll drop in the enhancement as a last-second addition, and the rewrite as proposed can be landed on trunk for the next release. I'll open a new issue for that with your description, since we have basic JXR support now.

**Comment by wolfbeast** [comment]
The slow-transfer still doesn't work

````
Not Found

The requested URL /palemoon/github/issues/105/slow-transfer/bgtest/dogonatrain_large.jxr was not found on this server.
````

**Comment by wolfbeast** [comment]
Since our support in MSOT fashion is pretty much complete, I'll enable jxr support by default. People can always switch it off if it causes issues for them.

**Comment by rhinoduck** [comment]
> The slow-transfer still doesn't work

The foreground image and the link are irrelevant to the bg test, they just remained there when I quickly reused the HTML; I am sorry if it caused confusion. I modified the documents and everything should be clear now.

---

A thought occurred to me today while outside wrt the issue which presented itself after slow rendering of the cloud image with planar alpha, and sure enough, that was it; It should have hit me immediately. Here is another little fix since it was easy to do: https://github.com/MoonchildProductions/Pale-Moon/pull/964
