### ISSUE TITLE
Useragent

### ISSUE THREAD

**Issue by yoursoftwarebug** [MoonchildProductions/Pale-Moon#1064]
When I select "Firefox compatibility" mode, I want Palemoon NOT to send palemoon's UA
but send Firefox's generic UA to websites.

You are forcefully using Palemoon UserAgent to various websites. This allows them to track users.
Why did you do this?

**Comment by wolfbeast** [comment]
User agent compatibility mode isn't there for anti-tracking or privacy. It's there for web compatibility, since too many websites insist on restricting themselves to "the big three".

Since we are not Firefox and we _are_ different, sending a generic Firefox UA would prevent websites from doing the right thing and adding Pale Moon as a separate case to consider. That's not a good thing to do.

Those sites that have specific overrides in place, need those overrides to function.
