### ISSUE TITLE
Unable to load a certain site in Pale Moon 25.5.0

### ISSUE THREAD

**Issue by Axiomatic-** [MoonchildProductions/Pale-Moon#108]
Posted a thread on the [forum](https://forum.palemoon.org/viewtopic.php?f=37&t=8598), and @squarefractal was able to reproduce the issue I was having, which is that Pale Moon fails to load the website, and returns a blank page instead. The website is https://netacad.com/ 

Hopefully to make it easier here is the console output of the site:
```
SyntaxError: invalid range in character class @ https://d1ej7ofr54nmsd.cloudfront.net/netacad-public-theme/js/assets.js:30
ReferenceError: angular is not defined @ https://d1ej7ofr54nmsd.cloudfront.net/netacad-public-theme/js/netspace.js:25
ReferenceError: $ is not defined @ https://www.netacad.com/:1
GET https://d1ej7ofr54nmsd.cloudfront.net/netacad-public-theme/fonts/CiscoSansTTLight.woff [HTTP/1.1 200 OK 3883ms]
ReferenceError: Munchkin is not defined @ https://www.netacad.com/:1
```

Not quite sure where to go from here, let me know if I can provide help with anything.

**Comment by wolfbeast** [comment]
The problem is bad regex, and the fact that they use AngularJS which doesn't render *anything** if there's but one error in the js used.
This isn't a Pale Moon problem. This is a problem with the site using bad regex in the netacad theme.

Short of changing the regex library to one that doesn't strictly check ranges with reserved characters (which would just be promoting lazy/bad use of regex on more sites) there's nothing that can be done on the browser side.

``` javascript
Source Code:
){if(!val)return[];var values=[];$.each(val.split(func?func:/[,|-\s]\s*/g),function(i,str){str=$.trim(str);if(str.length
```
The offending bit is ```func?func:/[,|-\s]\s*/g``` since [,|-\s] is invalid regex. Reserved characters MUST be escaped, either by escaping individual characters with \ or by bracing it with \Q and \E to make it a literal.

**Comment by Axiomatic-** [comment]
All right, thank you for letting me know I will see if I can contact someone on their end to notify them of the issue, and hopefully get them to fix it.

**Comment by wolfbeast** [comment]
If it's a common enough issue (I would think/hope not, though!) then we can see about adopting a less strict/correct RegEx engine like irregex, but it's not something I'm wanting to do if I can help it (and likely won't work on implementing personally, so it'll have to be a patch from one of the community members).

Relevant BMO bug according to @squarefractal is https://bugzilla.mozilla.org/show_bug.cgi?id=976446
Specifically, I'd prefer the patch that retains YARR as an option since it's tried-and-tested, *if* we're going this route, with a close eye on dependent/blocking bugs there to avoid pitfalls.
