### ISSUE TITLE
border-collapse <table> borders are not same width when decimal zoom

### ISSUE THREAD

**Issue by zcyzcy88** [MoonchildProductions/Pale-Moon#1141]
Firefox isomorphic: https://bugzilla.mozilla.org/show_bug.cgi?id=895096

## Step
- View a `<table>` [(example)](https://ja.wikipedia.org/wiki/%E3%82%86%E3%81%A8%E3%82%8A%E6%95%99%E8%82%B2#.E3.82.86.E3.81.A8.E3.82.8A.E6.95.99.E8.82.B2.E3.81.AE.E7.B5.90.E6.9E.9C)
- Zoom

## Now
<img width="802" alt="Pale Moon" src="https://cloud.githubusercontent.com/assets/15178410/26761965/a26ea0c4-496b-11e7-81b2-834ea7097adf.png">

## Expect
Rendered by MS Edge
<img width="815" alt="Edge" src="https://cloud.githubusercontent.com/assets/15178410/26761966/aa3a3250-496b-11e7-9a0a-2d5a81ac76e1.png">

**Comment by wolfbeast** [comment]
If you zoom, you may end up with an uneven distribution of lines on device pixels. Position and width will be sub-pixel, and the rounding involved may draw some lines thicker than others. To keep rendering crisp, this can't be treated like images would.

**Comment by zcyzcy88** [comment]
But other borders (example: `<div>` borders, `<table>` with `border-collapse: separate`) are always even, when zoom.
So you should find a solution.

**Comment by wolfbeast** [comment]
There is certainly an issue with rounding, and it's caused by (as the BZ bug states) the wrong type of units being in use in the calculation. My response was simply some background information.

I'm not entirely sure why this bug went stale at Mozilla; the patch seems to be a good approach and easy enough to implement to fix an obvious bug.

**Comment by wolfbeast** [comment]
Verified fixed with the table indicated at various zoom levels.
