### ISSUE TITLE
 Not allowing pages to choose their own fonts breaks the line-height of icon-font

### ISSUE THREAD

**Issue by zcyzcy88** [MoonchildProductions/Pale-Moon#1143]
Firefox isomorphic: https://bugzilla.mozilla.org/show_bug.cgi?id=1362883

## Step
1. Visit the page contains icon-font (e.g. twitter)
2. Toggle the setting

## Now
The line height is too height
https://cloud.githubusercontent.com/assets/15178410/25785262/00d58736-33af-11e7-837a-59b2ed6af307.png

## Expect
Normal line height
https://cloud.githubusercontent.com/assets/15178410/25785263/01167692-33af-11e7-8481-fa34da5187ff.png

**Comment by wolfbeast** [comment]
Fonts have intrinsic heights. If you exchange fonts for other fonts, you can and will run into alignment issues if the intrinsic height is different. If you want proper alignment of fonts, then you have to let the website display itself as-intended (with custom fonts) because that is what it is designed with.

**Comment by zcyzcy88** [comment]
I not mean the text fonts.
"Not allowing own fonts" keep the shape of icon-font, but change (ignored) the intrinsic height of icon-font, cause icon-font too high.

**Comment by wolfbeast** [comment]
If you think there is a bug, then please provide a reduced test case demonstrating that icon font glyphs are displayed incorrectly. I don't see anything unexpected with the screenshots you provided.
