### ISSUE TITLE
text with `rem` too inflated by minimum font-size

### ISSUE THREAD

**Issue by zcyzcy88** [MoonchildProductions/Pale-Moon#1153]
Firefox isomorphic: https://bugzilla.mozilla.org/show_bug.cgi?id=1204057

Demo: https://codepen.io/SitePoint/pen/GpmvaG?editors=1100

1. turn off minimum font-size (don't forget to click OK), view the page
> <img width="1228" alt="2017-06-07 22_56_59-unnamed - pale moon" src="https://user-images.githubusercontent.com/15178410/26885289-da140350-4bd4-11e7-9144-62282e11b7c0.png">

2. turn on minimum font-size (such as 10px), view the page
> <img width="1228" alt="2017-06-07 22_56_50-unnamed - pale moon" src="https://user-images.githubusercontent.com/15178410/26885302-e1bae998-4bd4-11e7-87ee-d03618f546e6.png">

The text in `<p>` is too big.
First, `<html>` text size is "minimum font-size" from 1px to 10px, then `rem` base on 10px, 10px * 14rem = 140px.

And, `em` unit is not have this bug.

**Comment by wolfbeast** [comment]
This behaves exactly as expected. It's not a bug.

You set the minimum font size to something that is to be treated as a floor value. That applies to the root element. Any `rem` css scaling based on that will be relative to the floor value on the root element. So, 10px floor * 14rem = 140px high. That's correct.

It's not our task to counter insane design choices where people want to use `rem` as `px` units.

**Comment by zcyzcy88** [comment]
> It's not our task to counter insane design choices where people want to use `rem` as `px` units

No, this is not insane, this is helpful to responsive design.

---

Now wrong logic:

1. **apply "minimum font-size" on `<html>`**
`min(1px, 10px) = 10px`

2. **calculate `rem` to `px` based on inflated `<html>`**
`10px * 14rem = 140px`

3. **render `<p>`**



Normal logic:

1. **calculate `rem` to `px` based on `<html>`**
`1px * 14rem = 14px`

2. **apply "minimum font-size" on `<p>`**
`min(14px, 10px) = 14px`

3. **render `<p>`**

**Comment by wolfbeast** [comment]
No, it's not helpful. If you think your way of going about it is logical then you have clearly not understood what the `rem` and `em` units are meant to be used for.

Bottom line is **YOU** set a minimum value for font size, meaning no font may ever be smaller than that setting, so any relative measurements should be calculated based on the actual used font size in that case. This means that using `max(1px, 10px) = 10px` is exactly correct.

And you may disagree but setting a font size to 1px is insanity in design.

**Comment by zcyzcy88** [comment]
> When people are sizing the root to 1px and then using rems everywhere else to mean px -- well, that's not the intended use of 'rem'.
[#C29](https://bugzilla.mozilla.org/show_bug.cgi?id=816948#c29)

I totally agree "set root to 1px" is crazy.

---

A more normal usage is: 

> `html { font-size: 62.5% }` and use [ bigger than 1 rem ] everywhere else.
[#C9](https://bugzilla.mozilla.org/show_bug.cgi?id=816948#c9)

Note:
`16px * 62.5% = 10px`, do this for easy code written, and also can based on user-defined-font-size

---

I edit and repeat my logic,
if you can't move "minimum-font-size check" to the end of calculating process chain:

1. apply "minimum font-size" on `<html>`
`max(1px, 10px) = 10px`

2. calculate `rem` to `px` based on **non-inflated** `<html>` (ignore the inflation that at before)
`1px * 14rem = 14px`

3. apply "minimum font-size" on `<p>`
`max(14px, 10px) = 14px`

4. render <p>

**Comment by wolfbeast** [comment]
You still don't seem to understand understand what I'm trying to say. The logic as we have it right now is perfectly sound. If you use relative scaling, then if the user sets a hard minimum size, that size should be used for relative scaling as well, or you're creating a discrepancy in the page design by not scaling proportionally.

**Comment by zcyzcy88** [comment]
_You still don't seem to understand understand what I'm trying to say._
No, I pretty understand.

> If a page's root element's font size is too small for the user to read and they've increased it, then if they've sized other things relative to that font size, those things should increase since the author asked for them to be relative to the root element's font size.
[#C29](https://bugzilla.mozilla.org/show_bug.cgi?id=816948#c29)

---

But, the foolish page ignore the real semantic of `rem`.

And you still use "page use the real semantic" as a precondition (This is OK, but **unrealistic**),
Keep `rem` **always relative** to root font size, cause too big font.

Too big font break the accessibility.

---

Why I use minimum font size?
Anti too-small-font, for good accessibility.

What your logic leads to?
In foolish page, either too big or too small, break the accessibility.

You goal:
**Keep the semantic of `rem`**

My goal:
**Good accessibility**

> And no, I guess there is no spec issue, it is a conflict of ideologies.
[#C31](https://bugzilla.mozilla.org/show_bug.cgi?id=816948#c29)

**Comment by wolfbeast** [comment]
I don't care what pieces of different Mozilla bugs you quote.

The way it is implemented right now is correct. it has nothing to do with semantics, and everything to do with the following corner case:
- A website uses `rem` in a way that it was not meant for, **and**
- A user forces a minimum base font size (a "wallpapering" accessibility setting) instead of using page zoom to enlarge text

Our implementation adheres to the base font size and scales everything relatively to that. **That is, by definition, the way `rem` works.** If you don't want that to happen, then you shouldn't be using `rem` in your web design, to begin with. Responsive design can also be done a lot better than using `rem` as if it was a magic wand (the lazy way out).

Ergo: the accessibility problem is on the side of the website, not the browser. If you run into such sites, you should let the webmasters know about this corner case.
I'm restricting further comments on this issue. If you want to discuss your perceived bug, feel free to do so on bugzilla or our forum. If there's a clear, uniform, acceptable resolution then I'll happily re-open this issue to implement a change, but as it stands now there simply is no reason to do this. I repeat: it's not our task to try and counter bad site design. It is folly to even try.
