### ISSUE TITLE
some support for gcc 4.4

### ISSUE THREAD

**Issue by mckaygerhard** [MoonchildProductions/Pale-Moon#1161]
due palemon are based on firefox, since firefox 20 

the gcc << 4.5 was removed (firefox 26+) and unsupported.. this make palemon unnavailable for older but supported combinations like embebed devices or older but mantained versions of linux

please some grade of support for gcc 4.4

**Comment by trav90** [comment]
Sorry, but the minimum version we support is GCC 4.7 (and has been for some time). There have been numerous changes made to our code that requires a more recent version in order to compile. It would be a very large undertaking to go through all 14 million lines of code in our tree and find all the places where early versions of GCC choke at. It simply is not feasible to invest that much time into supporting an ancient compiler.

**Comment by trav90** [comment]
As an aside, it is possible to install a newer version of GCC on many of the older but still maintained versions of Linux you mention. Or as another option, you could compile Pale Moon on an older distro (such as CentOS 6) to provide better compatibility for other older distros.
