### ISSUE TITLE
Fix vector leaks and append calls.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1254]
Our vector code is rather messy at the moment and causes issues on some sites by leaking.
We need to port https://bugzilla.mozilla.org/show_bug.cgi?id=1231224 to clean this up.
See also: https://forum.palemoon.org/viewtopic.php?f=57&t=16216

**Comment by janekptacijarabaci** [comment]
Ad https://forum.palemoon.org/viewtopic.php?f=57&t=16216

See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1225396
AFAIK - this problem is more likely:
https://shared.reliclink.com/d…990ac4794ed.live-shared.min.js
`try{for(var _step,_iterator=componentClass.theme.classes[Symbol.iterator]()...`

**Comment by wolfbeast** [comment]
Split off the iterator issue to #1256 -- that one should be implemented first, looks like.
