### ISSUE TITLE
Browser crash bug

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1265]
__The browser crashes with the following code:__
https://bugzilla.mozilla.org/attachment.cgi?id=8591225

This has been implemented:
https://bugzilla.mozilla.org/show_bug.cgi?id=1149891
but there is still a problem somewhere.

---

My suggestion: You add the label `Crash` and `Uplift Wanted` (`Tycho-bug` ?).

**Comment by wolfbeast** [comment]
No crash observed here.

**Comment by wolfbeast** [comment]
No crash observed with the test html when saved locally, but it does crash when loaded directly from the URL.

**Comment by wolfbeast** [comment]
No crash observed in the current unstable build, either locally or from the 'net.
Previous testing was done with the release build.

**Comment by JustOff** [comment]
I can still reproduce the crash using 27.5.0a1 / 20170723150958.

**Comment by janekptacijarabaci** [comment]
> I can still reproduce the crash using 27.5.0a1 / 20170723150958.

I also... Even with a clean profile.

**Comment by wolfbeast** [comment]
Hmm. Definitely odd. I hate intermittent crashes like that. Also, I don't see why this would still crash, but I can check if there's a potential wallpaper patch I can apply.

**Comment by wolfbeast** [comment]
I have a try build. Please let me know if this fixes your issues. I've tried many times loading and reloading the file with it and it won't crash with this build for me.

https://www.dropbox.com/s/ih4m3k5744255in/palemoon-27.5.0a1.win32.zip?dl=0

**Comment by JustOff** [comment]
It still crashes for me on clean profile with 100% reproducibility :anguished:

**Comment by wolfbeast** [comment]
I can reproduce in release, but with this patch in, the crash is gone, no matter what i try i can't make it crash any longer, so I do think it solves the problem. Not sure what's up with it still crashing for you...

I'll create a full unstable build with this extra check in, and you can try again.

**Comment by JustOff** [comment]
Meanwhile I tried to build with the fix above and saw that nsContentPolicy.cpp was not re-compiled for some reason, probably clobber is needed?

PS: The crush is still here ...

**Comment by wolfbeast** [comment]
See if 20170726192223 works better for you or not. It's a clobber build.

**Comment by JustOff** [comment]
It still crashes :worried:

**Comment by wolfbeast** [comment]
I dunno what to say. it's solved here.

**Comment by wolfbeast** [comment]
Can you make a crash dump of 20170726192223 and send that over so I can see what's going on when it crashes for you?

**Comment by JustOff** [comment]
Sorry, but it seem I can't manage to [install WinDbg](https://forum.palemoon.org/viewtopic.php?f=19&t=13044) ...

**Comment by wolfbeast** [comment]
@janekptacijarabaci what about you? since you were the one reporting it; does this unstable fix it for you or not, and if not, can you send me a crash dump?

**Comment by JustOff** [comment]
It seems I finally did it, see issue1265.zip on ftp.

**Comment by wolfbeast** [comment]
Okay.. Are you using non-standard settings for caching? Your call stack is completely different and seems to enter shouldload from a cache point/CC (which hasn't been touched). Otherwise your crash is a simple null deref and doesn't seem to be at all exploitable, unlike the UAF this issue was originally about, so that's not as big a problem.

**Comment by JustOff** [comment]
I can't say I understood all you said above, but my dump was taken from clean profile and clean Pale Moon installation, just replaced by the 20170726192223 unstable.

**Comment by wolfbeast** [comment]
The crash you're seeing happens from a completely different set of function calls. It's not a normal network load as I'd expect here. Do you even have Flash installed?

**Comment by JustOff** [comment]
Yes, I have latest Flash installed. Win7 x64 with all updates.

**Comment by wolfbeast** [comment]
@JustOff -- I think your crash might also be due to some triggered re-parsing as a result of the Yandex tools or Office hooking into the browser. I've verified all relevant code there and even compared it to current Mozilla and Basilisk code, and there aren't any differences to be seen in any function that's in your crash dump's call stack; I therefore suspect external influence causing this code path to be taken to begin with, confusing net load with cache load.

**Comment by JustOff** [comment]
Ok, I'll try to do more tests tomorrow and write back.

**Comment by janekptacijarabaci** [comment]
I sent the requested file: `issue1265_2017-07-27_07-50.zip` (with an *.dmp)

```
[JavaScript Error: "Blocked loading mixed active content
"http://www.91jucai.com/ckplayer/ckplayer.swf""
{file: "https://bug1149891.bmoattachments.org/attachment.cgi?id=8591225" line: 0}]
(1d54.6f0): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
*** WARNING: Unable to verify checksum for C:\[path]\palemoon\xul.dll
*** ERROR: Symbol file could not be found. 
Defaulted to export symbols for C:\[path]\palemoon\xul.dll - 
eax=00000000 ebx=0d1f3950 ecx=0076f254 edx=00000000 esi=68d7b2e0 edi=097647c0
eip=67e4b9d7 esp=0076f1e8 ebp=00000000 iopl=0         nv up ei pl nz na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210206
xul!imgLoader::SupportImageWithMimeType+0xc82a7:
67e4b9d7 ff500c          call    dword ptr [eax+0Ch]  ds:002b:0000000c=????????
```

**Comment by wolfbeast** [comment]
Interesting. that's the same crash signature as JustOff's, that I can't reproduce.
What, **exactly**, are you guys doing to trigger this crash?

**Comment by janekptacijarabaci** [comment]
@wolfbeast 

1. I unzip the zip file (with the unstable Pale Moon) - i.e. where Pale Moon is not installed!
2. I start Pale Moon (`palemoon.exe`)
3. I'll open this page: `https://bugzilla.mozilla.org/attachment.cgi?id=8591225`
4. After the second (and any other) start - in the new profile (ad https://github.com/MoonchildProductions/Pale-Moon/issues/1265#issuecomment-318040331) - Pale Moon crashes.

**Comment by JustOff** [comment]
I do exactly the same. Now I tried to disable all plugins, but the crash is still happens. See also `issue1265extrainfo.justoff.zip` on ftp with my `about:support` + `about:plugins` data.

**Comment by janekptacijarabaci** [comment]
Btw, more devices, more OS (Windows 7 / 10).

**Comment by JustOff** [comment]
I just installed 20170726192223 unstable into *clean* Windows 10 Pro Insider Preview Build 16251 VMware box and it was immediately crashed by test url.

**Comment by wolfbeast** [comment]
Okay. able to reproduce if I use the portable version that has cache disabled, NOT able to reproduce with mach run from a build.

As for the crash itself though, there doesn't seem to be a reason at all for this to happen. All parameters check out before the CheckPolicy function call, and they are garbage afterwards. This might take some time to figure out.

**Comment by JustOff** [comment]
> Okay. able to reproduce if I use the portable version that has cache disabled, NOT able to reproduce with mach run from a build.

All my crash reports above are from regular (not portable) installations.

Also, I'm not sure if it might be helpful, but since this crash is also observed in Pale Moon 26, [here is the regression **fix** pushlog around Firefox 25](https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=5976b9c673f8&tochange=0888e29c83a3).

**Comment by wolfbeast** [comment]
I'm not sure if there is much we can do about this crash without rearchitecturing the way content security policies are done. Because the platform code has it in the DOM, as opposed to (previously) doing this in JS (another decision made because of b2g...) and OMTC makes compositing asynchronous, the crash occurs because a content policy check task is launched when the external item is added to the DOM, but the mutationobserver immediately removes it, yanking what is supposed to be checked out from under us. So it tries to access an object that no longer exists. This is very timing-critical, hence the reproduction issues I've seen, because often, on my system, it has enough time to access the object before it is removed.

The only proper solution would be to remove CSP from DOM, and put it back where it belongs.

**Comment by wolfbeast** [comment]
This should be solved by UXP.
