### ISSUE TITLE
Implement memory write-through cache

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/Pale-Moon#128]
This is intended to finally make proper use of the memory cache device

It was first landed in bc2513b23e033e20f05c6bdfecb5e747fde67b2e however it was reverted in e03fdaf086602caf4aebe3b147100a573fa912ed when it was found to cause a crashes due to when disk cache entries are evicted. This SEEMS to be a use-after-free condition on a bogus mDiskCacheEntry.

It will need to either be fixed to catch such a condition or be rethought out in implementation.

A possible simpler solution may involve just prioritizing memory over disk cache.

**Comment by wolfbeast** [comment]
Prioritizing memory over disk won't really work here, because then the disk cache would become just as under-used as the memory cache is currently.

We need to figure out where exactly this freeing occurs that makes the pointer still valid but the actual entry freed. The solution is very close to being perfect, but has this one snag.

**Comment by wolfbeast** [comment]
If we still want this, then it'll have to be completely rewritten for cache v2 in Tycho. There currently isn't any code to draw on that does this, and I have no documentation about how to integrate something like this or the intricacies of the new caching system.
