### ISSUE TITLE
Prevent loading of default home page when restoring session.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1310]
Currently, there is a race between loading the sessionstore file and browser startup. Mozilla's code only opts out of loading the home page when the session store file has been read and information is available, and at that point in time replaces the (partially or completely) loaded home page with whatever should be restored; probably in an attempt to get as much loaded as soon as possible to shave off more time from browser startup (the prominent telemetry property for health report).

See, e.g. https://forum.palemoon.org/viewtopic.php?f=3&t=14216

Almost always, loading sessionstore loses this race, and the home page load is initialized. This needs to be changed.

**Comment by Lorienna** [comment]
I'm not sure whether the following is a regression or an intentional change.

#### Steps to reproduce:
1. Launch Pale Moon.
2. In the main menu, select "Options" -> "General".
3. In the __Startup__ section of the "General" tab, choose `Show my windows and tabs from last time`.
4. Empty the __Home Page__ field.
5. Click <kbd>OK</kbd> button to save the settings and to close the "Options" window.
6. Press <kbd>Ctrl</kbd> + <kbd>N</kbd> to open a new __non-private__ window.

#### Current result:
An empty page.

#### Former result:
<img src="https://user-images.githubusercontent.com/26753987/32572610-314cbc04-c4dc-11e7-90bd-026332c8b9e6.png" width="559" alt="Former result" title="Former result">

**Comment by wolfbeast** [comment]
This needs a different approach than initially thought, because sessionrestore gets triggered upon creation of new windows, not just on application start. When opening a new window after startup, we **don't** want the home page to be overridden because nothing will be replacing it, which would leave us with a null content browser.

The root cause is Mozilla's "half-async" way this is set up. Session restore is async, but browser window initialization isn't.
