### ISSUE TITLE
Menu items "stick" in high-contrast mode on Windows 8

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#137]
https://forum.palemoon.org/viewtopic.php?f=3&t=8938

Both Classic and Appmenu are affected by this. it only affects enabled menu entries (disabled ones are fine).
Of note is that the secondary Appmenu is not affected while it gets the same styling.

Probably a typo or one-liner fix somewhere?

**Comment by mattatobin** [comment]
Is this still an issue in Tycho?

**Comment by wolfbeast** [comment]
Verified this is no longer an issue in 27.1.2 -- considered solved.

**Comment by tomasz1986** [comment]
Are you sure that the issue has been fixed? I still have it here with PaleMoon 27.6.2 in Windows 10 (1607 LTSB). From what I have seen the issue is not limited to Palemoon. It also affects older versions of Firefox and Thunderbird. It does not occur in Firefox 57 though.

Because of the theme I am using the situation is even worse here, since the highlighted part is displayed in black text on a black background.

Please check https://i.imgur.com/1nUT6eg.png.

**Comment by wolfbeast** [comment]
Yeah this issue has been fixed -- your screenshot displays a related but slightly different problem.
I'll open a new issue for it.
