### ISSUE TITLE
DN.no still needs a UA override

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#1376]
Could you please include a UA override for dn.no in Pale Moon's next point release (to avoid being served the mobile version)?
I've posted a override here that works:
https://github.com/MoonchildProductions/Pale-Moon/issues/1363#issuecomment-332004026
..although, I'm not sure if it's the "optimal" one.

**Comment by wolfbeast** [comment]
How many users would be impacted by this? I want to keep the list of preset overrides limited to high-profile/high-importance and global sites. For other sites it's best if local users add these overrides as a personal workaround, or pressure the sites in question to change their sniffing. If it serves a mobile site then it's a simple bug in their system.

**Comment by THEtomaso** [comment]
> How many users would be impacted by this?

349 000 Norwegians, according to this statistic:
http://www.medienorge.uib.no/statistikk/medium/ikt/395
It's our 5th largest news page.

**Comment by wolfbeast** [comment]
Taking into account our market share, that would be around 175 Pale Moon users. Not exactly a number I'd add a global SSUAO for just because of mobile detection.

**Comment by wolfbeast** [comment]
Marking won'tfix for now. If our numbers grow significantly end DN.NO at that point STILL does it wrong (meaning using an outdated detection lib), we can revisit this.

**Comment by THEtomaso** [comment]
Kind of unexpected to hear that kind of reasoning coming from you.
No disrespect, but I mean, if you're gonna take Pale Moon's market share into account every time you're gonna consider a fix, you hardly need to fix anything (to overstate things a bit).

The thing is that I'd like to recommend Pale Moon to as many people as possible.
But when it doesn't work by default with the most common sites, most users will simply discard it, and use a different browser instead.
Personally, I don't mind adding a UA override when needed, but as I'm sure you know, the average users don't want to mess around with stuff like that..
They just want things to work by default!

Like I've mentioned before; I already contacted DN.no regarding this issue last year, but they showed absolutely no interest in fixing it at their end.
In fact, they didn't even bother to send me a reply.
Probably for the best anyway..
From similar insidents, whenever I actually DO get a reply, it usually says something like "For the best web experience, we recommend using Google Chrome". :(

**Comment by wolfbeast** [comment]
For the best web experience, I recommend that all of these people you want to recommend Pale Moon to complain to DN.no about their broken website, or simply use a different news outlet. UA overrides are at most a workaround, not a fix, and if we keep piling on more for small groups of users, the browser **will** get slow because every time we need to look up a domain name and set up a channel, it has to go over the entire list. **SSUAOs are very expensive to use.**

Your instant generalizing of anything that isn't catering specifically to your use of the browser is also tiresome. 
You clearly have no interest in stepping back and looking at the big picture. That's fine, but we'll remain in disagreement in that case. Refusing a band-aid for <200 users impacting >500,000 user's experience is a proportion that should NOT make you surprised. Would you care if 175 Indonesian people have the minor inconvenience of a mobile site display with a local shoe outlet? Of course not. Why would that be different to your case, then?

If you want to offer users an actual solution, then consider creating a browser extension that keeps an updated list of SSUAOs, similar to what adblockers do with filter lists. It can even be as simple as using our SSUAO feature and adding/removing site-specific overrides as prefs based on what is in your list, and you can extend your lists at will. Regional lists would be a good thing to consider in that case, too.

**Comment by THEtomaso** [comment]
Thanks for elaborating on this issue.

I wasn't aware that UA overrides actually affected the performance.
This certainly puts things into a different perspective.

The idea of an extension sounds good.
I wouldn't know the first thing about actually creating one though.

**Comment by wolfbeast** [comment]
I already elaborated on this before. It's exhausting to have to deal with this kind of back and forth every time I _dare_ to reject something. Next time just trust that I know what I'm doing?

**Comment by mattatobin** [comment]
@THEtomaso If I may remind you, the GitHub Issue Tracker is not meant for free-form discussion. Your responsibility as someone who creates a potential bug report on here is to make your report and be available for more information or to help verify the issue is fixed if it is deemed a valid issue,

It would be appreciated if you would keep your reports and responses limited to that scope and move any other discourse to the forums where detailed discussion belongs.

**Comment by THEtomaso** [comment]
Good news:
DN.no seems to have revised their UA sniffing.
They now serve the proper desktop version for Pale Moon's 'Firefox Compatibility' and 'Gecko Compatibility' modes. :)
Only 'Native' mode still requires a UA override.

**Comment by wolfbeast** [comment]
Good enough.
