### ISSUE TITLE
upgrade zlib

### ISSUE THREAD

**Issue by roytam1** [MoonchildProductions/Pale-Moon#1377]
Here is a patch that updates modules/zlib and security/nss/lib/zlib to Cloudflare's zlib fork.

Please rename to cf-zlib_diff.zip as github doesn't allow me to upload diff or zip directly.
[cf-zlib_diff.zip](https://github.com/MoonchildProductions/Pale-Moon/files/1342661/cf-zlib_diff.docx)

**Comment by wolfbeast** [comment]
Can you please indicate the reason for suggesting this zlib fork?

**Comment by roytam1** [comment]
Cloudflare's zlib is faster on decompression.
And nss' zlib seems quite old.

**Comment by mattatobin** [comment]
`modules/zlib/src` - zlib 1.2.8 - Mozilla is currently at zlib 1.2.11
`security/nss/lib/zlib` - zlib 1.2.5 - Same as Mozilla's current trunk

I am not sure if nss builds its own private zlib but we should keep it matched with relative upstream version of nss version we use.

As for the main zlib in `modules` maybe an update is needed if it has anything desirable... It shall have to be evaluated. I do not think we should be using some sort of screwed over non-standard fork of this lib as there are doubtless Mozilla-inherited concerns we may need to be worried about.

**Comment by wolfbeast** [comment]
I had a quick glance over the diff and it doesn't even seem like CF's version does much of substance at all, apart from making the zlib behave less like a generic lib (by removing a lot of preprocessor conditionals).

The optimizations that _are_ there seem to be based on assumptions of specific hardware and very focused on the use of gcc (not MSVC) so it won't even impact 95% of our users. Have you actually built the browser with these changes and compared it with what we ship now? What numbers are we looking at? Considering zlib is an essential core module (especially if you want to touch NSS's version which is probably a bad idea because of extra sec considerations) that will break literally everything if it busts, I'm not going to update it on a whim.
