### ISSUE TITLE
Update the internal version to work with add-ons packaged with the add-on's SDK cfx tool

### ISSUE THREAD

**Issue by antoyo** [MoonchildProductions/Pale-Moon#140]
Hello.
It would be nice to update the internal version number of Palemoon (which is 21 I think), to be compatible with add-ons packaged with the cfx tool from the add-on SDK (`cfx xpi`).
The `minVersion` set by the tool is 26.
So, please update the internal version to at least this number.
Thanks.

By the way, one of my add-on (Auto-sort bookmarks) is compatible with Palemoon, but is listed in the page *Known Incompatible Add-ons*. I think one version of my add-on was not compatible with Palemoon due to this issue, but I update the `minVersion` tag manually at each release. Could you please give me additional information?

**Comment by wolfbeast** [comment]
This can't be done, because the later add-on SDK builds on significantly changed front-end code that we do not support. Updating the internal version presented to add-ons to 26 would break many non-SDK and SDK add-ons alike.

SDK add-ons for Pale Moon should be built against the Pale Moon add-on SDK. Yes, this means that you need to build and maintain a separate version for Pale Moon, but that is going to be needed anyway, regardless of type, as we drift further apart.

**Comment by antoyo** [comment]
Could you answer my last question please?

And for the issue with the add-on SDK, could you update the PaleMoon add-on SDK to provide shims for the missing features? It would allow many add-ons to work on PaleMoon without having to develop two versions of the add-on.

**Comment by wolfbeast** [comment]
The last question is off-topic for development or this issue. Please go to the forum and address it in the extension compatibility board there.

We are currently extremely busy with core work, and do not have time to look into the differences in SDK code. Shims may not suffice, either. it's unfortunate that Mozilla has taken the premise behind the SDK being browser-version-independent as initially advertised and trodden over it, but that's where we are now. If you wish to contribute and help close the gap, then your are more than welcome!

**Comment by wolfbeast** [comment]
I've given this some more thought, and the main issue simply is that building with the Mozilla SDK makes it incompatible with us. The same Jetpack add-on, when built/compiled with our SDK instead would produce a compatible add-on for us (but possibly not for Firefox). they are mutually exclusive.

This is why we have the option to build exclusively for Pale Moon, to begin with. Trying for us to force 100% Firefox compatibility is battling a symptom rather than addressing the cause. In the case of Jetpack, the cause is not using the right SDK for our product. The same source code can, however, in many cases, use our SDK without changes. The only thing we'd need help with would be extending our SDK with shims to provide broader compatibility with later FF SDK add-ons, but they would still have to be built/compiled with **our** SDK to be compatible with us. i.e.: we can improve the compatibility for jetpack source code so more will build correctly on our SDK, but we can't solve the incompatibility with the Firefox SDK because the code *it* spits out is incompatible with us. Updating our extension compat version as a cheap workaround for this is a no-go, since it will break XUL, bootstrap and SDK add-ons that check extension compatibility versions.
