### ISSUE TITLE
Improve contrast and consistency of toolbar buttons on various backgrounds.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1405]
Looks like we need some additional tweaks to make this work on accent colored toolbar backgrounds properly.

Discussion: see https://forum.palemoon.org/viewtopic.php?f=3&t=16977

Probably needs a few `@media(--accent-color-applies)` or similar rules to check the backdrop color for the special case of the downloads button, to make it respond as-intended.

@Lootyhoof, do you have time to look at this, or shall I try to squeeze it in?

**Comment by Lootyhoof** [comment]
I'll take this one. It needs a few design decisions, anyway, since this always looks out-of-place when none of the other buttons respond in the same way (not just Win10, even if that's most prominent). Namely:

- Is there a reason we're treating this button differently to others? (I'm sure this was discussed somewhere, but..)
- Is it worthwhile to style others in the same way, in a `brighttext` situation?
- Do we want the black/dark background, in any `brighttext` situation with this button (or any)? I'm aware it's like this for `lwtheme` styles, though arguably they are slightly different to normal window decorations.

**Comment by wolfbeast** [comment]
- It's treated differently because Mozilla treated it differently (Because it's both an indicator and a button all rolled into one). 
- I don't think the actual button background should behave differently to other toolbar buttons.
- I think with the case of Windows 10 accent colors resulting in a `brighttext` situation, it should behave differently than in a `darktext` situation; probably an inverse effect like with lightweight themes is a good idea.

**Comment by Lootyhoof** [comment]
So we want to keep the background colour the same, but change the icon still? Or change all the buttons to a dark, inverted style when there's `brighttext`?

**Comment by wolfbeast** [comment]
I think you lost me there. What?

**Comment by wolfbeast** [comment]
OK, I re-read what you said, I think we should, on Windows 10 when there's a dark accent color/light text combo, behave like we do with `brighttext` lightweight themes. i.e.: inverted icons and button effects.

Whatever we choose though, we should make sure that the behavior of the buttons is consistent no matter which button it is.

**Comment by Lootyhoof** [comment]
Should this also apply to other `brighttext` situations? I'm mostly referring to if there's a dark system theme on some other Windows system, or some other edge-case setup that has everything be quite dark.

**Comment by wolfbeast** [comment]
I don't think so. We already use system colors where it's needed, and if an edge case causes an issue it's usually already on a system where someone would use a dark or black full theme anyway.

**Comment by Lootyhoof** [comment]
Hmm...I've found time to take a look at what I did back in #849, and I mostly agree with that (that's what I get for not looking into things before suggesting changes...), except for some minor changes to only show that dark styling when `counter` is true (i.e. when you can see the text on the indicator, which was the reason we made it look like this), and as for the other styling, I feel the current styling provides enough contrast even on darker backgrounds (though do let me know if this doesn't look good to you):

![Win10 dark background](https://i.imgur.com/ycrCYhl.png)

Interestingly, though, it seems our `brighttext` status is `true` even when `color` is `ThreeDShadow` (on Win10, this is `rgb(160, 160, 160)`). This is what is causing our indicator to look dark even on inactive windows (even in circumstances where the window background was not dark in active mode).

Apart from the weirdness above and the `counter` change I mentioned, I think the only thing we need here is to make `#downloads-indicator-icon` use `Toolbar-glass.png` like the others (since this seems to override our `brighttext` styling, which creates the icons you see in my screenshot even on a dark background). I can do this, but not sure how you want to proceed with the `ThreeDShadow` issue (if it's an issue?).

**Comment by wolfbeast** [comment]
The contrast is just fine -- there's a reason I design the "on glass" icons the way I did ;)

I'm not sure exactly what the `ThreeDShadow` problem is you're talking about. Care to enlighten me with some screenshots?

**Comment by Lootyhoof** [comment]
With our current implementation, we set the `color` to `ThreeDShadow` for the window when it's inactive. For some reason, though, this flips `brighttext`. 

![Inactive Win10 window](https://i.imgur.com/36urGOQ.png)

**Comment by wolfbeast** [comment]
Then let's not set it to `ThreeDShadow`? `rgb(160, 160, 160)` Is probably just on the bright side of the flip point. We can probably just keep it black, but make it 50% transparent or something to change the effect while not having unintended side effects. Using 3D object effect colors for text has always struck me as incorrect to do anyway.

**Comment by wolfbeast** [comment]
I've tested behavior of the merged PR on Windows 7 with a variety of lightweight themes to make sure it's all still working as it should, and it all looks good. I haven't tested Win 8 or 10. Assuming you have 10 covered; are you in the position to also throw it on Win 8?

**Comment by mattatobin** [comment]
How does this look on Windows Classic

**Comment by wolfbeast** [comment]
Windows Classic shouldn't be impacted -- this is all in the aero sections.

**Comment by Lootyhoof** [comment]
I'll fire up my Win8 VM tonight and let you know.

As an aside: it might be useful to remove the `Theme changes` tag since third-party themes aren't affected by this.

**Comment by Lootyhoof** [comment]
Looks good to me on Windows 8 also.

Though...I will admit that I did forget about Windows Classic. Opened #1418 to fix.

**Comment by wolfbeast** [comment]
Closing as verified then.
