### ISSUE TITLE
100% cpu usage on SDR sites using HTML5 Possibly vcomp120.dll 

### ISSUE THREAD

**Issue by GitCartel** [MoonchildProductions/Pale-Moon#1425]
http://websdr.ewi.utwente.nl:8901/
CPU is maxxed out on 8 cores, audio will stop if other tabs or windows are surfed or eventually on its own it will stop.  Old version 26.0.1 works fine, no issues.

27.5.1 X64 or X32
**Clean profile** or not
W7 X64

27.5.1 X64
![2017098](https://user-images.githubusercontent.com/30365972/31931697-e03472a6-b858-11e7-82d2-7b0fb70de319.jpg)

27.5.1 X64
![2017100](https://user-images.githubusercontent.com/30365972/31931699-e0650a1a-b858-11e7-84a0-d234311ecf0b.jpg)

**26.0.1**
![2017099](https://user-images.githubusercontent.com/30365972/31931698-e04fdd2a-b858-11e7-8cd5-745df706d547.jpg)

**Comment by wolfbeast** [comment]
It seems the high cpu usage only occurs when it plays sound. Since it's in vcomp, I'm gathering that it's probably in one of the audio libraries that try to use multiple processor threads for audio processing, as we're not using the library explicitly ourselves.

@trav90 do you have any idea what might be the cause? Maybe there are some pragmas that got activated in third-party code  because of -openmp build optimization that don't play nice with us?

By the way: There's too much of a difference between v26 and v27 to have any sort of useful comparison in any case, so that really doesn't help. It's a massive rebasing milestone.

**Comment by wolfbeast** [comment]
Looks like the most likely culprits would be the PSNR module in `libyuv`, or the `kiss-fft` one.

**Comment by wolfbeast** [comment]
Confirmed that building without `-openmp` fixes the problem, so now the fun part figuring out which lib we should exclude from `-openmp` ;)

**Comment by wolfbeast** [comment]
Looks like it's the KISS-FFT library that causes issues with openMP. I'm assuming the extra code isn't properly threadsafe.

**Comment by wolfbeast** [comment]
Verified fixed.
![1425-1](https://user-images.githubusercontent.com/3359132/31971667-113a31b4-b91d-11e7-8383-7ca3a8e72fc9.png)

**Comment by GitCartel** [comment]
Thats awesome, thank you!

**Comment by roytam1** [comment]
> Looks like it's the KISS-FFT library that causes issues with openMP. I'm assuming the extra code isn't properly threadsafe.

This is an another old bug with fix not committed.
https://sourceforge.net/p/kissfft/bugs/10/

**Comment by wolfbeast** [comment]
Yeah, it's clear that OpenMP parallelization hasn't been properly tested in this lib. Since nobody has worked on this for 5 years I don't think it ever will, so the safe option is to simply not rely on this code.

**Comment by wolfbeast** [comment]
By the way, after talking to the lib dev, I've forked the library now to fix these parallelization issues to incorporate the fork of it in our browser(s) in the future. https://github.com/MoonchildProductions/kissfft
