### ISSUE TITLE
canplay and canplaythrough event are never fired when media element is paused. 

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1430]
This seems to be the cause for some iterations of JWPlayer not working (or with specific configurations, like loading in paused state).

See https://forum.palemoon.org/viewtopic.php?f=3&t=17109

@trav90 could you have a look at implementing this soon? I should push 27.6 out in not too much time now AUS has been moved over to the new infra, and it would be great to have this fixed.

**Comment by trav90** [comment]
I'll look into this soon.

**Comment by trav90** [comment]
Looks like this is due to a timing/race condition which would be solved by using StateMachinery. I've still been working towards hooking up more of the media subsystem to the StateMachinery (#1272), but it's very complex work and slow going.

In the meantime, I'll see if there's another way to work around this particular problem.

**Comment by wolfbeast** [comment]
Yeah, understood. If there's another way to work around this, that would be great. Otherwise people will just have to be patient.

**Comment by wolfbeast** [comment]
Looks like an update to v.8 of JWPlayer solved hitting this issue in our back-end so at least for the time being we won't need an emergency hack to work around it.
