### ISSUE TITLE
Issue with Scrum Diagram

### ISSUE THREAD

**Issue by MartinX3** [MoonchildProductions/Pale-Moon#1436]
https://creately.com/diagram/example/hnro36rt/Sprint%20im%20Scrum-Prozess

Version: 27.5.1 (64-bit)
Started with disabled addons

Viewable with Firefox

![firefox](https://user-images.githubusercontent.com/4518092/32146954-2dc9d6e8-bcdf-11e7-8636-a645d69762c1.png)
![palemoon](https://user-images.githubusercontent.com/4518092/32146955-2de89736-bcdf-11e7-894c-f0d5b0b24b7b.png)

**Comment by janekptacijarabaci** [comment]
Pushlog:
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=2235e56c94cf61614902fd3a4ac7b837f7154b97&tochange=19b4265d0d568d232fb3a34705f947b6db7496dc

Results: `undefined`

---

Pushlog:
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=96377bdbcdf3e444a22aeaa677da696243b00d98&tochange=451a185791433bce1a6a894c27f3da60a3119431

Results: OK

**Comment by MartinX3** [comment]
Is this information relevant for me?
I am not a C++ developer and never used the "mozilla-central"-tool. :(
Is there something I need to look at?

**Comment by janekptacijarabaci** [comment]
> Is this information relevant for me?

This information is for someone who's looking for a bug. You don't have to take this into consideration :-)

**Comment by Lorienna** [comment]
<table>
<th colspan="3">Tinderbox central ranges (win32)</th>
<tr>
<td align="center"><a href="https://hg.mozilla.org/mozilla-central/rev/46842118f0c94cb300d0eb7416dddf43b777dbab"><b>44.0a1</b></a> <a href="https://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-central-win32/1442965178/">(2015-09-22, 16:39:38)</a></td>
<td align="center"><a href="https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=46842118f0c94cb300d0eb7416dddf43b777dbab&tochange=05a7ee49d40a4cfabf2479337fd5e1312e178b6d">Pushlog</a></td>
<td align="center"><a href="https://hg.mozilla.org/mozilla-central/rev/05a7ee49d40a4cfabf2479337fd5e1312e178b6d"><b>44.0a1</b></a> <a href="https://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-central-win32/1442965365/">(2015-09-22, 16:42:45)</a></td>
</tr>
<tr>
<td colspan="3" align="center" height="65"><b>Results:</b> the word <q>undefined</q> appears at the top left corner of the interactive area<br>rather than <q>Sorry. We could not find the diagram you requested.</q> in the middle.</td>
</tr>
<tr>
<td align="center"><a href="https://hg.mozilla.org/mozilla-central/rev/fc0b155bdac7a43d28c13e0cdd281a7928e64e09"><b>45.0a1</b></a> <a href="https://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-central-win32/1446461526/">(2015-11-02, 02:52:06)</a></td>
<td align="center"><a href="https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=fc0b155bdac7a43d28c13e0cdd281a7928e64e09&tochange=451a185791433bce1a6a894c27f3da60a3119431">Pushlog</a></td>
<td align="center"><a href="https://hg.mozilla.org/mozilla-central/rev/451a185791433bce1a6a894c27f3da60a3119431"><b>45.0a1</b></a> <a href="https://archive.mozilla.org/pub/firefox/tinderbox-builds/mozilla-central-win32/1446461826/">(2015-11-02, 02:57:06)</a></td>
</tr>
<tr>
<td colspan="3" align="center" height="45"><b>Results:</b> the diagram displays normally.</td>
</tr>
</table>

**Comment by mattatobin** [comment]
So.. Another Soved by UXP mid-priority issue?

**Comment by wolfbeast** [comment]
Unknown. The pushlogs don't actually have any bugs that stand out.

**Comment by Lorienna** [comment]
Below are the results of testing against __tinderbox inbound__ builds.


## Results: "undefined"

- Pushlog - https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=4d45c4323570afd1a19695dea9f3c148a88891a4&tochange=d0814284126324de850f1b92dc230ec46a443c74

- [Bug 918742](https://bugzilla.mozilla.org/show_bug.cgi?id=918742) - [XHR2] Implementation doesn't fix author-supplied charset correctly and adds charset parameter when author doesn't set it

## Results: OK

- Pushlog - https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=798c82c8a96d1099cf712434d9c9036fc48d8297&tochange=9160f08660b8290559e427fd80d617edd86fe2a6

- [Bug 264412](https://bugzilla.mozilla.org/show_bug.cgi?id=264412) - Add support for `element.innerText`

**Comment by wolfbeast** [comment]
We've already added support for element.innerText. I also sincerely doubt some charset issue would cause this.

**Comment by wolfbeast** [comment]
Reading through the charset bug it seems to actually cause issues in the wild with compat... and it does look like some corners were cut in Mozilla's initial implementation.

Under the motto "can't hurt to try" I've ported the patch and it does, in fact, solve this particular website's issue.
