### ISSUE TITLE
Javascript method console.clear is missing

### ISSUE THREAD

**Issue by roytam1** [MoonchildProductions/Pale-Moon#1445]
LIHKG.com tries to use method console.clear unconditionally and causing whole site unusable.

**Comment by wolfbeast** [comment]
So complain to them?!

**Comment by wolfbeast** [comment]
As it seems, Mozilla ran into this as well and attempted to work around it by adding a non-standard catch-all to the console API. But that's broken in a few ways, so it wasn't done properly or is simply very fragile.
I'll see if I can add some no-op methods for specific "we assume these to be present" functions instead of trying and failing to catch everything that doesn't exist in the API.
