### ISSUE TITLE
[regression] A webpage - a big lag when scrolling

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1446]
Description of the regression:
- This page:
http://inktank.fi/the-17-most-wonderfully-weird-websites-on-the-internet/
is very sluggish and has (probably) high CPU usage when scrolling.

Affected versions:
- Pale Moon 27.4.0+

See also:
https://forum.palemoon.org/viewtopic.php?f=29&t=17225

#1362 is the suspect (although I cannot verify it now).

My suggestion / IMHO (for the future - or earlier, if they exist):
- An archive of (official) unstable versions would be good.

**Comment by wolfbeast** [comment]
I just tested a portable version of our current release and it doesn't lag either. Not sure what's going on.

**Comment by wolfbeast** [comment]
OK, it seems the problem is the background (the green border) -- it will lag if your screen is wide enough.
Backing out that patch didn't help.

**Comment by wolfbeast** [comment]
The problem seems to be the background (green border) -- it'll lag if the window is wide enough to show it.
Backing out the horizontal scroll patch did NOT help.

**Comment by wolfbeast** [comment]
No high CPU usage was seen on my system, but it does lag terribly.
I'll make a local build with your vertical-text scrolling patch backed out and see if that fixes it.

**Comment by wolfbeast** [comment]
There aren't all that many layout patches recently. One that stands out as a possible culprit is another one you submitted: 795ff324010703849d4437e381acac211d60e20a  -- can you please check if building without that fixes it?

**Comment by wolfbeast** [comment]
I just checked an unpatched unstable to verify it's a problem on trunk, and I can't reproduce the issue there.
Can you please verify this is still an issue in the latest unstable?

**Comment by wolfbeast** [comment]
(github is on the fritz with their timestamps, mixing comments out of order :/ I hope it still makes sense)

**Comment by janekptacijarabaci** [comment]
IMHO: The problem persists (unstable/2017-11-02, Win32) - i.e. on the new profile.

**Comment by janekptacijarabaci** [comment]
> can you please check if building without that fixes it?

I can't do it right now. But:

Pale Moon Portable win32 27.3.0 - OK
Pale Moon Portable win32 27.4.0 - a big lag

**Comment by wolfbeast** [comment]
OK I'll check the range, see what's there.

**Comment by wolfbeast** [comment]
I know the problem. It's their background image. it is an SVG with absolutely ridiculous pixel dimensions. Very large SVG images are not put in the surface cache because it kills the surface cache's effectiveness.

**Comment by janekptacijarabaci** [comment]
Update: A big lag, only if window width is greater than 806px:
For Scratchpad (Environment-Browser):
window.resizeTo(806, 1000);
- OK
window.resizeTo(807, 1000):
- a big lag

**Comment by wolfbeast** [comment]
There's something wrong with their SVG format to begin with, since it shows up in media as a 4Bx4B pixel image dimension SVG. I just loaded and saved it in inkscape, and also made a PNG export at their native resolution (that is half the file size, mind you); seems the SVG canvas is maxed, and the "image" is defined as a viewport.

This is something that will simply not work on the web. The webdesigners need to convert the SVG to something sane, and preferably not use an SVG source file as a static background image, but use a lossless raster format instead like PNG.

**Comment by wolfbeast** [comment]
The "regression" here is a side-effect of an optimization performed to make repeat scaling of SVG images smooth and fast.

**Comment by wolfbeast** [comment]
@janekptacijarabaci yes, it depends on whether the border shows or not. If it doesn't show, then Goanna will optimize it out (if you scroll all the way to the top you will still see lagging as it needs to process the SVG for each frame). Once more: this is a problem with their background being a very large dimension SVG, and the lag occurs because those are not put in the surface cache (as it would evict all other entries with a resize operation). The only way to make this particular site not lag would be to undo that surface cache optimization, OR for the website to use a raster format (which would save them bandwidth anyway).

**Comment by wolfbeast** [comment]
A compromise is possible here -- the cache limit is rather restrictive; allowing up to 32MB for cache element would allow for images of up to ~2850 px square that would not immediately evict everything in the surface cache. I've done some tests with the increased limit and the performance loss is very acceptable because it remains within the working bounds of the surface cache, while also allowing potentially poor design choices for SVG backgrounds.

**Comment by JustOff** [comment]
I confirm this resolves the issue.
