### ISSUE TITLE
Program returns random data in a function (no-return-in-nonvoid-function)

### ISSUE THREAD

**Issue by computersalat** [MoonchildProductions/Pale-Moon#1464]
build on Open Build Service fails cause of:

```
[ 1581s] I: Program returns random data in a function
[ 1581s] E: palemoon no-return-in-nonvoid-function /home/abuild/rpmbuild/BUILD/Pale-Moon-27.6.0_Release/dom/base/nsGlobalWindow.cpp:5696, 5713, 5730, 5747
```

**Comment by wolfbeast** [comment]
OpenBuildService should focus on building and not on static code analysis (which is obviously naive and can't even understand the use of macros)

http://xref.palemoon.org/palemoon-trunk/source/dom/base/nsGlobalWindow.cpp#328

Macro always returns something.

**Comment by computersalat** [comment]
@wolfbeast 
just wondering why someone is preparing a patch and referencing this issue when OBS static code checks produces bullshit warning ...

**Comment by mattatobin** [comment]
My question is why anyone is trying to fix nonbusting nonissue compiler warnings that ONLY obs trips on for a codebase that only has what.. 6 months of life left to it?

**Comment by wolfbeast** [comment]
If OBS treats warnings as errors, then that is OBS's fault. It shouldn't.
Also, it's a warning that has no grounds. If it warns on these functions, then it should warn on all `FORWARD_TO_OUTER_OR_THROW` macro calls where the call is in a non-void function, but it doesn't.

The patch, in fact, also doesn't do anything useful. the return values there are never reached because the macro either throws or returns a value in all cases.

@mattatobin the intended code base life isn't really relevant for a minor fix, but it isn't even a fix.

**Comment by wolfbeast** [comment]
I've merged it in anyway - it doesn't do anything but it also won't hurt in case the macro has unexpected quirks based on compiler in use (e.g. not exiting on a throw properly)

**Comment by computersalat** [comment]
@wolfbeast 
Thank you ... that patch removes mentioned complaints
