### ISSUE TITLE
Tab loading indicator for linux appears jerky after libPNG update

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/Pale-Moon#1474]
[Trobber](http://xref.palemoon.org/palemoon-trunk/source/browser/themes/linux/tabbrowser/loading.png): ![loading](https://user-images.githubusercontent.com/340855/32910454-f7d87cb0-cb11-11e7-8552-d911fd764109.png)

There may be problems with other animated png images too.

Reported [on forum](https://forum.palemoon.org/viewtopic.php?p=127292), related commit: [Update libPNG to 1.6.28 and enable SSE2](https://github.com/MoonchildProductions/Pale-Moon/commit/b23b65f852951a69cc8bebc54655496e556946ab).

**Comment by wolfbeast** [comment]
Hmm.. it seems there's something indeed wrong with decoding that particular animated image. It doesn't show because Linux is the only one that is using that particular throbber image.
I'll make a build without SSE2 intrinsics and see if that helps -- it's most likely a bug in the Intel SSE code in libPNG not playing nice with the Mozilla APNG patches.

**Comment by wolfbeast** [comment]
It's not the SSE2 code. I'll have to dig a little deeper.

**Comment by wolfbeast** [comment]
OK, so, looks like the throbber for Linux has invalid chunk bits, that with the libPNG update we now trip over, because our decoder doesn't actually allocate enough of a buffer (assuming the chunks are reported correctly). I think I know how to fix this.

**Comment by JustOff** [comment]
I checked this using local build, all is ok now :+1:
