### ISSUE TITLE
Remove accelerator key from Restart menu entry

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#1490]
Although the Restart menu item was received well, having the `Ctrl+Alt+R` accelerator for it isn't working well for people. Apart from not being available on certain keyboard layouts, it causes issues with some input methods for non-English users, where the diacritical `graphics alt` acts as `ctrl+alt` for the browser. This leads to unintended restarts of the browser with potential loss of data!

It's best to just remove the accelerator for the command to avoid these issues.

Follow-up to #1322

**Comment by wolfbeast** [comment]
Uplifted in ef4cf6159b21c743cda0c76a813dc5edde0ba6d1

**Comment by wolfbeast** [comment]
Uplifted in ef4cf6159b21c743cda0c76a813dc5edde0ba6d1

**Comment by JustOff** [comment]
Strings changes were pushed to CrowdIn.

**Comment by JustOff** [comment]
Now, after the accelerator has been removed, do we need a confirmation dialog when restarting, taking into account that the menu item "Exit" next to "Restart" does not ask for any confirmations?

**Comment by wolfbeast** [comment]
I think it certainly can't hurt to have a confirmation there. I'd at least expect a confirmation for that kind of action.

Exit also has a confirmation dialog, depending on your settings, by the way.

**Comment by graciecat** [comment]
There are extensions such as [Restart Manager](https://addons.mozilla.org/en-US/firefox/addon/restart-manager/) by GMaL and [Restart](https://addons.mozilla.org/en-US/firefox/addon/re-start/?src=search) by Schuzak that "restore" the Ctrl+Alt+R shortcut. They also allow you to reconfigure the shortcut to different keys. Unfortunately, they also add a duplicate Restart entry in the File menu.

Would it be possible to add a preference to remove the default Restart entry from the File menu, so that when [users who want the keyboard shortcut](https://forum.palemoon.org/viewtopic.php?f=4&t=17546&p=128457#p128457) install one of these extensions, they do not get this duplication?

![duplicate restart menu entries](https://user-images.githubusercontent.com/18286141/33265626-64ad0532-d340-11e7-8a11-b606466804fa.png)

**Comment by JustOff** [comment]
Just add this to [userChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css):
```
@-moz-document url("chrome://browser/content/browser.xul") {
  #menu_restart, #appmenu_restart {
   display: none !important;
  }
}
```

**Comment by wolfbeast** [comment]
The css overlay is something the extensions should do if they want to target Pale Moon.

**Comment by sergeevabc** [comment]
Ctrl+Alt+R is the restart combo used [i]for years[/i] by extensions mentioned earlier. When a native accelerator was introduced in Pale Moon, I removed the extension, even though some abilities were lost (e.g.  to disable the quit confirmation). Now a native accelerator is silently gone and I'm quite upset. Why not make it optional and bury into advanced options or even deeper?

**Comment by sergeevabc** [comment]
@graciecat, it is little consolation, but if you decide to use [Toolbarize Menu Button][1] instead of original Menu bar, then adding [QuickRestart][2] extension will bring Ctrl+Alt+R back without polluting button’s menu.

![](https://images.vfl.ru/ii/1511896269/4518fe9a/19608132.png)

[1]: https://addons.palemoon.org/addon/toolbarize-menu-button/
[2]: https://addons.mozilla.org/firefox/addon/3559

**Comment by sergeevabc** [comment]
@graciecat, digging deeper into Palemoon-specific extensions, I found out [Restart Browser][1] by riiis.
It does not add menu items for 27.5+, but brings the beloved combo back.

[1]: https://addons.palemoon.org/addon/restartbrowsernow/

**Comment by wolfbeast** [comment]
It doesn't matter that there is consensus among the users or devs of these **extensions**. A built-in accelerator key will apply to **every single user of the browser**, without exception. That is where the crux lies because that combo is not safe for all users.

Important: this is an issue tracker, not a forum -- side-discussion about which extensions work as alternatives etc. do not belong here.
