### ISSUE TITLE
Pale Moon 27.6.x keep login info if switch to Private Window

### ISSUE THREAD

**Issue by Symbian9** [MoonchildProductions/Pale-Moon#1491]
Currently if I login on Github (for example) in 'normal' window, then make "New Private Window" and switch on it -- I still shown as logged in if go to `http://github.com/` in 'private' window.

Version: 27.6.0 (64-bit)
OS: Linux Mint 18.2 Xfce (x86-64)

**Comment by wolfbeast** [comment]
Unable to confirm. If I open a private window while logged into github and go to `github.com`, I'm not logged in when using the private window.

**Comment by Symbian9** [comment]
![PaleMoon private bug](http://hnng.moe/f/Wtf)

**Comment by JustOff** [comment]
Can't confirm on Win7 / Mint 17.3, "New Private Window (Ctrl+Shift+P)" item is also in place.
Probably a conflicting add-on?

**Comment by Symbian9** [comment]
> Probably a conflicting add-on?

I just use only "uMatrix"  and "uBlock Origin" installed throw Pale Moon add-on's manager.

**Comment by wolfbeast** [comment]
Please post the output of help -> troubleshooting information so we know your exact environment (copy text to clipboard)

**Comment by wolfbeast** [comment]
Wait... Did you select "never remember history" in privacy options? If so, you are in permanent private browsing mode, and you will not have a separated environment in new private windows (nor have the option to open a normal new window) and then it's correct that you remain logged in.

**Comment by Symbian9** [comment]
> Did you select "never remember history" in privacy options? 

Yes.

> If so, you are in permanent private browsing mode, and you will not have a separated environment in new private windows (nor have the option to open a normal new window) and then it's correct that you remain logged in.

This look like a bug, really. Because, for keep 'private' functionality I must allow browser keep my history. 

> permanent private browsing mode

What? This not indicated by 'mask' icon in browser interface or "Private Mode" text in browser window tittle!

**Comment by wolfbeast** [comment]
Mozilla browsers have worked this way ever since private browsing was introduced. If you don't remember history, then your browsing session will be private by default and everything will be thrown away when you end your browsing session (close the browser). No indicators are shown in this mode because this is the "normal" setup for public computers. "Private mode" in the title bar is there only when you actually have a private window in a normal session to distinguish them from each other.
Also, even in private windows, history is kept for the session, but it is thrown away when you close that window (that is the nature of a private browsing window).

> Because, for keep 'private' functionality between two browser windows I must allow browser keep my history.

No, you don't -- you have to select "custom settings" for history if that's what you want, and select "clear history when Pale Moon closes" to automatically clear the items you don't want it to remember. If you need help with these specific settings, please post on the forum.

**Comment by Symbian9** [comment]
> If you don't remember history, then your browsing session will be private by default and everything will be thrown away when you end your browsing session (close the browser).

No! If I use private mode each window should not to know what password I use in another window!

**Comment by JustOff** [comment]
@Symbian9 
This is just how it works, and you have to accept this, see [SUMO](https://support.mozilla.org/en-US/kb/private-browsing-use-firefox-without-history).

**Comment by wolfbeast** [comment]
@Symbian9 The behavior you want is using the browser normally, and open private windows whenever you need a private/separate window. If you also don't want to remember history in the non-private "session window", then you need to set the options as I indicated to custom.

Permanent private browsing mode's operation will _not_ be changed.
