### ISSUE TITLE
[suggestion] Places (Bookmarks/History) - the tree - ctrl+backspace

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1543]
Ad https://forum.palemoon.org/viewtopic.php?f=29&t=15016#p108330

> In Bookmarks Manager, it would be cool if pressing Backspace when no text field has focus would move up to the parent folder like it does in Windows Explorer.

> You can use the left arrow. But the folders are closed...
> I can assign a key combination (the backspace - to return on previous page)

I don't know how this is acceptable... Would be some problems with it (e.g. on Linux)?

**Comment by mattatobin** [comment]
I think it is overall a bad idea. While in edge cases this is expected behavior on a webpage.. Places is not a webpage.

----

Additionally, would you stop creating noise with pull requests especially in this context where it may not even BE desired.

Also, when you work on an issue that has been like some of your recent ones.. You are creating issue after issue and pull request after pull request.

Do like the rest of us do and if you are working on a complex thing.. Wait until you are finished and it is verified on your tree and/or by our build testing before you submit your final clean pull request.

**Comment by janekptacijarabaci** [comment]
> Please also try not to submit pull requests for incomplete contributions

Is this some example:
#1528 
or something else?

Because I think it makes sense and is sufficiently clear...
If I don't take into account the names (with the number of the issue - due to a direct "connection") - I will now try to do this.

**Comment by wolfbeast** [comment]
This would create ambiguity in controls, for the benefit of just one person's workflow? Nope, sorry.
