### ISSUE TITLE
Provide an option to override the setting of TextQuality

### ISSUE THREAD

**Issue by zcyzcy88** [MoonchildProductions/Pale-Moon#1554]
Provide an option to overlay the setting of TextQuality

Succeed of #1155

I have read the source code and find 
https://github.com/MoonchildProductions/Pale-Moon/blob/5214789d035f4e4c08899a6e281116520f605ec6/gfx/2d/ScaledFontDWrite.cpp#L143-L167

The problem is not about rendering mode, is about text quality.

If Windows cleartype is on, gfx will use `CLEARTYPE_QUALITY` (sub pixel / true letter spacing)
If Windows cleartype is off, gfx will use `ANTIALIASED_QUALITY` (snap to pixel)

[Anti-Aliasing Tuner](https://addons.mozilla.org/en-US/firefox/addon/anti-aliasing-tuner) and `gfx.font_rendering.cleartype_params.rendering_mode` are useless, can't affect TextQuality.

**Comment by wolfbeast** [comment]
Please clarify exactly what the issue is. What do you mean with "overlay"?

>If Windows cleartype is on, gfx will use CLEARTYPE_QUALITY (sub pixel / true letter spacing)
If Windows cleartype is off, gfx will use ANTIALIASED_QUALITY (snap to pixel)

This is correct. You can't use cleartype when it's switched off in the system. If you use cleartype when it's switched off in the system, you have a pretty good chance that the quality will be much worse because cleartype has likely not been set up with proper parameters.

**Comment by zcyzcy88** [comment]
Overlay: Apply user-specified setting and ignore default setting
Provide an option that make gfx think ClearType is on.

> you have a pretty good chance that the quality will be much worse because cleartype has likely not been set up with proper parameters.

I bet it will not. I think this is the last step to get beautiful text-rendering in Windows.

**Comment by wolfbeast** [comment]
Ah you mean **override** okay.
Adding a pref to override what that function returns isn't too hard to do.

**Comment by Atavic** [comment]
Current rendering in PM on windows is perfect as it is, compared to other browsers IMHO
