### ISSUE TITLE
Was browser login managers exploit in Pale Moon or not?

### ISSUE THREAD

**Issue by Symbian9** [MoonchildProductions/Pale-Moon#1559]
Details on exploit:
> We tested the following browsers: Firefox, Chrome, Internet Explorer, Edge, Safari.
> - https://freedom-to-tinker.com/2017/12/27/no-boundaries-for-user-identities-web-trackers-exploit-browser-login-managers/

**Comment by wolfbeast** [comment]
This approach is only possible when a third party has script access to the first-party domain, since crossorigin access needs to be set explicitly. In the case of XSS, we have CSP to mitigate that.

It's easily avoided on insecure sites by setting `signon.autofillForms` to `false`, but the drawback of that is (obviously) that logging in to sites will require manual selection of the user name in that case, even if there is only one password saved.

**Comment by wolfbeast** [comment]
Probably the best solution here is to disable `autofillForms` by default, and add a control to the UI in Security to allow the user to easily enable it if/when they want it.

**Comment by wolfbeast** [comment]
@JustOff please note the added string and access key in this change.

**Comment by JustOff** [comment]
Strings changes were pushed to CrowdIn.
