### ISSUE TITLE
Microsoft Edge data import support

### ISSUE THREAD

**Issue by Lootyhoof** [MoonchildProductions/Pale-Moon#156]
With Microsoft Edge as the default browser on Windows 10, it would be useful if data could be imported from it into Pale Moon.

BMO (meta):

[1163644](https://bugzilla.mozilla.org/show_bug.cgi?id=1163644) - (edge-migration) Data importers/migrators for Microsoft Edge browser

**Comment by Axiomatic-** [comment]
In this [duplicate bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1191406), it makes it sound like Firefox detects Microsoft Edge, as Internet Explorer if that is the case for Pale Moon as well, then is not the fix as simple as adding, Internet Explorer / Microsoft Edge?

**Comment by Lootyhoof** [comment]
That is a bug with how Firefox detects Edge, not a solution. Edge stores its data in a separate location to IE, due to being a "modern" app (see discussion in meta).

**Comment by wolfbeast** [comment]
Importing data from other browsers is a moving target that is simply not possible to properly maintain for a small team like ours (requires reverse-engineering, lots of guess work and testing, etc.)
We won't be extending this, and will be removing importing from other browsers entirely due to unmaintainability by us.

Perhaps an import extension can be written by a contributor to fill in this gap if needed.
