### ISSUE TITLE
When hiding the tab bar, the border of the lowest toolbar is also hidden.

### ISSUE THREAD

**Issue by RobertZenz** [MoonchildProductions/Pale-Moon#1560]
When the tab bar is being hidden, the bottom border of the lowest toolbar is being hidden as well. This occurs on a Linux system (GTK2 frontend).

Here is a screenshot with tabs being visible:

![Palemoon with tabs visible.](https://i.imgur.com/6pN5Ebz.png)

Now when the option "Always show the tab bar" is unchecked, it will be hidden when there is only one tab. But the border between the toolbars and the content will disappear as well:

![Palemoon with no tabs visible.](https://i.imgur.com/dLp2Nyv.png)

This occurs no matter if tabs or on top or not, and with the bookmarks bar visible or not.

**Comment by Lootyhoof** [comment]
Confirmed. There actually appears to be a bit of hackery in place to get that border appearing at the moment, and I'm not quite sure why it differs from the Windows styling (which appears to work fine in testing).

I'll see what I can do.

**Comment by Lootyhoof** [comment]
Hmm...looking at this further, it seems this also happens on Windows (and presumably Mac). At the same time though, I'm not sure if there's a sane way of doing this without upsetting other things - it CAN be done, but would result in the tab backgrounds being changed, which would adversely affect extensions that move tabs off the pre-defined tab bar (as at the moment, when tabs are on bottom a _border_ isn't drawn - but rather a strategically-placed line that's both part of the tab bar's background and each tab's background). This is why there isn't a border there when the tab bar is removed. As for why there's a border when tabs are on top, this is because it doesn't affect tabs in any way - if that border were there when tabs are on bottom, there'd be a double line (since we definitely _do_ want a bottom "border" on the tabs). 

We also couldn't just say "draw a line when the tab bar isn't there", because the only indicator we have for that is `#TabsToolbar` itself has the `collapsed=true` property, and since it's the last element in `#navigator-toolbox` we can't even draw borders on adjacent toolbars based on its `collapsed` property (since the only way to do so is using `~`, which allows us to style the element directly _below_ the current one, e.g. `#PersonalToolbar[collapsed=true] ~ #TabsToolbar`).

This might be one to put `On Hold`, I guess. It's definitely an issue, but fixing it would break other things (unless I happen to think of some other way this can be done without being destructive).

**Comment by RobertZenz** [comment]
I can now confirm that this is also on Windows.

 > As for why there's a border when tabs are on top, this is because it doesn't affect tabs in any way - if that border were there when tabs are on bottom, there'd be a double line (since we definitely do want a bottom "border" on the tabs).

But how is the border drawn when the tabs are on top? The first step could be to make sure that that line stays even when the tabs are hidden. That would get us halfway there.

For tabs on bottom, I see, ain't got an idea right now, either.

**Comment by RobertZenz** [comment]
Maybe the line could be a another element which is toggled visible or not depending on what is going on?

 * Tabs on top, not collapsed: Visible
 * Tabs on top, collapsed: Visible
 * Tabs on bottom, not collapsed: Hidden
 * Tabs on bottom, collapsed: Visible

Something like that?

**Comment by Lootyhoof** [comment]
When the tab bar is hidden in this manner, `#TabsToolbar` is always `tabsontop=false`. In this mode, the border we would otherwise draw when tabs are on top (in some cases this is just a `border-bottom` of `#navigator-toolbox`, other times a `background` element of `#navigator-toolbox::after`) is hidden, as we're relying on the one provided by the tab bar background. As mentioned, for the elements that we'd need to style (ideally, `#navigator-toolbox`), it's not possible to know when this is, as the `collapsed` property is only on `#TabsToolbar`.

**Comment by RobertZenz** [comment]
Mh, I see, I guess.

The only thing that I could contribute further is that over at [ClassicThemeRestorer](https://github.com/Aris-t2/ClassicThemeRestorer) might be a solution (or at least the possibility there of). CTR provides a "Tabs on Bottom" functionality for Firefox v56- together with custom themes which do not suffer from that problem. So there might be something there. Unfortunately I'm quite unable to understand if that is the case.

**Comment by SpockMan02** [comment]
>if that border were there when tabs are on bottom, there'd be a double line (since we definitely do want a bottom "border" on the tabs).

Couldn't we put the line there without a double line by just removing the line in the tabs' backgrounds? Why do we definitely want a background on tabs that mimics a bottom "border?" If that would make tabs on top look weird (no bottom border), then just give the whole tabs toolbar a bottom border when tabs are on top.
It's entirely possible I'm just not understanding something, but these pseudo-borders on the tabs seem unnecessary and I don't see why we can't just always have a line under the bottommost toolbar and give the tabs toolbar a proper bottom border when tabsontop=true.

**Comment by RobertZenz** [comment]
> Why do we definitely want a background on tabs that mimics a bottom "border?

Certain themes (as in OS dependent theme) don't have a border underneath the active tab.

**Comment by SpockMan02** [comment]
>Certain themes (as in OS dependent theme) don't have a border underneath the active tab.

Right, because the metaphor is that the tab is a sticking-up part of the page... Okay, so what if in those themes the active tab was given a thicker bottom border, the same color as its background, to cover up the line underneath it and make it still seem connected to the page?

I did a similar thing with subreddit post-sorting tabs a while back.

**Comment by SpockMan02** [comment]
Would there be a problem with removing the background hackery, and then using
`#navigator-toolbox { border-bottom: 1px solid #7B7B7B; }`
`#TabsToolbar[tabsontop="true"] > .toolbarbutton-1,`
`.tabbrowser-tab { border-bottom: 1px solid #7B7B7B; }`, and for OS dependent themes that don't have a bottom border underneath the active tab,
`.tabbrowser-tab[selected="true"] { border-bottom: none !important; }`?

This should ensure that there's always a border at the bottom of the lowest toolbar to separate it from the page content, while also giving the tab bar (or rather, the things inside of it) a border, but excluding the active tab.

**Comment by Lorienna** [comment]
According to my tests on Win7x64, after the following change in FF 12, if a single tab was open, then upon hiding the tab bar the `Tabs on Top` context menu entry got inactive and greyed out, and the border disappeared both in the <q>tabs-on-bottom</q> and the <q>tabs-on-top</q> modes (as can be observed in PM now):


<table frame="below">
<tr>
<td align="center">Last good: <a href="https://hg.mozilla.org/mozilla-central/rev/5a446202be5f"><b>12.0a1</b></a> <a href="https://archive.mozilla.org/pub/firefox/nightly/2012/01/2012-01-07-03-10-40-mozilla-central/">(2012-01-07, 03:10:40)</a></td>
<td align="center"><a href="https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=5a446202be5f&tochange=1a4ef8ec3f5a">Pushlog</a></td>
<td align="center">First bad: <a href="https://hg.mozilla.org/integration/mozilla-inbound/rev/1a4ef8ec3f5a"><b>12.0a1</b></a> <a href="https://archive.mozilla.org/pub/firefox/nightly/2012/01/2012-01-07-04-02-21-mozilla-inbound/">(2012-01-07, 04:02:21)</a></td>
</tr>
<tr>
<td colspan="3"><a href="https://bugzilla.mozilla.org/show_bug.cgi?id=618770">Bug 618770</a> - Titlebar gradient breaks off abruptly at the toolbar in windows without tab bar when tabs are set on top</td>
</tr>
<tr></tr>
<tr>
<td colspan="3"><a href="https://hg.mozilla.org/mozilla-central/rev/440b585a2896">Changeset 83998</a> - Use tabs-on-bottom layout when the tab bar is hidden. r=dolske</td>
</tr>
</table>


<br>Prior to the change above, if the tab bar was hidden, and a single tab was open, the border was missing only in the <q>tabs-on-__bottom__</q> mode, and present in the <q>tabs-on-__top__</q> mode:


<table frame="below">
<tr>
<td align="center">Last good: <a href="https://hg.mozilla.org/mozilla-central/rev/fd0817e454fe"><b>4.0b12pre</b></a> <a href="https://archive.mozilla.org/pub/firefox/nightly/2011/02/2011-02-09-03-mozilla-central/">(2011-02-09)</a></td>
<td align="center"><a href="https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=fd0817e454fe&tochange=199cb6282554">Pushlog</a></td>
<td align="center">First bad: <a href="https://hg.mozilla.org/mozilla-central/rev/199cb6282554"><b>4.0b12pre</b></a> <a href="https://archive.mozilla.org/pub/firefox/nightly/2011/02/2011-02-10-03-mozilla-central/">(2011-02-10)</a></td>
</tr>
<tr>
<td colspan="3"><a href="https://bugzilla.mozilla.org/show_bug.cgi?id=631698">Bug 631698</a> - 1px border visible below active app tabs when there is tab overflow (using Aero Glass with DirectWrite disabled)</td>
</tr>
<tr></tr>
<tr>
<td colspan="3"><a href="https://hg.mozilla.org/mozilla-central/rev/f2a249b46e43">Changeset 62283</a> - remove bogus 1px border below active app tabs (w/ tab overflow, Aero Glass, no DirectWrite). r=fryn a=dolske</td>
</tr>
</table>

**Comment by RobertZenz** [comment]
Why the closing? Has this been obsoleted with the migration to UXP or something?

**Comment by wolfbeast** [comment]
If this is still an issue on the unstable channel Pale moon based on UXP, please open a new issue on the UXP repo.

**Comment by RobertZenz** [comment]
Ah, okay, will check that.
