### ISSUE TITLE
IP leak via WebRTC

### ISSUE THREAD

**Issue by Ud71p** [MoonchildProductions/Pale-Moon#1573]
I often use Tor or VPN. My IP address should be hidden from websites. But with WebRTC it leaks.

Step to reproduce:

Go to 'https://check.torproject.org/'.
Observe " Congratulations. This browser is configured to use Tor. Your IP address appears to be: *not-my-IP*".
Go to 'about:config'.
Verify that media.peerconnection.enabled = true.
Go to 'https://diafygi.github.io/webrtc-ips/'.
Observe the problem: "Your public IP addresses: *my-real-leaked-IP*".

They can see my real IP address.

The issue is well-known, described here:
https://en.wikipedia.org/wiki/WebRTC#Concerns
And in linked article:
https://torrentfreak.com/huge-security-flaw-leaks-vpn-users-real-ip-addresses-150130/

Version: 27.6.2 (64-bit)

As a work-around, compile PaleMoon without WebRTC, or set media.peerconnection.enabled = false.

**Comment by mattatobin** [comment]
Pale Moon does not compile WebRTC as it is.. In fact.. I am not even sure it builds currently..

So, do you even know anything about our project?

**Comment by Ud71p** [comment]
Yes, PalMoon has (optional) WebRTC support.

Yes, it does compile with --enable-webrtc, I tried myself.

There are even packages for distros making the webrtc flag available for users to flip in package manager UI, see here the packages have the webrtc flag (minus '-' means disabled by default, bug can be turned on by users):
https://gpo.zugaina.org/www-client/palemoon

So, do YOU even know anything about your project?

I opened new issue with more info:
https://github.com/MoonchildProductions/Pale-Moon/issues/1579

**Comment by mattatobin** [comment]
Just because it is in the codebase doesn't mean it should be used. Official configuration does NOT include it. If this option is being exposed to source based distros.. That needs to stop as the code is NOT maintained in the Tycho (Pale Moon 27) codebase and hasn't been a thing that Pale Moon has included for years.

IF there are binary builds out there with webrtc they are in violation of the terms regarding redistribution with offical branding.

Yes, I do know this project and I also know in no circumstance is webrtc enabled Pale Moon no matter if the code builds or not webrtc is unmaintained and building it is NOT ALLOWED.

**Comment by mattatobin** [comment]
But if it requires a patch to the build system to make it explicit.. Guess I will have to make one, eh?

**Comment by wolfbeast** [comment]
official branding + webrtc -> throw error.
