### ISSUE TITLE
IP leak via WebRTC when built with --enable-webrtc

### ISSUE THREAD

**Issue by Ud71p** [MoonchildProductions/Pale-Moon#1579]
PaleMoon has optional WebRTC support, see:
https://github.com/MoonchildProductions/Pale-Moon/commit/d4a4492c6588116d4888510cbb2e1db9ab077a24

I built PaleMoon with --enable-webrtc, because I need it for work.

I often use Tor or VPN. My IP address should be hidden from websites. But with WebRTC it leaks.

Step to reproduce:

Go to 'https://check.torproject.org/'.
Observe " Congratulations. This browser is configured to use Tor. Your IP address appears to be: not-my-IP".
Go to 'about:config'.
Set media.peerconnection.enabled = true.
Go to 'https://diafygi.github.io/webrtc-ips/'.
Observe the problem: "Your public IP addresses: my-real-leaked-IP", that is they can see my real IP address.

The issue is well-known, described here:
https://en.wikipedia.org/wiki/WebRTC#Concerns
And in linked article:
https://torrentfreak.com/huge-security-flaw-leaks-vpn-users-real-ip-addresses-150130/

Version: 27.6.2 (64-bit)

As a work-around, set media.peerconnection.enabled = false.

**Comment by wolfbeast** [comment]
We don't ship Pale Moon with WebRTC. It is well-known that WebRTC exposes the IP through peer connections (because that is by design).

Not sure what you think this issue is supposed to address other than providing information for people using non-standard builds, but it's neither actionable nor in the right place in this issue tracker.
