### ISSUE TITLE
Add support for Array.prototype[@@unscopables] properties

### ISSUE THREAD

**Issue by janekptacijarabaci** [MoonchildProductions/Pale-Moon#1587]
Ad https://forum.palemoon.org/viewtopic.php?f=29&t=18017

Throws an error in Browser Console:
```
TypeError: Array.prototype[X.unscopables] is undefined
```

Follow up / Improvements #1562

---

https://tc39.github.io/ecma262/#sec-array.prototype-@@unscopables

>22.1.3.32Array.prototype [ @@unscopables ]
>
>The initial value of the @@unscopables data property is an object created by the following steps:
>
>    Let unscopableList be ObjectCreate(null).
>    Perform CreateDataProperty(unscopableList, "copyWithin", true).
>    Perform CreateDataProperty(unscopableList, "entries", true).
>    Perform CreateDataProperty(unscopableList, "fill", true).
>    Perform CreateDataProperty(unscopableList, "find", true).
>    Perform CreateDataProperty(unscopableList, "findIndex", true).
>    Perform CreateDataProperty(unscopableList, "includes", true).
>    Perform CreateDataProperty(unscopableList, "keys", true).
>    Perform CreateDataProperty(unscopableList, "values", true).
>    Assert: Each of the above calls will return true.
>    Return unscopableList. 
>
>This property has the attributes { [[Writable]]: false, [[Enumerable]]: false, [[Configurable]]: true }.
>
>Note
> The own property names of this object are property names that were not included as standard properties of Array.prototype prior to the ECMAScript 2015 specification. These names are ignored for with statement binding purposes in order to preserve the behaviour of existing code that might use one of these names as a binding in an outer scope that is shadowed by a with statement whose binding object is an Array object.

---

An example:
``` javascript
var keys = [];
with (Array.prototype) {
  keys.push('something');
}
alert(Object.keys(Array.prototype[Symbol.unscopables])); 
// ["copyWithin", "entries", "fill", "find", "findIndex", 
//  "includes", "keys", "values"]
```

Actual results:
```
Exception: TypeError: keys.push is not a function
```

Expected results:
```
alert("copyWithin,entries,fill,find,findIndex,includes,keys,values");
```

Bug(s):
https://bugzilla.mozilla.org/show_bug.cgi?id=1258163

It is important to use the correct argument (parent) for `NewObjectWithGivenProto`:
https://bugzilla.mozilla.org/show_bug.cgi?id=1142296
(e.g. `NewObjectWithGivenProto<PlainObject>(cx, NullPtr(), NullPtr(), TenuredObject)`)

**Comment by wolfbeast** [comment]
Looks like the partial implementation of unscopables causes more issues than not having them altogether (not so strange). This is quite unfortunate.
Are you working on this? If not, I'll probably temporarily back out the unscopables base implementation until the feature can be implemented in full.

**Comment by wolfbeast** [comment]
Since I don't see any commits on your branch I'm assuming you're not working on this -- I'm backing out the base implementation and will assign it to myself to implement.

**Comment by janekptacijarabaci** [comment]
> Are you working on this?

No, I'm just testing it:
https://github.com/janekptacijarabaci/Pale-Moon/tree/_testBranch_js_array_unscopables_1

I will not continue to do so.

> Please do some more research next time for new features. Everyone fucks up now and then but this is becoming rather bothersome.

These bugs are not linked (directly). ES6/ES2015... A lot of it is related only 

indirectly.

Why didn't someone else notice it?

I will do it less and less often (I feel like it's always up to me - which is also very "fun")... It will be good for both sides.

**Comment by wolfbeast** [comment]
Look, doing research to gather up all bugs (whether they are linked or not) and seeing when they were implemented is a big part of porting code. You can't just do a 1-2 step going from "website is broken" - "search bugzilla for the error" "port code from whatever bug comes up in search" and expecting to be done, especially when it's about new JS features.

Someone else doesn't notice it because we are not here to check your research like a teacher; it would cost us just as much time and effort to do that as it would to implement it ourselves.

Also, nobody asks you to jump in and do this. It's only up to you because you rush in and find the bugs and pump out a PR usually before I've even had a time to properly look at it. And considering your definitive actions I must assume you've done the entire run of solving the issue (in full).
If that's not how you want to work, then please let me know. I won't merge anything from your hand without a thorough review in that case; but don't be surprised it takes a while or too impatient and removing the code. It's not very efficient that way but at least we won't have half-done work that causes issues for our users.

**Comment by janekptacijarabaci** [comment]
> in full

...and it may always be different.
= `I will do it less and less often... It will be good for both sides.`

> it would cost us just as much time and effort to do that as it would to implement it ourselves

...and this is the best choice.

> If that's not how you want to work, then please let me know. I won't merge anything from your hand without a thorough review in that case

If that happens, yes.

> but don't be surprised it takes a while or too impatient and removing the code

I don't do it this way... e.g. #1270

**Comment by wolfbeast** [comment]
OK, if that is your attitude, then please stop contributing code to the browser core.

We have to be able to have a solid foundation to work from, and that's obviously not something you want to do. The Mozilla code is clearly more complex than you are willing to put effort towards and I don't want to deal with more half-done things that I have to pick up the pieces for.

I appreciate all the time and effort you have put in so far, and thank you very much for contributing, but it's probably better if you focus on simpler things that can be solved with a single straight shot solution. Maybe you can continue to help out (if you want) in the area of extensions or toolkit components, but please don't contribute any more code changes to core parts of the browser like JS, DOM, the parser, layout, rendering or XPCOM.

**Comment by janekptacijarabaci** [comment]
> don't contribute any more code changes to core parts of the browser like JS, DOM, the parser, layout, rendering or XPCOM

I think that is a reasonable solution. In this case, I will create an issue, and/or I add a comment (i.e. in the forum) or a suggestion (i.e. in a(n) issue and PR from someone else). Non-binding things, simply.

Thank you for your cooperation (PM, i.e. UXP/Basilisk).

**Comment by mattatobin** [comment]
I will say this. When it comes to devtools you have been a superstar.. But you just need to be realistic when it comes to other bits of the codebase.

There is a reason I stay away from cpp and javascript whenever possible. A lot of it is beyond me in how this stuff was is will be done in a mozilla style. So I stick to build system-y things and preprocesser-y things and general oversight-y things and coordination of things and server administration-y things because I am more confident in those areas. Like being a pain in the ass to everyone about doing things properly. The guy who trys to keep the entire big picture of everything in his head and try to speak to the past, present, and future.

It is my nitch in the project. Travis has linux and media, Ryan has themes, etc. We all dabble in everything but are more valuable for our more targeted skills in our areas that others may not be. Doesn't mean we can't expand our capabilities but it also means each of us must be spectacular at everything either..

It just means that we must be extra careful when it comes to things that we may not know like the back of our hands. This is why asking questions and help are essential and being reasonably detailed is important.

It is one thing to be in your element and plastering a "what it says on the tin" and another to try to do something out of your primary skillset that you have doubts about.

I hope you take this to heart and learn rather than simply give up because you have had some difficulties as of late.

**Comment by mattatobin** [comment]
Also, never ever EVER trust Mozilla wholesale. ;)

**Comment by janekptacijarabaci** [comment]
I did not give up... Only... I am announcing the release of positions, but at the moment I was completely smiling :-)

**Comment by wolfbeast** [comment]
@janekptacijarabaci -- I do hope you realise I need to make a chemspill release for this. Certain frameworks in wide use break with the half-implementation. I'm not happy about that.

**Comment by janekptacijarabaci** [comment]
@wolfbeast 
It was not that kind of smile... that it caused problems. I'm sorry about that - that my PR was not perfect.
However it will only be better now... when I'm out of this "place of the core".

**Comment by mattatobin** [comment]
I'm not sure I know what that means but I hope it isn't passive aggressiveness cause that would be unfortunate.

**Comment by janekptacijarabaci** [comment]
@mattatobin 
It's the exact opposite.
IMHO: PM this is based on developers with more experience and now it's coming back though some people are making efforts. I think it's good now - until other developers start noticing your work and maybe join you for developing if you will want.
And the first paragraph was sincere :neutral_face: I never wanted to cause problems (however, there is no uniform procedure - everything that needs to be checked to make sure it's good to go - and this is the best way).

**Comment by mattatobin** [comment]
Good and I totally agree. I think the future just got a little better. Thank you for that.
