### ISSUE TITLE
Browser crash when visiting the link (reproducible)

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/Pale-Moon#1622]
As reported on forum [here](https://forum.palemoon.org/viewtopic.php?f=12&t=18437), visiting `https://mee6.xyz/levels/243407864411062272` causes a crash. 
Verified in both 27.7.2 and unstable x86 @ Win7x64.

**Comment by wolfbeast** [comment]
Okay. It's a safe crash in JS. The strange thing is that the page script somehow manages to enter the arithmetic system with a NOP operation... Since that's undefined, it falls through to a `MOZ_CRASH`.

**Comment by JustOff** [comment]
In case this can help, there is no crash here in 27.6.0 and below.

**Comment by wolfbeast** [comment]
So, last good = 27.6.0, first bad = 27.7.0?

**Comment by JustOff** [comment]
More precisely, last good = 27.6.2, first bad = 27.7.0.

**Comment by wolfbeast** [comment]
Okay, thanks.

**Comment by wolfbeast** [comment]
Regression from #1523 -- well in so much as that prior to that, the site's calculations don't work, but don't crash either ;)

**Comment by wolfbeast** [comment]
Looks like there's an issue with the Baseline JIT code not passing the correct op_ down to `BinaryArith()`. This gets hit on the URL in question because the calculation is used in a loop and therefore triggers JIT on a hot path.

Since we're likely not going to hit hot paths very often with this exponentiation, it's OK to disable JIT for it. Firefox likely has the same problem but avoids the crash because it is handed off to IonMonkey instead of baseline in that case.
