### ISSUE TITLE
Error when load folder fshare.vn

### ISSUE THREAD

**Issue by meav** [MoonchildProductions/Pale-Moon#1623]
Example this link

https://www.fshare.vn/folder/MOA4HS8GC5BW

In Palemoon

https://farm5.staticflickr.com/4654/39819981654_e7c2330830_b.jpg

In Googlechrome

https://farm5.staticflickr.com/4605/39819981494_05efb85834_b.jpg

I hope you will fix this.

Sorry for my bad english!

**Comment by wolfbeast** [comment]
Syntax errors on the page are not our bug:
```
07:44:39.023 SyntaxError: expected expression, got ')'1 FileListAction.js:246:12
07:44:39.024 SyntaxError: expected expression, got ')'1 folder.js:356:8
```
Their script is bodged:
```JavaScript
        $http.get(url, {
            params: ctrl.next == '' ? params : null
        }).then(
            function successCallback(response) {
                [...]
            }.bind(this),
            function errorCallback(err) {
                [...]
            }.bind(this),
        );
    }
```
Notice the comma after the last `.bind(this)`? that's a syntax error because you can't have a comma right before a closure. This same error is in both scripts. Chrome probably accepts this as a quirk in their sloppy mode (it shouldn't but eh, sloppy mode is a wild west).

**Comment by meav** [comment]
I'm sorry
Is there any way to load list file by Palemoon

**Comment by wolfbeast** [comment]
Contact fshare.vn and have them fix their scripting.
