### ISSUE TITLE
Page elements missing on https://ipleak.net/

### ISSUE THREAD

**Issue by Sa-Ja-Di** [MoonchildProductions/Pale-Moon#1639]
There are quite some elements missing on the page which are shown for example in Chromium but not on Pale Moon.

Error messages from the web console:

1) SyntaxError: expected expression, got ')' index.js:129:12

2) ReferenceError: IpLeak is not defined

Url is: https://ipleak.net/

Was reported by a user over IRC

**Comment by janekptacijarabaci** [comment]
IMHO, this problem is: Trailing commas in arguments (draft ECMAScript 2017/2019):
http://web.archive.org/web/20160902171844/http://jeffmo.github.io/es-trailing-function-commas/
Also: [bug 1303788](https://bugzilla.mozilla.org/show_bug.cgi?id=1303788)

**Comment by wolfbeast** [comment]
what a bullshit spec.

**Comment by mattatobin** [comment]
Solved by UXP?

**Comment by adeshkp** [comment]
As if code attribution is such a big problem.
JavaScript is becoming a shitpile borrowing unnecessary features from other languages.

**Comment by wolfbeast** [comment]
it's just all sorts of backwards. This is adjusting programming language grammar to cater to completely unrelated versioning system practices? It's total BS. If people find they want their precious blame logs pristine then should change the way they code, and put their bleedin' commas at the start of the line instead of at the end.

```
function a( arg1
 ,arg2
 ,arg3
)
