### ISSUE TITLE
Palemoon always scales raster images

### ISSUE THREAD

**Issue by l29ah** [MoonchildProductions/Pale-Moon#1671]
Say, when i open https://dump.bitcheese.net/files/afytywa/screenshot-workspaces-2010-06-29.png, i observe it upscaling my screenshot horribly:

![screenshot](https://a.pomfe.co/qghsaf.png)

While i expected it to be shown pixel-to-pixel, like firefox does.

27.9.0 here.

**Comment by wolfbeast** [comment]
The image shows scaled down by default, and when clicking the zoom icon on it, it will display 1:1

I don't see anything wrong with the way images are displayed, here.

**Comment by l29ah** [comment]
It is upscaled in my screenshot. You can clearly see the image pixels bigger than a pixel.

**Comment by l29ah** [comment]
In firefox:

![ff](https://pomf.space/xuP9BjR.png)

**Comment by wolfbeast** [comment]
Maybe I wasn't clear. I tested this image and it works as it should, giving the behavior I stated in my previous comment. Are you using any extensions that manipulate zoom levels?

**Comment by l29ah** [comment]
No, i observe it in --safe-mode as well.

**Comment by l29ah** [comment]
Also it may be palemoon reacting to me moving to a high dpi display, since i don't recall seeing such behaviour previously.

**Comment by wolfbeast** [comment]
In that case it's expected. If your device pixels are no longer equal to css pixels, then all images will be scaled accordingly -- by design. If that wouldn't be done, you'd create a discrepancy.
If I look at your Firefox screenshot, that isn't scaled (the UI elements are much smaller) so likely you've set `layout.css.devPixelsPerPx` in Firefox to `1.0` instead of `-1.0` (=auto)

**Comment by l29ah** [comment]
It's strange i haven't noticed it on my previous display (that had about 125ppi, unlike the current 178) then.
Nope, `layout.css.devPixelsPerPx` in firefox is the default `-1.0`, just like in palemoon.

**Comment by l29ah** [comment]
By the way, is there a way to set devPixelsPerPx per site?

**Comment by wolfbeast** [comment]
Zoom levels are stored per-site. Device pixels per pixel is a global setting because it scales *everything* to the DPI/scale indicated.
I'm not sure why your Firefox doesn't display the same behavior with a setting of -1.0; it should have the same behavior as Pale Moon at larger DPI settings.

Either way, as far as I can tell Pale Moon is doing exactly what it should be doing, by design, for higher system DPI settings.
