### ISSUE TITLE
Support Angular

### ISSUE THREAD

**Issue by karptonite** [MoonchildProductions/Pale-Moon#1689]
Pale Moon almost supports the Angular framework (or vice versa), but not quite.

According to the Pale Moon forums, users of Pale Moon can get Angular pages to load by changing the browser settings to [force javascript to strict mode](https://forum.palemoon.org/viewtopic.php?t=18192).

It seems that, with the browser and the framework so close to compatible, it would be beneficial to users of both for one project or the other to make whatever changes are necessary to make Angular pages work. I ran into this issue when we launched a redesign of a part of our site, and got complaints from Pale Moon users. While I was able to direct them to instructions to change their browser setting to make the site work, this is obviously not the ideal solution.

I have no idea which project, if any, is in error here, so I've filed an issue on Angular as well: https://github.com/angular/angular/issues/25046. I hope that a solution to this problem is possible.

**Comment by wolfbeast** [comment]
Thanks for getting in touch.
The fact that forcing strict mode fixes it suggests there is a problem with Angular's browser detection mode making assumptions about specific features available based on a limited number of tests (their JS shims may need work).

That being said, with the upcoming new milestone for Pale Moon (v28, planned next month) this should be a thing of the past (unless Angular decides to shim new shinies beyond ES6 and ES7 and not detecting properly again) because of the JS standards progress we've made in it, which will sidestep Angular's problems.

**Comment by karptonite** [comment]
Glad to hear the new version should work with Angular.
