### ISSUE TITLE
Branding Related Questions

### ISSUE THREAD

**Issue by FlyGoat** [MoonchildProductions/Pale-Moon#1805]
I was trying to send an email to <licensing@palemoon.org> but got rejected....

```
<licensing@palemoon.org>: host vmx.palemoon.org[80.255.0.190] said: 550 5.1.1
    Recipient unknown <licensing@palemoon.org> (in reply to RCPT TO command)
```

As you may know, I'm working on a MIPS port of Pale Moon browser. I'll submit most sean changes to the upstream but there are some dirty hacks & optimization that can never be submitted to the upstream, also I'm targeting Chinese users thus there might be some localization works that violate "sean" build config. So I decided to make a fork of Pale Moon focusing on experience on MIPS/[Loongson](https://en.wikipedia.org/wiki/Loongson) systems.

Before that, I'd like to confirm some details about licensing.

- Will redistribution of source tarball violate branding policy? For sure I'll replace the brand and icons in the source, but there are lots of code, even file names include PaleMoon string, should I replace all of them too?

- Will files in Git history violate branding policy? As a fork, I'd like to preserve git log to make tracking easier. But that may include PaleMoon's icon etc, is it sean to do so?

- Will announce my fork as "A fork of PaleMoon" violate branding policy? To credit your works, I'd like to add "A fork of PaleMoon" in the program's description and about page of the final binary.

Can I still use PaleMoon's sync server in my fork?

Thanks a lot! And really appreciate your works!

**Comment by wolfbeast** [comment]
The correct e-mail address for licensing, branding and other legal matters should be "legal{at}palemoon.org". I thought this was changed properly everywhere but perhaps I missed a location? Where did you get the address from?

Redistribution of the source tarball and git history will not violate the branding policy, as you are not using the included branding in a final product _as_ branding. You aren't granted any rights for **use** of the included branding materials (e.g. logo, wordmark, etc.), but that does not prevent redistribution of them as part of the source. We do request that you make sure the end product doesn't refer to itself as Pale Moon (meaning ensure &brandShortName; and &brandFullName; are properly re-branded) but other occurrences of the Pale Moon string in code do not need to be changed.

Crediting is always fine, since you are simply referring to Pale Moon as the browser, not claiming it as your own! See also http://www.palemoon.org/branding.shtml

Just, please do at all times **use the proper spelling**: "Pale Moon" 2 words, capitalized.

**Comment by FlyGoat** [comment]
> 
> 
> The correct e-mail address for licensing, branding and other legal matters should be "legal{at}palemoon.org". I thought this was changed properly everywhere but perhaps I missed a location? Where did you get the address from?

From here: https://www.palemoon.org/redist.shtml the "contact me" link.

> 
> Redistribution of the source tarball and git history will not violate the branding policy, as you are not using the included branding in a final product _as_ branding. You aren't granted any rights for **use** of the included branding materials (e.g. logo, wordmark, etc.), but that does not prevent redistribution of them as part of the source. We do request that you make sure the end product doesn't refer to itself as Pale Moon (meaning ensure at least `&brandShortName;` and `&brandFullName;` are properly re-branded, and your about box does not use the official artwork and the likes) but other occurrences of the Pale Moon string in code do not need to be changed.
> 
> Crediting is always fine, since you are simply referring to Pale Moon as the browser, not claiming it as your own! See also http://www.palemoon.org/branding.shtml
> 
> Just, please do at all times **use the proper spelling**: "Pale Moon" 2 words, capitalized.

Thanks a lot! Will do.

> 
> Your use of Sync will depend on the expected volume of users! Please discuss details via e-mail or on the forum.

**Comment by wolfbeast** [comment]
> the "contact me" link.

Ah.. Thanks, i'll fix that forthwith
