### ISSUE TITLE
Port Pale Moon to Haiku

### ISSUE THREAD

**Issue by extrowerk** [MoonchildProductions/Pale-Moon#1807]
Haiku is an emerging alternative operating system and the users at the Haiku forum expressed their wish to have PaleMoon available for Haiku.
Because you - the PaleMoon developers - have the most experience with the codebase, please consider to support your users on Haiku too.
The Haiku developers and the HaikuPorts team can give you some assistance to bridge the platform differences.
As Haiku have no X11 server and not planned to have it, the GUI will need more work than on Linux-like platforms, where X11 is available.
Thank you!

**Comment by wolfbeast** [comment]
@trav90 is having no X11 a viable environment for the platform or not?

**Comment by g4jc** [comment]
I don't think X11 is the major blocker as long as it is able to run gtk2 or equivalent on their display server called `app_server`, which seems to be the case. UXP also runs on `Xenocara` without issue, which is a modified version of X11 from *BSD.

The problem I had when I attempted to build on Haiku a year or so ago is that they have a busted Python2 configuration that isn't capable of running `mach` since the python interpreter itself was crashing.

The original [2009 port](https://github.com/haikuports/haikuports/tree/master/www-client/bezilla) appears to have involved running `./configure` directly. If that has improved it _may_ be possible to have another look at this.

Obviously someone from the Haiku community should step up to offer build support in order to maintain it. BeOS removal was done [over 8 years ago](https://bugzilla.mozilla.org/show_bug.cgi?id=808399) so I'm sure there's many if define scenarios that have changed since then.

**Comment by wolfbeast** [comment]
What does BeOS have to do with this?

**Comment by g4jc** [comment]
[Haiku](https://en.wikipedia.org/wiki/Haiku_(operating_system)) is essentially a fork of BeOS and shares similar code and [API](https://en.wikipedia.org/wiki/Haiku_Device_Kit). The [patch for Haiku](https://github.com/haikuports/haikuports/blob/master/www-client/bezilla/patches/bezilla-2.0.0.22.patchset) included in the 2009 port essentially just uncomments some stuff and added Haiku to the list of BeOS defines. Ref: `XP_BEOS`. Most of the locations for that have since been removed.
