### ISSUE TITLE
Problems with Github

### ISSUE THREAD

**Issue by FakelsHub** [MoonchildProductions/Pale-Moon#1847]
Why does PaleMoon have constant problems with GitHub?
Do you know about this?

**Comment by wolfbeast** [comment]
Pretty sure it's because Microsoft moved edge to Chromium, and so they are constantly "improving" it to make use of the latest shinies in that engine. But please, go to the forum if you want to discuss such matters.

**Comment by wolfbeast** [comment]
Oh, I see, I'm guessing it's because they broke the "labels" yet again.

**Comment by FakelsHub** [comment]
I certainly don't understand what you have for labels that always broken.)))
Maybe you should get rid of these labels in the browser, so that it always works like other browsers?)

**Comment by wolfbeast** [comment]
I meant labels on Github.
But looks like any "popup" menu isn't populating again. This has happened before. It's usually because Github development tends to break their fallback paths for new shinies every time they want to make a visual change to the web UI that's currently only properly tested in Chrome and the Chromium-based version of Edge. 

What i don't understand is why they can't just leave something that works and has been stable for years (the github core functionality) alone. 
My most recent communication with Github support has also been very discouraging in that they are apparently no longer interested in having broad browser support but would rather follow unilaterally-defined features. This used to be different.
Officially, "Github doesn't support Pale Moon" and they have no intention of supporting any UXP browser, so if it keeps breaking, then there's little we can do at this point aside from reporting to them.

Of note, we can't even troubleshoot any of this because console errors are silenced. They will either see it in their log and fix it, or they won't.

**Comment by wolfbeast** [comment]
@JustOff was kind enough to construct a workaround for GitHub's use of WebComponents with an installable extension on Pale Moon.
https://github.com/JustOff/github-wc-polyfill
