### ISSUE TITLE
Non-standard license states cannot create fork with same name

### ISSUE THREAD

**Issue by hughperkins** [MoonchildProductions/Pale-Moon#188]
Non-standard license states cannot create fork with same name

This is unusual, non-standard, and discourages innovation.

**Comment by wolfbeast** [comment]
Protecting one's trademark is not non-standard.

If you make a fork, which would by its nature of being a fork  be materially different from the original product, you have the freedom to brand it whichever name you wish.

In what way would protecting one's quality of product this way discourage innovation? Because that completely escapes me.

**Comment by hughperkins** [comment]
You've *trademarked* an opensource project?  Other than Firefox, and Truecrypt, do you see many opensource projects with trademarks on them?

**Comment by wolfbeast** [comment]
:laughing: Yes, as a matter of fact, I do see many. Want me to name a few? Python, Qt, Sendmail, OpenOffice, OpenSuse, OpenWrt, MinGW, Linux, KDE, Gnome, ImageMagick, VNC, Ubuntu, Wireshark, ... I can go on.

**Comment by hughperkins** [comment]
Interesting, that's new information.  I was very surprised to see Python, sendmail, and mingw in that list.  Openoffice, qt, opensuse, ubuntu, less surprised, since they're clearly sponsored/commercial projects, often with a dual-license clause (eg qt).

In the case of Python, here is their documentation about their Trademark usage: https://www.python.org/psf/trademarks/  It is quite broad.  One is basically free to name one's product eg wxPython, IronPython etc, as long as it is freely available.  I may have misinterpreted, but this sounds somewhat looser than my current interpretation of your own trademark usage guidelines?

- "Use of the word "Python" in the names of freely distributed products like IronPython, wxPython, Python Extensions, etc. -- Allowed when referring to use with or suitability for the Python programming language. For commercial products, contact the PSF for permission.
- "Use of the word "Python" when redistributing the Python programming language as part of a freely distributed application -- Allowed. If the standard version of the Python programming language is modified, this should be clearly indicated. For commercial distributions, contact the PSF for permission if your use is not covered by the nominative use rules described in the section "Uses that Never Require Approval" above.
"

**Comment by wolfbeast** [comment]
Python is a programming language, and can expect products made with it to carry a similar name. It's just an example, anyway.

If you want to discuss this kind of thing, this issue tracker is the wrong place. Please go to the forum http://forum.palemoon.org/
Bottom line is that it's neither non-standard, nor unusual; and in the end I decide the degree of freedom as regards my trademark. What peers of other projects do ultimately has no bearing on this.
Since you also keep avoiding my question about your assertion about how this would discourage innovation, I think we're done here.
