### ISSUE TITLE
A question regarding distribution of Pale Moon binaries on NixOS.

### ISSUE THREAD

**Issue by Axiomatic-** [MoonchildProductions/Pale-Moon#192]
So I created a way for NixOS users to install Pale Moon from @trav90 packaged Linux builds. However because of how NixOS is a functional Linux distribution certain things need to be modified to the binary. The modification is done with the patchelf command, which changes the ELF interpreter, RPATH, etc. See: [pale-moon-bin.nix](https://github.com/Axiomatic-/Pale-Moon-Nix/blob/NixOS-binary/pale-moon-bin.nix)

However the redistribution license says, "the binaries and/or archives are completely UNALTERED." As well as in issue #166 which says, "when official binaries are used (in re-packaged form but otherwise unaltered)."

Not sure apply the patchelf command constitutes as re-packages, so I ask if I try to get this package into the Nixpkg tree (somewhat equivalent to the Arch Linux AUR) am I violating any terms or does the modification of the binary since necessary to get Pale Moon running on NixOS is allowed?

/cc @wolfbeast

**Comment by wolfbeast** [comment]
I'd say binary patching goes beyond repackaging, so no, this wouldn't fall under point 3.

However, if you're going to want to make this part of the package tree for NixOS then it would fall under point 8, although you're not building from source in this case it would still be considered a different "build" since it's different at a binary level:

8. An exception applies to point 5 of this license for inclusion of the officially branded binaries in freely available and fully Open Source operating systems, including but not limited to non-commercial variants of Linux, variants of BSD and ReactOS. This exception only applies to unaltered versions of the Pale Moon binaries or officially branded variants specifically built for the target operating system from source that have not been materially changed (including brand-specific configurations like e.g. home page, default search engine). If any of the essential settings of the browser are altered beyond what is strictly needed for providing a working build on the target operating system, the exception in this point does not apply and the license defaults to point 10, instead.

a. Clarification of "officially branded variants specifically built for the target operating system": If an officially-built binary (i.e. built by our team) is available for the target operating system (e.g. existing Linux binaries), then those binaries will always, in principle, take precedence over a third-party build to ensure necessary QA and compatibility. Building and distributing a binary with official branding is in that situation only **in principle allowed if an actual variant build is required for the target distribution's compatibility (e.g. kernel or library requirements) or operation, and otherwise not impacting the material content of the browser package as a whole.** QA of and support for the resulting variant binaries will in that case fall on the maintainer who will have to take full responsibility for the variant binary.

**Comment by Axiomatic-** [comment]
All right, thank you for the clarification.
