### ISSUE TITLE
Stop using deprecated libgnome and libgnomeui.

### ISSUE THREAD

**Issue by Axiomatic-** [MoonchildProductions/Pale-Moon#193]
This issue, has a Mozilla bug number. See [bug 694570](https://bugzilla.mozilla.org/show_bug.cgi?id=694570).

From what I can tell the patch has not made it into any builds provided from Mozilla. Seeing that you can run Pale Moon, and Firefox without actually having libgnome and libgnomeui installed promotes the idea that they should be removed as dependencies.

This is not a [GTK3 issue](https://github.com/MoonchildProductions/Pale-Moon/blob/master/toolkit/xre/nsNativeAppSupportUnix.cpp#L516), rather it is more of a stop using dead dependencies issue. So this possibly this falls under code clean-up? 

I can attempt to port the patch; however, I am unsure whether the patch should be developed further before being merged into Pale Moon or is fine as is. Anyone have any comments?

**Comment by trav90** [comment]
I took a quick look and it seems like Mozilla is for removing these dependencies, but has not implemented the patch yet because some problems have yet to be resolved. Bug 557601 is specifically mentioned, along with a couple other problems (see the last couple comments). It also looks like if the patch as-is is ported to PM, Mozilla refactoring will have to be accounted for.

**Comment by wolfbeast** [comment]
Oh the joys of async calls.

**Comment by Axiomatic-** [comment]
Just a thought, but would not using D-Bus be a more elegant method to do what the patch attempts? What confuses me is that the bug says D-Bus is GNOME only, however through a quick use of a search engine, I found documentation of D-Bus in many desktop environments (for example, KDE, Gnome, Enlightenment, etc). Either I am missing something or the bug is outdated.

**Comment by chaoskagami** [comment]
DBus is a protocol for communicating with a remote process. It's a lot like RPC on Windows. Unless you run gentoo or LFS, chances are your system has DBus on it.

This code seems to be attempting to communicate with a session manager, like gnome-session, xfce-session, awesome-session, etc. libgnome was implemented for communication with Gnome2. It also worked with some other session managers at the time, perhaps. Gnome2 is no longer developed. The code seems to be used for the 'save running applications on logout' functionality in multiple desktops. What they're suggesting is one of three things to fix it:

1) Use DBus to talk to gnome-session directly, rather than use libgnome to do so. This will obviously only work under GNOME. They also are discussing this as gnome3, which implies a need for *systemd* with the latest versions. This is inappropriate for multiple reasons.
2) Use libSM. This is a generic session management library that works regardless of desktop.
3) Pretty much same as 2 with a different library, and used in-tree rather than dynamicly.

Cutting out DBus will most certainly fix this, since it couldn't communicate with a session manager if it wanted to. You would also have to cut this out on top of that. However, DBus is used for other things besides this (although, I haven't looked into what.)

**Comment by wolfbeast** [comment]
If we're taking this then we should have a look at both patches on that bug. It may be easier to refactor forward from the 2012 one than to unrefactor the 2015 one.

**Comment by Axiomatic-** [comment]
@chaoskagami is D-Bus not desktop environment independent? (When I say that, I mean does gnome-session have to be talked to directly?) I run xmonad however still have a D-Bus daemon running. As well as my init system not being _systemd_.

I did have some time to dig in a little deeper, and the code seems to also restore the previous closed session as well, if all one needs to do it inhibit the session from being kill (to save then close), there is a specification for a D-Bus API that seems to inhibit the session:
http://people.freedesktop.org/~hadess/idle-inhibition-spec/re01.html

Reasons on why I would prefer to use D-Bus rather than ICE is because D-Bus seems to [have the capability](http://dbus.freedesktop.org/doc/dbus-faq.html#inter-client-exchange).

**Comment by chaoskagami** [comment]
Yes, DBus is desktop independent.

I was reading through the Mozilla bmo and largely summarizing what they thought they should do. Which...were all dragging in dependencies to replace gnomeui, basically.

If generic DBus can be done for this, that's great. Didn't seem to hit the Mozilla guys at the BMO. None of the patches there may be easily portable if that route gets taken.

On December 15, 2015 12:54:52 AM EST, "S." <notifications@github.com> wrote:
>@chaoskagami is D-Bus not desktop environment independent? (When I say
>that, I mean does gnome-session have to be talked to directly?) I run
>xmonad however still have a D-Bus daemon running. As well as my init
>system not being _systemd_.
>
>I did have some time to dig in a little deeper, and the code seems to
>also restore the previous closed session as well, if all one needs to
>do it inhibit the session from being kill (to save then close), there
>is a specification for a D-Bus API that seems to inhibit the session:
>http://people.freedesktop.org/~hadess/idle-inhibition-spec/re01.html
>
>Reasons on why I would prefer to use D-Bus rather than ICE is because
>D-Bus seems to [have the
>capability](http://dbus.freedesktop.org/doc/dbus-faq.html#inter-client-exchange).
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/MoonchildProductions/Pale-Moon/issues/193#issuecomment-164651389

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mattatobin** [comment]
Is this still a concern in Tycho?

**Comment by trav90** [comment]
Yes. Mozilla just recently (June) landed the patches for FF 50.

**Comment by trav90** [comment]
Solved by UXP.
