### ISSUE TITLE
Pale Moon cannot build against system nss since ec48ccc34fe6c17ef9ce6437667e325361bd6198

### ISSUE THREAD

**Issue by chaoskagami** [MoonchildProductions/Pale-Moon#200]
As the title says. While I'm glad this was added to nss by Pale Moon, it also means this patch to nss needs to be mirrored system-wide, due to added declarations. This means that Pale Moon can't be built against nss 3.20.1 from mozilla.

If the work on adding ciphers to nss was done upstream and hasn't made it to a release yet, that's one thing. If this is a patch made by you guys, I'd suggest offering a patch for system nss or disabling system nss use since this commit broke API compatibility with it.

**Comment by wolfbeast** [comment]
There is never a guarantee that using system libs will build, since the intended libs for Pale Moon are always the ones included in the source tree. Adding this to NSS is an open bug at Mozilla (https://bugzilla.mozilla.org/show_bug.cgi?id=940119) and intended to be incorporated (has a reviewed patch and everything but is stale (patch from April 2014)), and until this lands, **not using system NSS is your solution**. I wasn't going to wait for this to travel through the pipes however long it takes, since there seems to be resistance to supporting the ciphers in Firefox and the AES-only status quo is not something I'd want to maintain or support.

As an aside: there is also no guarantee that the "latest" system libs will always work with our code base, and you're pretty much on your own if you decide to take that chance.

**Comment by chaoskagami** [comment]
I think personally you made the correct decision. The very fact that they're resisting adding strong non-aes ciphers is odd. Mozilla has shot themselves in the foot a lot lately. Knowing them, it probably will never land upstream. Maybe you should fork nss too and make it a submodule? :P (just kidding)

Since I run LFS, I applied this patch to my system nss. I can get away with it since I don't have to worry about binaries. Doing so will only probably work for LFS, Gentoo and Arch users however.

Anyways, thank you for the information, MC. I was overtired when I filed that issue, but better a closed bug report for the next person who complains about it breaking, right?

**Comment by wolfbeast** [comment]
> Maybe you should fork nss too and make it a submodule? :P (just kidding)

In a way I already have, with it being part of the Pale Moon tree and used by default ;)
