### ISSUE TITLE
.src file load order

### ISSUE THREAD

**Issue by EuanM** [MoonchildProductions/Pale-Moon#230]
http://bit.ly/clubknight-demo2 does not load successfully on PaleMoon/Windows 7
The code successfully runs on other platform/browser combinations.  (the full list is at http://clubknight.uk)

Probably  due to JavaScript source file loading order, 
plus interaction with the in-line Javascript.  (prob. espec, the lines of document.write code.)

The code successfully runs on other platforms.  (the full list is at http://clubknight.uk)

**Comment by wolfbeast** [comment]
No, it seems the issue is that the site is using a mobile-specific (and 2 year old, v1.3) version of the jquery library which throws an error on initializing.

`[20:35:57.971] TypeError: e is undefined @ http://clubknight.uk/trial/jsLibs/jquery.mobile.js:2`

**Comment by EuanM** [comment]
It throws an error on initialising *in PaleMoon*.  It uses both jquery.js
and jquery.mobile.js
This is what seems to be load-order dependent.

**Comment by wolfbeast** [comment]
Yeah, it throws an error in Pale Moon. And hitting F5 clears the error. So, it's timing sensitive -- if the mobile jquery library depends on the main jquery library being initialized, then assuming they are loaded sequentially when listing them one after another in the HEAD isn't a very smart thing to do. it lets the browser decide how to grab the externally-linked files; this means that it may be finished with the mobile one before the main jquery one.

**Comment by EuanM** [comment]
It may not be very smart - but it's *specification compliant*.

**Comment by wolfbeast** [comment]
Pale Moon is spec compliant. It loads and parses the Javascript in sequence. Whether an asynchronous/deferred initialization in the loaded JS (which I gather is what jquery uses as to not block the page) finishes in time or not falls outside of the spec. Did you even read my entire previous comment?

**Comment by EuanM** [comment]
Yes, I read it.  That was not my reading of the spec.

**Comment by wolfbeast** [comment]
Why do you think things like HeadJS exist if this wasn't a known snag for linking multiple script sources in the head? JQuery in particular is notorious for being problematic for other scripts that rely on it.

**Comment by EuanM** [comment]
Known snags and workarounds are not the issue.  Why do you think they are
called "snags"?  And "workrounds" ?

**Comment by EuanM** [comment]
I have an issue in Palemoon that I don't in Firefox, Opera, etc etc.  I
reported it.  Why so defensive?

**Comment by wolfbeast** [comment]
The "snags" are snags resulting from a particular web design.
There is nothing that can be done on the browser side to solve what is ultimately a web design problem.

Why defensive? Because you're on the offense saying it's most definitely a Pale Moon bug, while it isn't. You're asserting that we're not spec compliant, etc. We are.

If you want me to spell it out for you:
- Script 1 is loaded and parsed
- Script 1 starts its initialization (which is done asynchronously because of the way the script is constructed)
- Script 2 is loaded and parsed
- Script 2 starts its initialization

If script 2 starts its initialization and that initialization depends on something that is only ready after script 1 has finished initializing, then script 2 will fault if script 1 isn't done with its initialization yet. Basically, Pale Moon is too fast loading and parsing script 2 so the init starts before script 1 is completely done.
The spec only covers the loading and parsing in sequence, which Pale Moon does.

If you want to avoid these issues, you can, for example, combine the scripts that are interdependent into one, or use smarter placement of your scripts in the head/body, or use script deferring mechanisms.
