### ISSUE TITLE
Implement an active XSS filter

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#257]
Just a meta here to keep track of the v26 milestone features.

Current status:

- [X] Implementation
- [X] Initial testing
- [X] Implement DOM filtering selection
- [X] Implement domain whitelist
- [X] Implement domain whitelist UI
- [X] Merge to trunk
- [x] Beta testing
- [x] Public beta testing
- [x] Adjust the filter implementation based on feedback
- [x] Completion

**Comment by TPS** [comment]
Just wondering.…  Is there a particular reason to implement this directly in PaleMoon if Noscript has a [very mature version](https://noscript.net/features#xss) for many years?  E.g., is there potentially _more_ protection available if implemented directly?  I _do_ understand this would amazing to have for [those who _don't_ use Noscript](https://noscript.net/faq#qa4_1), but just wanted an insight to your concept for comparison of this feature between the 2 implementations.

**Comment by wolfbeast** [comment]
Yes, there is. Mature as it may be, NoScript's version is prone to many more false positives, as well as not protecting against a number of additional reflected XSS attacks covered here. Also, the browser, if implemented this way, has a much easier time being able to compare the request with the actual returned result in-page.

I consider this an essential enhancement for every user of Pale Moon, so it belongs in the core. NoScript comes with a lot of extra baggage as well which I don't want to inflict on our users because of the known problems the extension causes by being too aggressive..

You may want to have a look at the paper (pdf attached) written by the person responsible for the implementation of the matching algorithm in this implementation here, which makes a direct comparison between Chrome's XSS filter, NoScript's XSS filter, and this implementation.

[xss.pdf](https://github.com/MoonchildProductions/Pale-Moon/files/58619/xss.pdf)

**Comment by TPS** [comment]
Thanks for the useful info. I _did_ forward to Ma1 @ Noscript (don't _think_ he's on GitHub), since as many folks as possible should reap the benefits of that paper.  Do you think then there's likely to be conflict running Noscript or other referred XSS protection mechanisms on PM once this comes live?

**Comment by squarefractal** [comment]
[**@TPS**](https://github.com/TPS) commented on [Friday, December 11, 2015 9:13:13 PM](https://github.com/MoonchildProductions/Pale-Moon/issues/257#issuecomment-163967612 "2015-12-11T15:43:13Z - Replied by Github Comment Enhancer"):
> Do you think then there's likely to be conflict running Noscript or other referred XSS protection mechanisms on PM once this comes live?

You can always set `security.xssfilter.enabled` to false if you want to disable Pale Moon's built-in XSS filter.

**Comment by wolfbeast** [comment]
There *shouldn't* be any conflict with e.g. NoScript, especially if those solutions filter the requests to begin with (in which case the built-in XSS filter simply won't find anything to complain about)

**Comment by BruceBerry** [comment]
Author of the paper here. Giorgio can't architect his filter this way because the API available to extensions does not have the required hooks, I had to add stuff to the C++ codebase. In this sense, this filter is much more similar to Chrome's XSS filter, which is also not an extension but part of the codebase.

The two filters won't conflict with each other, although you definitely have a higher chance of false positives and higher overhead that way. You can disable mine through the pref @squarefractal mentioned, it won't slow anything down when it's off.

**Comment by TPS** [comment]
Or, conversely, set `noscript.injectionCheck` to `0`.…  I have a much better understanding now; thanks @wolfbeast, @squarefractal, & @BruceBerry! ☺

**Comment by wolfbeast** [comment]
As an aside, the XSS filter will also have an enable/disable checkbox in the browser's Options in the final release.

**Comment by wolfbeast** [comment]
With the latest changes to this code it can now be considered functionally complete - closing this tracking bug -- any specific issues with it should be listed as a new issue (bugfixes as opposed to implementation)
