### ISSUE TITLE
SSL/TLS connections are claimed to be unencrypted for feeds.

### ISSUE THREAD

**Issue by squarefractal** [MoonchildProductions/Pale-Moon#275]
Feeds delivered over SSL/TLS are claimed to be unencrypted when they are viewed from the feed subscription UI. The padlock and the identity panel are not displayed, and the page info dialog and the identity panel dropdown claims that the connections are unencrypted.

An example can be seen in the screenshot below:

![1](https://cloud.githubusercontent.com/assets/11385622/11923854/834ec6e0-a7cf-11e5-94be-c5d204140bba.png)

**Comment by wolfbeast** [comment]
The reason for this is:

- the original content loads over https (secure)
- the preview page is loaded from a jar channel (insecure)

nsSecureBrowserUIImpl inspects the current channel for securityInfo and uses that to update the browser UI. 

In this "nested" channel situation we have no way of knowing what the securityInfo of the original channel is. 

This will potentially require significant API changes. Since this is lower priority (worst case is the user getting freaked out that content isn't secure when it actually is -- in any case https: is still shown in the address bar even if coloration and lock icon aren't present), it'll be on the backburner. Keep in mind that this page is a **preview** only.
