### ISSUE TITLE
Follow-up to #189 - Animations in SVGiOT

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#280]
This is a follow-up to #189 which aligns the SVG-in-OpenType implementation with the spec.

One thing that is missing is SVG animations in those font glyphs.
Relevant BMO [Bug 906643](https://bugzilla.mozilla.org/show_bug.cgi?id=906643) - Support animation in SVG glyphs

Question is: do we want this? Having multiple colors in fonts is already pushing the definition of a font-face, animation would go way beyond that.

**Comment by wolfbeast** [comment]
We probably need this or intended animated SVG text may not show at all.

**Comment by wolfbeast** [comment]
Mozilla's hashtables still suck. :-1: 
I may have to rewrite some of this.

**Comment by wolfbeast** [comment]
Current state of the SVGiOT branch is that it builds with animation support and doesn't crash, but animations also don't work and it screws up SVG font scaling. Putting this on hold, anyone willing to help is welcome since I obviously don't know enough about the refreshdriver involved to fix this.

**Comment by chaoskagami** [comment]
The reason em scaling broke is that you derped when moving the ctors in gfx/thebes/gfxFont.cpp from the header. You removed 'mUnitsPerEm(0)' which leaves the em size uninitialized when created. No offense intended by this of course. ;) This was commit 8e09b99b8f6628258505831b818f0d9628ad23e3.

I make no guarantees about getting it working, but I'm going to toy around with this. There are a number of changes in the refreshdriver that lead me to believe it isn't even calling the animation code. If I do, I'll go through the usual PR process. (please don't consider me assigned on this one.) Got a test page with animated glyphs?

**Comment by chaoskagami** [comment]
Ugh, this is complicated. In a nutshell, there's nothing wrong with what you ported @wolfbeast. The problem is a bit deeper seated...

Summary of what I think is going on: RefreshDriver isn't up-to-date, and is not doing what the Animation patches expect. Animations are never performed for SVGs that are fonts, because the implementation is a stub. We're missing some commit that was added before this at some point in 2013. Looking at the tree from the same time as the eighth patch in 2013, the refreshdriver uses RestyleManager, which appears to be unimplemented (#22?) What it looks like; SVGiOT can't use the same animation update code as SVG because it has to be considered as text and requires separate timers for each letter. Plus the possibility of being deleted/unloaded at a moments' notice. This code is missing from Goanna, so an entity is created on the page but it never refreshes (leaving it blank.)

I have absolutely no clue what needs to be done to fix this, but here's a list of potentially related bugs:

https://bugzil.la/1058634
https://bugzil.la/1002632
https://bugzil.la/666446

I could be completely wrong, but assuming I'm onto something - our backend is out of sync with this code. It's no wonder it doesn't work.

I'm not going to take this bug, but there's some information for anyone wanting to attempt this.

**Comment by wolfbeast** [comment]
The problem with the RestyleManager code is that it's just refactored code and so far has not been needed at all to be strictly its separate entity; I don't see why in this case it would be any different...

The thing you indicate (requiring separate timers for each letter) is I think more the issue here - it means we'd have to start drawing all text one glyph at a time and attaching individual parameters/events to each letter. I'm sorry but that's really counter to the way text is supposed to work, and I don't even want to know the impact this will have on performance.

**Comment by chaoskagami** [comment]
I'm just kind of pointing out what I observe from looking at the code. Mozilla code is like soup - it links together all over the place in a really badly modularized manner. I went through a very limited amount, and without running it through a debugger I'm not sure I'm even close to 100% correct.

Honestly; I don't even want to know what effect this will have on performance either. Personally I think anything past static SVGs colored or not is a disaster waiting to happen, not to mention that it must munch through RAM like potato chips (heh.) Adding to the fact that there's no real legitimate use for animated text outside of games (read: `<canvas>`)

Didn't know that bug 666446 was implemented (silly me.) Kind of tired here, need more caffiene. :P

**Comment by wolfbeast** [comment]
Animations in SVGiOT have been fixed by Tycho, with a follow-up fix (see MoonchildProductions/Tycho@510de6c80ef7f928c5cfa0c2f45470d6929b595d) to prevent massive performance issues (to the point of hanging the entire browser and eating up whatever cores it was given). This should all be working as-intended now. Closing.
