### ISSUE TITLE
Exiting DOM full screen mode causes the window to exit full screen mode as well

### ISSUE THREAD

**Issue by Antonius32** [MoonchildProductions/Pale-Moon#304]
Currently, exiting full screen mode for an HTML5 video causes the containing window to exit full screen mode as well, and I think that's undesirable. I think exiting DOM full screen mode should mean just that; it should not implicitly change the window state of the containing window.

For Firefox, this issue was fixed in bug [947854](https://bugzilla.mozilla.org/show_bug.cgi?id=947854), but the final patches ("fix this bug" and "simplify code") cannot be applied to Pale Moon as-is; relevant changes, that were introduced in Firefox before this bug was dealt with, will have to be taken into account.

**Comment by wolfbeast** [comment]
Sorry if I don't understand the issue. If you exit full-screen mode, don't you want to actually *exit* full-screen mode? Why shouldn't this apply to the browser as a whole?

**Comment by Antonius32** [comment]
The way I see it, if a user is browsing in full screen mode, and then comes across a video and decides to play it in full screen, they would expect to return to a full screen window upon exiting full screen mode for the video. For Flash video, that's what happens, indeed, but for HTML5 video, it's not. I think the full screen behavior for Flash video is correct, and the behavior for HTML5 video should be on par with it. (Also see https://bugzilla.mozilla.org/show_bug.cgi?id=947854#c17)

**Comment by wolfbeast** [comment]
Hmm.. not necessarily. But I can see both approaches, so this is probably good to have BUT should be behind a pref.

**Comment by chaoskagami** [comment]
I'm with @Antonius32 on this. If I was browsing in fullscreen and hit the maximize button on a video, when I hit unmaximize I would expect to return to the previous state. So if my window was fullscreen, it would return to fullscreen. Otherwise, windowed.

It's a stack of states, not a toggle. If a user enters fullscreen, and a video enters fullscreen, then exits, the user has still set the browser fullscreen and it should remain as such. Nowhere did the user exit fullscreen, they minimized a video (in their mind, at least, never mind actual implementation)

I don't think this is a pref-required issue. I think it's a bug. Then again, I'm all for more configurability.

**Comment by wolfbeast** [comment]
I don't think it's a bug; it's a design decision. Now when it comes to Mozilla, those *can* be considered equal sometimes ;)

Anyway, either way, patches are welcome; I'm swamped with more important things to give this the proper attention it requires. It's a little complex because you'll need to make both states completely independent.

**Comment by wolfbeast** [comment]
Considering we've re-based to something very close to when this was applied in Firefox, this has probably become a lot easier. It should be given another look.

**Comment by wolfbeast** [comment]
We'll have this solved in a UXP-based Pale Moon. Closing.
