### ISSUE TITLE
Implement CSS gradients on premultiplied colours

### ISSUE THREAD

**Issue by Lootyhoof** [MoonchildProductions/Pale-Moon#308]
Currently, using a `gradient` of any kind in CSS will look incorrect if going to or from `transparent`, as it makes the gradient move to grey rather than transparent. Let's fix this.

BMO: [591600](https://bugzilla.mozilla.org/show_bug.cgi?id=591600).

**Comment by wolfbeast** [comment]
So, if I understand this correctly, the perceived problem is that `transparent`, having no inherent color in and of itself, will make the color shift towards 0% saturation while the gradient runs to transparency?

**Comment by Lootyhoof** [comment]
Essentially, yes. The test case in the BMO probably describes it best, but to show things a bit better I took a screencap of it:
![Test case](http://i.imgur.com/2to6185.png)

**Comment by wolfbeast** [comment]
Actually, the test case is comparing 2 different things ;)
rgba(255,255,0,0) is not the same as "transparent". It's a color yellow with 0 opacity. They are *effectively* the same thing when looking at the resulting pixel values values after calculating (*,*,*,0) since the color is irrelevant for a fully transparent color. Any of those colors with an alpha of 0 is transparent, so transparent as a keyword is very ambiguous if you're going to imply colors.

So, it depends on what the interpretation of "transparent" should be.

The way Firefox does it to me seems incorrect, as well. Using premultiplied color space for example will fail to render linear-gradient(rgba(255,255,0,1), rgba(255,0,0,0)) correctly, and you won't have a shift to red while transitioning to transparent, as intended, because it assumes no hue shift at all just because the final value is transparent.
The spec also doesn't say anything about either being incorrect, only that:

> Interpolating colors using the premultiplied representations rather than the plain rgba representations tends to produce more attractive transitions, particularly when transitioning from a fully opaque color to fully transparent.

So what should be done is special-case the "transparent" keyword only, I think.

Using pre-multiplied color space is wrong because it leads to unintended gradients (or lack thereof). In fact, it'll lead to very poor gradients for e.g. shifting to a very small alpha for a different color at 100%.
Compare [Testcase](https://dl.dropboxusercontent.com/u/1466747/Palemoon/betatest/gradient-transparent-test.html) in Pale Moon and Firefox. I think Pale Moon does everything correct but could do with a special case for "transparent". The bottom ones in Firefox are just plain wrong.

**Comment by wolfbeast** [comment]
Actually filed a bug for Firefox.
https://bugzilla.mozilla.org/show_bug.cgi?id=1241717

**Comment by wolfbeast** [comment]
I looked at it a little more and I think the main issue is simply that `transparent` in the Mozilla-inherited code translates to `(0,0,0,0)` which is black with 0 opacity. This is going to be very noticeable on light colors fading to visually transparent on white because there's a big luminance shift.

Considering `(0,0,0,0)` is extremely unlikely going to be intentional as an rgba value with the exception of the reserved keyword, this can be fixed easily; with the only quirk that if it's intentional to fade to as we do currently with `transparent`, that that will no longer work since we'll be special-casing it to be a pure fade to the transparent version of the adjacent color(s). Workaround being using a non-0 alpha (can be really small which would equal to 0 pixel value after computation) or non-zero component for any of the channels.

**Comment by wolfbeast** [comment]
Commit dab2fee747d1853d5e081f69750869d45b7cf6b0 and friends special-cases 'transparent' but doesn't make it work on premultiplied RGBA color space since that's just plain bad and makes it impossible to have proper gradients. Even for someone who doesn't know CSS that I showed this to, their logical expectation was our current behavior and not Firefox's...

**Comment by wolfbeast** [comment]
Also, it looks like the W3C spec has been flipped back and forth a few times to describe converging browser behavior rather than describing a sane way of doing this. We may currently be the odd one out but I really don't want to make gradients use premultiplied calculation values -- you're effectively limiting your color space if you do that. I've poked the www-style mailinglist about this but no reply yet.

**Comment by wolfbeast** [comment]
Discussion on the W3C CSS mailing list found some initial resistance but otherwise people seem to be amenable, especially Adobe's voice was positive about it. We may see a spec change as a result, but it'll likely take some time because bureaucracy.
