### ISSUE TITLE
Yahoo Calendar

### ISSUE THREAD

**Issue by Reed3** [MoonchildProductions/Pale-Moon#320]
With PM 26.0, Yahoo Calendar does not display (worked with PM 25.8), verified Yahoo Calendar would still not display by restarting PM with add-ons disabled (see below screen shot)  I'm running Windows 10 with all current updates installed.  Not much more to add, happy to test any potential fixes.
![yahoo calendar does not display screen shot](https://cloud.githubusercontent.com/assets/16908569/12599998/ce3b07c4-c45b-11e5-95a9-d3c2743c8cdc.PNG)

**Comment by wolfbeast** [comment]
Using a useragent override will work around this. There doesn't seem to be any issue with Pale Moon not being able to display the calandar.

To solve it, you may want to add your votes to https://yahoo.uservoice.com/forums/210695-yahoo-mail/suggestions/11596617-yahoo-calendar-refuses-pale-moon-26-arbitrary-us since this is a server-side check by Yahoo.

Workaround: new pref `general.useragent.override.calendar.yahoo.com` set to `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0 (Pale Moon)`

**Comment by Reed3** [comment]
Thanks, but what exactly do I do with the workaround?

**Comment by Axiomatic-** [comment]
In the address bar type: `about:config` you should see a list of values, Right click, however over the New, select String.

A window should pop up and ask you for preference name, in that enter: `general.useragent.override.calendar.yahoo.com` click okay. Another window will pop up, at this point enter `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0 (Pale Moon)`

**Comment by Reed3** [comment]
Works perfectly!  Thanks you very much for the assistance!

**Comment by wolfbeast** [comment]
Commit 2a6068ca2f9e333314eb685d7c7c549846af3863 resolved this with a default UAO.
