### ISSUE TITLE
Add more Web accessibility to the browser

### ISSUE THREAD

**Issue by Lennium** [MoonchildProductions/Pale-Moon#325]
Pale Moon really lacks in 2 departments heavily: ES 6 features and the fact that Pale Moon expects that scripting on a page has no lose implementation (IE11, QTWebkit or Webkit/Blink browsers have no problem with this most of the time). Also, Promise is only partially implemented which can make problems.

Would be essential if this year more development resources would be used for enhancing the browser in that few departments.

Thanks!

**Comment by wolfbeast** [comment]
If websites are specifically telling the browser "use strict" then the browser is supposed to apply strict rules. Not "kinda sorta" or "when I feel like it" or "try loose/quirks anyway if the site breaks".

ES6 enhancements: patches are welcome.

Marking this as invalid because it's not a concrete issue, and more a "general statement" that doesn't actually address anything. We don't need help understanding what needs to be on the roadmap. we have that figured out.
