### ISSUE TITLE
"Classic downloads window" shows nothing

### ISSUE THREAD

**Issue by bernardkkt** [MoonchildProductions/Pale-Moon#328]
If the option "Use the classic downloads window" is enabled:
![capture1](https://cloud.githubusercontent.com/assets/16949329/12665649/1175a2c8-c674-11e5-9c1f-66d3f6eab163.GIF)
The download window will not display any queuing task.
![capture](https://cloud.githubusercontent.com/assets/16949329/12665720/95097a2e-c674-11e5-83ea-e11737c7d58b.GIF)
That happened in Portable Palemoon Version: 26.0.0 (x86) when the option was enabled at first, then proceeded to download an executable file.

**Comment by wolfbeast** [comment]
I always use the classic download window myself and haven't seen any issues with it. Are you using any extensions that do something with downloads?

**Comment by bernardkkt** [comment]
@wolfbeast No I didn't install any extensions yet at that time. I ran Palemoon from the extracted folder, started private browsing, then clicked on a link. I soon realised that the classic download window was empty when I attempted to check the progress of the download.

**Comment by wolfbeast** [comment]
Aha! well there's your issue.
Private browsing would (obviously, since it's private) not propagate what you're downloading to outside the private browsing session, which includes the global download window. That is very much by design to keep private sessions private.

To check the downloads in private browsing mode, press the downloads button or ctrl+j *in the private window* and it will show the downloads for that private session.

**Comment by bernardkkt** [comment]
@wolfbeast Thank you, you are right. I can see the progress now with the steps you have suggested.
