### ISSUE TITLE
Possible solution: Google hangouts

### ISSUE THREAD

**Issue by LennyDMighty** [MoonchildProductions/Pale-Moon#347]
There was an interesting post in the board, but it seems that it was overlooked, so i post this solution here too, perhaps you guys can enhance Pale Moon in some way that it works with Hangouts again:

-----------------------------------------------------------------

http://forum.palemoon.org/viewtopic.php?f=29&p=77446#p77339

-----------------------------------------------------------------
Postby evgeny » Thu Feb 04, 2016 6:57 pm

Hi. I just finished investigating the issue.

This is due to DOMException ( "The operation is insecure.") at javascript https://hangouts.google.com/_/scs/chat- ... lccdc-9stQ

In this javascript at a line number 63 there is the following code "var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();"
At a.open() we get the exception.

I use Fiddler (http://www.telerik.com/fiddler) to replace this code with "var b=a.contentWindow,a=b.document;a.body.innerHTML="";a.close();"
(actually replace javascript file with edited one)
and now hangouts works in Pale Moon 26.0.0 (and in 26.0.2).

I did not yet report this to Google.
But it looks like Google knows about this this error because I see the following requests right after the exception (and this request looks like error reporting).
https://hangouts.google.com/webchat/u/0 ... e.&line=63

**Comment by wolfbeast** [comment]
The post wasn't overlooked.
This is not something we can change on our end, though.

**Comment by wolfbeast** [comment]
I got some more information regarding this matter from another poster on the Google Hangouts forum relayed to us.

    Somebody on Google Hangouts forum wrote:Hangouts doesn't work in Pale Moon 26.x due to the exception

    s=AGNGyv1Bt7FbwZilcKuxKPLKAg6VyPTmNg

    [object DOMException] at line 63:
    file: https://hangouts.google.com/_/scs/chat- ... lccdc-9stQ
    Exception message: "The operation is insecure."
    name: "SecurityError"

    Code at that line:
    a=document.createElement("IFRAME");
    a.style.display="none";
    a.src="";
    document.documentElement.appendChild(a);
    var b=a.contentWindow,
    a=b.document;
    a.open();
    a.write("");
    a.close();

    At "a.open()" the Pale Moon throws the exception.

I think Pale Moon's behavior is correct. You can't just add an iframe and be allowed to manipulate the iframe's content that way.
In fact, creating an iframe with src="" means it's an in-line iframe, and its content is not defined by the iframe document content (like a classic iframe) but in fact by the actual inner content of the tag itself.
I'm really not sure what they are trying to do here - it seems to be a test if writing arbitrary data to an anonymous (and hidden) iframe's document is allowed, but specifying it as an in-line iframe means that's not possible, and I think the same-origin policy would otherwise prevent it anyway. So... looks like a scripting error on Google's side to me, unless I'm really missing something.

**Comment by wolfbeast** [comment]
Some more research indicates this is likely an undefined/incorrect code path on Google's side caused by a problem with our Promises implementation.
