### ISSUE TITLE
Add musl libc support. 

### ISSUE THREAD

**Issue by Axiomatic-** [MoonchildProductions/Pale-Moon#366]
Current master branch does not build with a musl libc combination, getting it to should not be too hard. 

Reason: Growing adoption of musl libc in [Linux distributions](http://wiki.musl-libc.org/wiki/Projects_using_musl).

**Comment by wolfbeast** [comment]
mu-whatnow?

**Comment by wolfbeast** [comment]
I'm sorry but until Linux gets its act together and decides on ONE way to do shit, I'm not likely to cater to the latest shinies.

**Comment by bmentink** [comment]
I would like this as well, please don't dismiss so soon!

**Comment by the-maldridge** [comment]
Even if it was supported, after [the Pale-Moon OpenBSD fiasco](https://github.com/jasperla/openbsd-wip/issues/86) its unlikely any distribution would accept the port.  I know Void's official stance is "no more Firefox clones, and especially not hostile ones."

**Comment by g4jc** [comment]
You might want to inform those ~~snowflakes~~ folks that Pale Moon is no longer just a browser, but an entire toolkit. There is no reason to ban all XUL applications just because of a single issues with OpenBSD where they were improperly packaging the software (they could have just used NewMoon branding and resolved all of that, OR complied with the trademark requirements).

If you think they were hostile I advise you to read more of [Linus Torvalds](https://github.com/corollari/linusrants) or [Theo de Raadt](https://en.wikiquote.org/wiki/Theo_de_Raadt).

**Comment by mattatobin** [comment]
I see I might have to go through and lock old issues because people want to cause trouble. How unfortunate.
