### ISSUE TITLE
26.1.0 tab bar scrolling buttons displayed even if unncecessary

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#367]
> I have set browser.tabs.tabMinWidth to 1 and browser.tabs.tabMaxWidth to 180.
This means that tabs are never scrolled, and scrolling buttons are never needed.
Yet they are still displayed (and non-functional) in PM 26.1.0

![pm3](https://cloud.githubusercontent.com/assets/3359132/13109077/6c16f904-d577-11e5-9dcd-926367989f36.png)

**Comment by wolfbeast** [comment]
This isn't yet solved, despite #365 - one the tab bar overflows in maximized mode, the arrow scroll boxes remain in place.

**Comment by Antonius32** [comment]
> This isn't yet solved, despite #365 - once the tab bar overflows in maximized mode, the arrow scroll boxes remain in place.

I'm not sure what you mean, can you clarify? The patch seems to work for me..

**Comment by wolfbeast** [comment]
If I maximize a window, with tabs on top, and add tabs until the tab bar overflows (scroll arrows appear) then closing tabs will not remove them again (it never triggers an underflow).

**Comment by wolfbeast** [comment]
Correction, it does trigger an underflow, but only if it reaches max tab width.

**Comment by wolfbeast** [comment]
I think I know what's going on here -- not necessarily a styling issue.

**Comment by wolfbeast** [comment]
Yup, figured it out. 
If set to use resizing immediately, it displays this behavior -- which makes sense for the logic involved.

**Comment by Antonius32** [comment]
Ah, I see what you mean, now.

I've done some testing, and I am positive that this is in fact a styling issue; it is caused by the negative side margin on the tabs that was introduced by PR #317 (commit a6c16f0). And I've found that another issue, regarding the tabs' resizing behavior when browser.tabs.resize_immediately is set to "true", is caused by this negative side margin as well. For reference, see [this](http://forum.palemoon.org/viewtopic.php?f=3&t=11419) topic on the forum.

I think we may end up having to remove the transparent outer border of the tabs, after all. In that case, we'll just have to live with the fact that when the tabs are on top, they are "glued" right up against the top edge of the screen when the window is maximized or in fullscreen mode...

**Comment by Antonius32** [comment]
> And I've found that another issue, regarding the tabs' resizing behavior when browser.tabs.resize_immediately is set to "false", is caused by this negative side margin as well.

Never mind, I just saw that this problem was dealt with in issue #384. But that still leaves the problem of the scrollbox arrows not disappearing in time when tabs are closed, doesn't it?

**Comment by wolfbeast** [comment]
Well, the issue is that our current tab browser logic can only do one of two things: resize immediately when a tab is closed, or not. Because of the negative margins we apparently never trigger an underflow when resizing automatically, so it will only underflow when our total tabstrip width actually becomes less than the available space+ scroll buttons, at which point it no longer overflows and the scroll buttons are removed.

I don't see an easy way to rewrite this logic in a way that would work in all situations, fixing this would break windowed behavior, for example, and I want to avoid making this too complex because it's code that gets triggered all the time, not to mention rapid closing is using a queueing system which will likely break as well.

the commit for #384 is a rather crude workaround which makes tab closing behavior a little ambiguous if you hit the front or back limit of tabs. if we can remove the negative margins to fix this, it'd be better; we'll just have to live with the on-edge tab borders in that case, but from a functional point of view it's more important to have behavior right than preferred aesthetics.

**Comment by Antonius32** [comment]
> (...) from a functional point of view it's more important to have behavior right than preferred aesthetics.

I agree. I'll create a pull request that removes the transparent border, tomorrow. When I do, there's no need for the fix/workaround for issue #384 anymore; would you like me to revert commit 1ba944a while I'm at it?

**Comment by wolfbeast** [comment]
If you can confirm it's fixed with that backed out then yes please roll it into one PR.
Thanks for your work!

**Comment by Antonius32** [comment]
Before I make any changes, I have a question and a suggestion - I hope that's OK.

Question

Can you explain exactly why you decided to stop using tabbrowser.png (see commit 1204d1f) in the first place? My guess is that you were preparing for commits 1ab05a7 and cdf4201, in other words, dropping the use of a border image was the easiest way to be able to set different border radiuses for the tabs for different Windows versions later on, is that correct?

Suggestion

Since Windows 8 and Windows 10 are styled similarly, just like Windows Vista and Windows 7 have similar overall styles, I thought that perhaps we could go with the following styling scheme for the various Windows versions:

- Windows Vista / 7: Restore the old style for the tabs; reinstate the border image.
- Windows 8 / 10 : Use the "Square is the new round" style; set the border radius for the top corners of the tabs to 0 for both OS versions. This allows us to add a transparent top border to the tabs - so we have Fitts' law compliance *and* aesthetics - but without the need to add a transparent side border as well (because a border radius of 0 cannot be stretched/distorted when the joint borders are not equally wide) and thus without the need to use negative margins.

If you don't like this idea, then I'll simply remove the transparent border and the negative margins - no problem at all.

**Comment by wolfbeast** [comment]
The tab.png border image was an ancient hack from an era before we had both proper and speedy CSS rendering. It's a bad solution and it will not play well with higher DPI settings, for example, as well as creating ugly stretched textures as a border image that are going to blur and bleed.
On top, it indeed prevented easy and correct CSS styling of the tabs, but the border radiuses was actually a secondary consideration.

As you can imagine, I don't want to reinstate the border image because that would effectively lock us in to a hacky, inflexible solution from a bygone era. We don't need to use a border image because tab shapes don't have exotically-shaped borders (which is what border-image is for, really, not for a simple 2px pre-rendered rim)

As an aside I'm not sure why the negative margins were needed to begin with - you can create double borders from the edge inward as a normal border, IIRC. Something for a future PR?

**Comment by Antonius32** [comment]
Just a short reply for now - I'm typing this on a mobile device.

From my experience, joining a double top border (a transparent outer border and a colored inner border) and a single (colored) side border causes the visible corner to be vertically compressed, i.e., the corner you end up with is not round. That's why I added the transparent side borders, which I then partially hid by setting negative margins.

**Comment by LimboSlam** [comment]
I agree with @Antonius32. Though proper speedy CSS is indeed important. So maybe down the line sometime this year you guys can find a way to implement the old style for the tabs through proper and up to date code.

**Comment by wolfbeast** [comment]
There are probably other alternatives to do this 1px thing with, then. Like I said that'd be a for a future PR.

**Comment by Antonius32** [comment]
> The tab.png border image was an ancient hack from an era before we had both proper and speedy CSS rendering. It's a bad solution and it will not play well with higher DPI settings, for example, as well as creating ugly stretched textures as a border image that are going to blur and bleed.

A final thought on this: could using a vector image instead of a raster image be a solution here?

**Comment by wolfbeast** [comment]
Potentially, but I have no idea if it's going to play nice with tab animations in that case or not. I think it'd likely cause a lot of paint events and cause a serious performance hit.
