### ISSUE TITLE
XML unxpected parser state on netError.xhtml

### ISSUE THREAD

**Issue by ShadowHunterRUS** [MoonchildProductions/Pale-Moon#370]
![210](https://cloud.githubusercontent.com/assets/9568978/13159833/1ee003c2-d6a5-11e5-878d-533c99d3ef2a.png)

**Comment by janekptacijarabaci** [comment]
See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=569229
https://bugzilla.mozilla.org/show_bug.cgi?id=812853

**Comment by wolfbeast** [comment]
I've CCed myself on bug 569229 to keep an eye on it.
Definitely more info needed -- apparently it's something that can happen with an odd timing of disconnects/connection failures.

**Comment by wolfbeast** [comment]
More info:

This is triggered by nested entities. Expat keeps a linked list of open
entities (openInternalEntities) which goes from the most inner open entity to
the most outer open entity. In this case we're parsing an entity and it ends in
another (inner) entity. While parsing that inner entity we block the parser,
either because we're loading something like script, or because we interrupt.
The inner entity hasn't been completely parsed, so it's not marked closed and
the handler is set to internalEntityProcessor, the outer entity is considered
to have been parsed completely, so it is marked closed and openInternalEntities
is set to null. When we unblock the parser we end up in internalEntityProcessor
with a null openInternalEntities, which is a bogus state and we report an
error.
