### ISSUE TITLE
Use hardened build options (PIE, Fortify Source, Immediate Binding, Stack Protection...)

### ISSUE THREAD

**Issue by luchr** [MoonchildProductions/Pale-Moon#371]
Please think about

1. adding an option for building position independent executables on gcc/clang, [see Mozilla changeset d38de091ced0](https://hg.mozilla.org/mozilla-central/rev/d38de091ced0)
1. using stack-protection compile-time options like `-fstack-protector-strong`
1. using `_FORTIFY_SOURCE`
1. using `-z relro` and/or `-z now` for linking

to build a hardened version of Pale Moon. [There are linux distributions that build Firefox with these hardening options.]

**Comment by trav90** [comment]
1. Could you please elaborate on the advantages of using PIE?
2. `-fstack-protector-strong` is not used in the builds released by us because the underlying code is not static. Note that the Windows builds do not use stack protection either.
3. `FORTIFY_SOURCE` is not used, as it can (in some cases) cause stability issues, and will need an EXTENSIVE amount of regression testing. It is also reported to lower performance on 32bit builds.

4 `-z relro` is already used beginning with Pale Moon 26.0

**Comment by chaoskagami** [comment]
If it matters, my compiler does PIE by default and Pale Moon works fine as PIE. I'm not running gentoo but I'm using gentoo's PIE patchset on gcc and my system runs grsec.

The advantage of PIE, @trav90 is that executables can be relocated like libraries, e.g. loaded anywhere in memory. Thus they get the full advantage of ASLR which would normally not fully work on them. It makes attacks on executables more difficult once execution is gotten from an exploit.

These are indeed security options which WILL lower performance - I think FORTIFY_SOURCE should get some testing but otherwise I think these are options you should be putting in mozconfig with --enable-optimize.

**Comment by luchr** [comment]
Thank you for the fast replies.
@chaoskagami: I use Fedora and compile Pale Moon also with PIE, etc. [Redhat tries to enforce this security features on more and more packages.]

@trav90:
ad 1: see answer of @chaoskagami 
ad 2-4: I was not asking to make them the new defaults (without testing, ...). My request/issue was to ask for simpler methods (e.g. the `--enable-pie` option) in order to make it simpler for people to test/use this features (just by chaning the `mozconfig` file without patching `configure.in` like in the changeset above) such that more users can easily do the testing of the options.

Yes: For some of this security options one has [to pay the price](https://securityblog.redhat.com/2012/12/12/position-independent-executable-pie-performance/).

**Comment by chaoskagami** [comment]
So I ran checksec on PM, and my toolchain automatically enabled both FORTIFY and -fstack-protector-strong when I last built it. My install seems to work fine, as far as I can tell.

**Comment by trav90** [comment]
@chaoskagami, thanks for the info (I was on a mobile device earlier and wasn't able to look it up). I'll look into adding the `--enable-pie` option.

@luchr My apologies, I misunderstood your original post. As chaoskagami mentioned, you can already use your mozconfig to enable those compiler flags by either adding options to `--enable optimize` or using `export CFLAGS`/`CXXFLAGS`.

For the record, when building Pale Moon on my Manjaro box, I believe the compiler automatically uses PIE, and I do enable FORTIFY_SOURCE in the mozconfig.

**Comment by wolfbeast** [comment]
If you had paid attention to the changeset pointed out:

> +# bionic in Android < 4.1 doesn't support PIE
> +# On OSX, the linker defaults to building PIE programs when targetting OSX 10.7+,
> +# but not when targetting OSX < 10.7. OSX < 10.7 doesn't support running PIE
> +# programs, so as long as support for OSX 10.6 is kept, we can't build PIE.
> +# Even after dropping 10.6 support, MOZ_PIE would not be useful since it's the
> +# default (and clang says the -pie option is not used).
> +# On other Unix systems, some file managers (Nautilus) can't start PIE programs

On Android, we target 4.0+ (API level 14), this can't run PIE programs.
On *nixes, there's obvious issues with a number of distros and launchers, so this wouldn't work very wel for a generic binary build to distribute.

If you'd like to see a hardened build, then that would be the perfect reason to make a contributed 3rd party build yourself to add to the Pale Moon ecosystem. We would certainly welcome such an effort :smile:

**Comment by MingcongBai** [comment]
Well, but this is like a `configure` option that you can enable or disable, it wouldn't hurt to include this option that **will** improve binary security would it?

**Comment by wolfbeast** [comment]
Why do you think we need to start adding configure options for compiler-specific optimizations? That's just needlessly increasing the complexity of the configure script. If we do that, then we may as well start adding configure options for all other GCC and MSVC flags...

**Comment by luchr** [comment]
Thank you for adding `MOZ_PIE` with commit 3d8ce1a11a7347cc94a937719c4bc8df46fb8d14.
