### ISSUE TITLE
Does not disable glib slice allocator with glib >= 2.35. Startup critical error. 

### ISSUE THREAD

**Issue by themusicgod1** [MoonchildProductions/Pale-Moon#39]
FF mozilla bugzilla ticket : https://bugzilla.mozilla.org/show_bug.cgi?id=833117 

It's listed as a a "won't fix" bug in FF/ESR 24, and there's no sign of a fix in any future version of firefox, yet nevertheless: a critical error message is displayed in Pale Moon on linux consistently on startup.  Nothing high level in particular fails, but as per the bugzilla thread, the reason this is happening at all is that Pale Moon is using a debugging method in the glib ( g_slice_set_config() ).  If glib isn't providing a ready method for what Pale Moon needs, that may be at root what's causing this - - but there's got to be a better way than throwing critical errors at the users. 

"(process:25581): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed"

People have and it looks like they are going to continue to confuse crashes with this issue (Because it is a "critical" error) and will try to report it as a crash (when it's not).

I can reproduce on Ubuntu 15.04 / Version: 25.4.0a1 (x64), but as you can see in the original thread there's a variety of different Linux-related environments that this is reproducible in.

**Comment by trav90** [comment]
I too can confirm on Manjaro. Something to think about: how many users actually start Pale Moon from the terminal? And even if they do, (in my experience) most people will ignore any error messages they get as long as the software works as expected for them.

Also, I looked through threads and searched on the Pale Moon forums for people who were confused by this "critical" error, and didn't find anyone who had asked about it.

Please, don't get me wrong; I'm not saying that this shouldn't be looked at or fixed, but I don't think that it is currently a huge issue. On that note, there was a patch posted on the bugzilla number you mentioned; have you tried applying that to Pale Moon and see if that resolves it?

**Comment by wolfbeast** [comment]
There is no easy way to determine glibc version early in the startup where this happens. Disabling the slice allocator is needed for mozalloc (jemalloc) on Linux and also on BSD operating systems. If it's not disabled, **it's not critical** and will simply use a sub-allocator instead. Downside is that that tends to increase fragmentation.

Removing the error would cause inefficient (and possibly broken) memory allocations on glibc < 2.35

It's one of the problems when dealing with an OS that is not uniform and comes in many different flavors.

**Comment by wolfbeast** [comment]
Looking at this some more, I'd even say that this is a bug in GLib, instead.

1. They don't allow memory allocators to be disabled anymore
2. They still allow the call to the config function, however, and it succeeds
3. They throw an error when the available config function is used to try and do something that is no longer supported. There is no way for the caller to know it errored (void function) or to suppress the output.

From the browser side, the call to config succeeds, because it's available. There is no way to check for the error because it is thrown as part of a successful call. The actual error is thrown by GLib, not the browser, so will be thrown regardless whenever the otherwise successful call is made.
GLib should remove the assertion, or should make the callee be able to be silenced if the caller can get direct success/failure feedback.

**Comment by themusicgod1** [comment]
@trav90 likewise, it's mostly an error message but it seems to have the smell of deeper issues.   @wolfbeast has gone more in depth into this.  The problem seems to stem from the fact that GLib treats the config function as a deprecated, debugging function, and PaleMoon/xulrunner are not using it that way at all.  That said, it seems to be that it's not using it that way because the functionality to do what PaleMoon needs (especially on all platforms) isn't actually present without using it.  Ie this is a design-level problem involving GLib.  If the problem is on their side, I can pursue that, if from the PM perspective the bug is on the GLib side.

https://bugzilla.gnome.org/show_bug.cgi?id=687763 Seems to be the GLib bug for this issue.

**Comment by wolfbeast** [comment]
Firefox/Pale Moon isn't the only software suffering from the same erroneous error, judging by the search results.
The problem seems to be that it wasn't fully deprecated. Internally, the use of it was deprecated and some functions have been made non-functional (including the one used by Pale Moon), and when trying to use the function it will throw an assertion from an internal test that fails after the removed function was called.

The problem is that for Pale Moon (and Firefox, and anything else wanting to use jemalloc) to work correctly, it *must* be allowed to disable the slice malloc allocator in GLib. The only way to do that is/was through the now half-deprecated "debug" function. It wouldn't be too terrible of a problem (although still causing jemalloc to not work fully!) if the function actually didn't trip over *itself* when someone tries to do this and throwing a critical error that can't be silenced (and will be misinterpreted by users if there's another error). Basically, anyone who sees this now will not be taking full advantaged of Pale Moon's built-in memory allocator, and I'm not even 100% sure if this half-enabled state would cause problems of its own or not. You may have to build without --enable-jemalloc for a sane allocator state on gcc 4.9 until this is remedied.

**Comment by wolfbeast** [comment]
As pulled from the bugzilla bug and patched by @trav90 the browser will now set the environment variable temporarily while initializing the lib when jemalloc is in use. commit 070058f761640d00c3d1c932e192359e197015a2 fixes this issue.

Needs a dev doc note, if you are compiling the browser yourself on Linux 3.*, you should not compile with jemalloc and use Linux's malloc() implementation.
