### ISSUE TITLE
Thanks for deleting my account, palemoon author.

### ISSUE THREAD

**Issue by whydoyoudeleteme** [MoonchildProductions/Pale-Moon#413]
https://trac.torproject.org/projects/tor/ticket/18697

**Comment by whydoyoudeleteme** [comment]
@MoonchildProductions .

**Comment by whydoyoudeleteme** [comment]
@wolfbeast @Axiomatic- @MoonchildProductions https://trac.torproject.org/projects/tor/ticket/18697

**Comment by wolfbeast** [comment]
Excuse me but we did not do anything. In fact, I was about to respond to your issue only to find it had vanished. I assume GitHub removed your account.

**Comment by wolfbeast** [comment]
For the record, the original issue content as I received in my mailbox was:

> I'm using Palemoon and your mail client for years.
> And nowadays, you decided to use "Cloudflare". Now I can't access to your website or forums.
> 
> I'm sick of Cloudflare's "One more step". It's just no good.
> You're losing many people, including me, to try out/download/wanna-help your software.
> 
> Many people who see "One more step" will simply stay away from the website.
> I'm writing this issue to ask you what you think about this.
> 
> If you really don't care about us, fine. Firefox it is.
> If you wanna help, please try to do one of those options:
> 
>     Provide alternate way to download your software. Sourceforge or Github.
>     Change your Cloudflare setting to accept Tor.
> 
> If you don't do one of them, I think Palemoon does not honor the anonymous connection
> and helping mass surveilance. We are waiting for your reply.
> 
> FYI
> https://trac.torproject.org/projects/tor/wiki/org/doc/ListOfServicesBlockingTor
> https://blog.torproject.org/blog/call-arms-helping-internet-services-accept-anonymous-users

**Comment by whydoyoudeleteme** [comment]
Oh, sorry for accusing you for this. Yeah, I think Github delete my account. Duh.
I shouldn't login to this account because github will delete my account(this) again, so I won't reply in the future(but still reading it).

So...

>  I was about to respond to your issue

I would like to read it. thanks.


P.S.
Your websites are now on the lists.

**Comment by wolfbeast** [comment]
> Your websites are now on the lists.

We don't have anything on our websites that would require the use of anonymizers, neither TOR, nor disposable e-mail, nor other anonymity services. This makes this a one-sided argument where we only see the negatives involved with allowing such services: abuse, spam and trolling.

As such, I don't care if it's publicly listed on the tor "blocked" lists or not. Part of the issue is that we do, out of necessity, use Cloudflare. Their policies in part dictate our policies. If CF's policies change regarding TOR, then you may have better luck accessing our web assets through it. However, do expect the forum to be more aggressive in blocking TOR visitors.

**Comment by whydoyoudeleteme** [comment]
I don't care about your forums, sure, I understand you want to use CF to block posting,
but Palemoon's internal updater/manual update are blocked by Cloudflare.

Can't you just turn off security only for downloading?

In Cloudflare - Pagerule webpage, there's an option to add exception.

URL /*.exe
Action Security Low

**Comment by whydoyoudeleteme** [comment]
> Then you can expect sites to not trust you.

You don't have to trust me. I don't trust you either.
You can force me not to post anything on the forum(POST method),
but blocking me from downloading/updating your software(GETting method)
is just cruel, isn't it?

**Comment by whydoyoudeleteme** [comment]
More specifically:

http://relmirror.palemoon.org/release/*
http://relmirror2.palemoon.org/release/*

What's the point of using Cloudflare on Software distribution server?
They are NOT forums' server.

**Comment by wolfbeast** [comment]
The relmirrors have been targets for some nasty attacks which is why they were put behind cloudflare.
I've disabled the CDN for now on them, but if attacks reoccur, i will protect our servers.

**Comment by wolfbeast** [comment]
Also, the internal updater MUST be behind CF because we need the CDN capabilities of the CF network for that, unless you think we should overload our servers with direct requests when there's an update just so TOR users can update "anonymously".

**Comment by chaoskagami** [comment]
Another question: shouldn't you be running Linux, downloading source tarballs from Github, doing integrity checks and building those? You shouldn't be using automated updates let alone Windows. That's insecure for multiple reasons, which I won't get into. I'm pretty well versed with tor, since I use it on occasion.

@wolfbeast - Maybe it'd be possible to mirror binaries on the Github releases page? Other projects put binaries on Github. Just a thought.

**Comment by wolfbeast** [comment]
We already have mirrors. Downloadcrew, FossHub, etc.
People CAN use those.

I'd rather not host binaries on GitHub.

**Comment by chaoskagami** [comment]
My apologies. I'll be more careful in the future. :(

**Comment by wolfbeast** [comment]
I'll send you a note about our internal updater - it's more secure than you seem to think.
