### ISSUE TITLE
Fix S4E copyright attribution

### ISSUE THREAD

**Issue by SparkyBluefang** [MoonchildProductions/Pale-Moon#460]
statusbar@palemoon.org was forked, and has since received updates, from status4evar@caligonstudios.com. However I can not find evidence of any original copyright notices or attribution.

For source files that originated solely under the older MPL 1.1/GPL 2.0/LGPL 2.1 license, I don't see any evidence of the copyright attribution being included "in a single file for the code as a whole" or "in the source tree of Pale Moon in the relevant directory when released as integral part" (Re: About licensing and compatibility of S4E 02/16/2014 05:55 PM).

S4E was re-licensed solely under the terms of the MPL 2.0 on Feb 17, 2014, so any changes cherry picked since then would have been covered by the updated license. The MPL 2.0 does not permit any modification to copyright notices unless they are factually incorrect. https://www.mozilla.org/en-US/MPL/2.0/#notices

However, I will say, for the record, that I do not agree with the original decision to remove the per-file copyright notices when statusbar@palemoon.org was re-licensed under the MPL 2.0. Each of the MPL 1.1/GPL 2.0/LGPL 2.1 have clauses that derivatives must conspicuously publish an appropriate copyright notice and disclaimer of warranty.

**Comment by wolfbeast** [comment]
Any software released under the MPL 1.1 may be re-licensed under the MPL 2.0 by a third party with no requirement to keep GPL/LGPL licensing. As such, consolidating the copyright notices to a generic MPL 2.0 header in each affected file is fine, and merging your code with an otherwise MPL 2.0 licensed application is also no problem (see "larger work").

I do notice that your name isn't listed in credits which it should. I'll fix that immediately.

**Comment by wolfbeast** [comment]
I've gone the extra mile and added optional licensing text for clarity in addition to listing you as an author of part of the code base (my apologies - I really thought I had already added you to the authors list but apparently I was mistaken).

It's *optional* licensing text because the code in question does fall under the MPL 2.0 and apart from generic credit to the code base as a whole, the MPL 2.0 does not require explicit copyright in each and every file. Since you asked though, I'll be more than happy to credit where it's due and state the disclaimer redundantly in the part of the code base that is derived from your work, but the licensing text is there for historical reasons only since it was re-licensed -- even more so it was relicensed by you, yourself, being the initial developer, making all code MPL 2.0 even pre-fork.

**Comment by SparkyBluefang** [comment]
The MPL 2.0 does not require explicit copyright in each and every file, however it does forbid you from removing it if present.

As I linked https://www.mozilla.org/en-US/MPL/2.0/#notices
```
3.4. Notices

You may not remove or alter the substance of any license notices (including copyright notices, patent notices, disclaimers of warranty, or limitations of liability) contained within the Source Code Form of the Covered Software, except that You may alter any license notices to the extent required to remedy known factual inaccuracies.
```

So I don't appreciate the implications that I am somehow unduly burdening you by asking you to correctly replicate any copyright notices from the original sources. Remember, source licenses give you permission to copy and modify a copyright work. If does not give you permission to disregard the copyright altogether.

**Comment by wolfbeast** [comment]
I've never disregarded your copyright and have always clearly stated you as the Initial Developer of this code, although maybe not at all times in the locations you expected them. The one who's being snarky is you, Matt.

I'll update the license text in the relevant sections of the repository.

**Comment by SparkyBluefang** [comment]
Thank you for making the requested changes.

I apologize for being overbearing, but I take copyright and licenses extremely seriously, especially when derivations are being monetized. I hope you can understand how statements like "the original source code was re-licensed ... under the MPL 2.0, making this license statement optional." can rub someone the wrong way when reproducing such notices are not optional under the GPL 2.0, LGPL 2.1, MPL 1.1, or MPL 2.0 if they existed in the original code.

**Comment by wolfbeast** [comment]
I take copyright and licenses just as serious.
Like I said, you've always been given due credit, and I apologize if it wasn't in the manner that the license demanded. I should have paid closer attention when integrating that the previous notice (that was present when it was an extension format) was maintained in the location it should be.

As an aside, stating any previous license when software has been re-licensed *is* optional. It's historical context at most, and I wanted to clarify that the license, even though stated, would no longer apply to the actual code living there. But I guess there's such a thing as trying to be too clear?
