### ISSUE TITLE
GitHub JavaScript issues when editing issue metadata

### ISSUE THREAD

**Issue by stevenschlansker** [MoonchildProductions/Pale-Moon#462]
GitHub has been breaking on Pale Moon (tested on Mac 26.3.2) with various JS problems.  It looks like it is constructing URLs to redirect to, but somehow some object is getting serialized out instead of constructing a URL properly.

For example, go to any issue you have rights to edit, and attempt to assign it.  The "Assign up to 10 people to this issue" box comes up, but the list of possible assignees never loads.

![screen shot 2016-07-21 at 10 19 16 am](https://cloud.githubusercontent.com/assets/129097/17032214/f460fe2a-4f2c-11e6-8899-e91ed7608af4.png)

In the console log, you see the problem:

![screen shot 2016-07-21 at 10 20 02 am](https://cloud.githubusercontent.com/assets/129097/17032221/f9f0b768-4f2c-11e6-9e88-0de95ee3e60f.png)

Note how the url shows as `https://github.com/jdbi/jdbi-docs/issues/%5Bobject%20URL%5D`; somehow `[object URL]` is getting used rather than whatever the URL was supposed to be?

I tried to track it down a bit further to see if they made any obvious coding mistakes, but unfortunately the JavaScript is minified, so it's nearly impossible to debug :(

**Comment by wolfbeast** [comment]
I'm aware of this and am already in touch with GitHub.
The root cause is the "empty string passed to getelementbyID" error, I think, which then results in the incorrect URL. Since it's all minified it's guess work and only github can give more details. This was NOT an issue until this weekend, and even then it was intermittent at first. It's been a change on github -- their initial response was (predictably) that they "don't support any but the very latest versions of the 3 major browsers" but I've asked them for details to see what the root cause is.

I'm having to resort to using a different browser myself for labeling and assigning right now which is a PITA. I see no reason why they would need to change the behavior it had before either.

**Comment by wolfbeast** [comment]
I've been in touch with a FE engineer of GitHub who pointed out the core issue with this, which is the fact that the new URL API implemented since March apparently doesn't serialize when the object is passed to a toString() (either explicitly or implicitly by conversion). This _should_ have worked and I implemented this properly in the API, but as it turns out Mozilla's WebIDL implementation we have is only half done. For a core interface technology I'm really surprised about that. As of today this is still an assigned but not fixed bug at Mozilla (4 years old now)

I'm able to work around this by manually stringifying the object.
