### ISSUE TITLE
Keep selected text highlighted when losing focus

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#50]
Reference bug: https://bugzilla.mozilla.org/show_bug.cgi?id=141007
Relevant thread: https://forum.palemoon.org/viewtopic.php?f=29&t=7781

It should not be too difficult to fix but the problem is finding the exact location in the FE/editor code to fix this.

**Comment by janekptacijarabaci** [comment]
I cannot simulate it (i.e. v25.3.0). Is it still true?

**Comment by Lorienna** [comment]
<dl><dd><b>Steps to reproduce:</b><br><br>
<b>1.</b> Type in or paste a text into the "Leave a comment" form below, but don't submit it.<br>
<b>2.</b> Select that text of yours.<br>
<b>3.</b> Click elsewhere outside that form to draw the focus away from it.<br>
<b>4.</b> See that the selection has seemingly disappeared.<br>
<b>5.</b> Middle-click or right-click somewhere within the "Leave a comment" form containing your text.<br>
<b>6.</b> Discover that the selection has actually been there all along.</dd></dl>


#


<dl><dd><b>FYI:</b><br><br>
On earlier FF builds for Windows (where this has been tested) inactive selection used to become grey rather than invisible when a spelling mistake was being underlined by the spellchecker:</dd></dl>

* <b>Last good:</b> [3.0a6pre (2007-06-20)](https://archive.mozilla.org/pub/firefox/nightly/2007/06/2007-06-20-04-trunk/)
Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9a6pre) Gecko/20070620 Minefield/3.0a6pre

* <b>First bad:</b> [3.0a6pre (2007-06-21)](https://archive.mozilla.org/pub/firefox/nightly/2007/06/2007-06-21-07-trunk/)
Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9a6pre) Gecko/20070621 Minefield/3.0a6pre
