### ISSUE TITLE
Trouble with opening some Facebook links

### ISSUE THREAD

**Issue by xbeyond1** [MoonchildProductions/Pale-Moon#615]
Seems that when opening some links of Facebook posts, Pale Moon starts acting a bit bizarre: it opens the picture in post in a separate window and then closes it, and then opens it again.

The link I tested this with: 

https://www.facebook.com/arminvanbuuren/photos/a.418329438315.197399.25498833315/10153964290048316/?type=3&theater

Pale Moon 27b2 x86 on Win 7 Ultimate x64

**Comment by wolfbeast** [comment]
I'm unable to reproduce this on current trunk. Facebook opens the page, then pops the theater viewer over it. This is likely more Facebook weird scripting going on -- you may be seeing the built-in pop-up blocker in action if Facebook first tries to open it in a pop-up window.

**Comment by xbeyond1** [comment]
Hmm... I tried opening the link in Chrome and it's working fine. I've also encountered this problem with some other posts (I cannot link the latest, since it's private), but this is definitely a recurring issue on my end.

**Comment by wolfbeast** [comment]
Apparently Facebook does A/B testing based on account, so what happens on your account may be different than what happens on someone else's account. They ARE messing with the "theater mode" code the past 2 weeks or so, causing trouble. All of this is however on Facebook's scripting side... You should probably complain to them that this behavior is bizarre. like I said it _sounds_ like it tries to open a classic pop-up window, for some reason; that fails because of the pop-up blocker, and then it tries to do it differently, or something along those lines.

**Comment by schmurtzm** [comment]
Same problem here with palemoon 27.0.3, tested with x86 and x64 version and with a new fresh profile.

The test link used to reproduce it is the same than xbeyond1 :
https://www.facebook.com/arminvanbuuren/photos/a.418329438315.197399.25498833315/10153964290048316/?type=3&theater

The facebook page is opened, then a frame is launched like in the screenshot below : 
![palemoonproblem](https://cloud.githubusercontent.com/assets/7110113/22028709/5ec8f7a2-dcd8-11e6-9350-e1919ea02c8a.jpg)

Suddenly this frame is closed and the entire page is reloaded, the frame is loaded again and so on.

OK may be it's a problem with facebook code but it's not working only with Palemoon...

**Comment by wolfbeast** [comment]
There is nothing we can do about this, since it is a problem purely in Facebook's scripting. It is unknown why it trips over our ID and feature set, and reverse-engineering Facebook scripting is plainly impossible.
Please report this bug to Facebook.
