### ISSUE TITLE
OS X: Personas kill the titlebar

### ISSUE THREAD

**Issue by Lootyhoof** [MoonchildProductions/Pale-Moon#623]
On OS X (using Tycho) it would appear that using a persona kills the titlebar, including caption buttons.

![OS X](http://i.imgur.com/xnqsAen.png)

This _appears_ to be due to [625989](https://bugzilla.mozilla.org/show_bug.cgi?id=625989) (with additional back-end work having been already done in multiple dependant bugs), however applying this doesn't seem to restore the caption buttons (and in fact kills them entirely). I'm not sure where caption button-specific work lives regarding the required bugs, unfortunately (though some of the dependant bugs on this one look promising).

I'm afraid someone more familiar to OS X may need to look into this one.

**Comment by wolfbeast** [comment]
Caption button specific code lives in `/widget` in the source tree, split up per OS.

**Comment by graciecat** [comment]
Confirmed that this is still an issue in PM 27.6.2 unofficial build for Mac OS

**Comment by wolfbeast** [comment]
Is this still an issue in PM 28.0.0 prereleases, if Mac builds are available?

**Comment by SpockMan02** [comment]
Yes.
<img width="1440" alt="screenshot 2018-06-12 18 43 56" src="https://user-images.githubusercontent.com/11634417/41325728-becb3266-6e70-11e8-9bad-c650f817ae16.png">
I'm sorry I didn't get back on this earlier, I've been doing other things and couldn't install any "themes" from AMO at first.
FYI: The `(Pale Moon)` at the end of the default AMO UA override needs to be removed, otherwise personas are uninstallable (it just tells you to download Firefox).
