### ISSUE TITLE
Misaligned caption buttons on tweaked Windows 10 UI

### ISSUE THREAD

**Issue by rjbprime** [MoonchildProductions/Pale-Moon#627]
Hi all,

I am running Windows 10 x64 version 1607, testing 27.0.0b2 (x64) (2016-10-08). The three buttons in the top of the window (Minimize, Maximize, Close), are glitchy, in that when mouse over of the close button, it shows a much larger button overlay, that takes up roughly 1.5 times it's normal size. This also occurs to the other two buttons, and pushes them to the left. Only the Close button has an actual icon, the other two have an overlay, but no actual icon, when mouse over. Using PM with a clean profile. Pale moon 26.5.0 works fine in this regard.

**Comment by wolfbeast** [comment]
Are you using non-standard system font sizes?

**Comment by rjbprime** [comment]
Yeah, I currently use WinAeroTweaker, to change some things. Going back to Pale Moon 26.5.0, it doesn't have this error, but I remember when I first used Windows 10 and Pale Moon, when Win10 first released, that it had this error as well. And I didn't even know about WinAeroTweaker back then.

Any Ideas, or is it just user error, in that I'm using WinAeroTweaker?

**Comment by wolfbeast** [comment]
Well, the tool is likely the direct cause :smile:

The problem is that for the custom window header that's needed for having the Pale Moon application button, we have to re-paint the title bar area ourselves. We have to use some dirty tricks to work around things on Windows 10 to keep things similar to native and deal with the accent color at the same time, including "faking" the caption buttons with our own overlays of matching sizes. If you tweak the underlying controls, then it will no longer match.

A possible workaround would be to switch to using the menu bar instead of the application menu, since we no longer draw the custom header in that case.

**Comment by rjbprime** [comment]
Using Version: 27.0.0b3 (x64) (2016-10-25) on the same laptop, the non-menu bar window framing does the same thing, but when using the menu bar, it's all good.

The options I am using that may be the culprit in WinAeroTweaker are: Enable Aero Lite (Default); Enable Colored Title Bars; Icon spacing of 42 x 42, with the icons themselves quite small; I am using Noto Sans Regular size 7 font on the icons, menus, message boxes and status bar fonts.

System fonts have been changed to Noto Sans. Window borders are set to 1, with padding set to 0; Title Bar height is set to 12 px, and the font to Noto Sans size 7. Scroll bars width and button size are set to 10.

Those are the Appearance and Advanced Appearance changes I have made. I wouldn't think the other options in the app would affect it.

With these settings, Pale Moon 26.5.0 had no issues, but then again, I changed it to menu bar and compact theme. Any idea if this could be looked at? I know that not everyone would customise their Windows installs as much as I have, but I like having maximum screen estate.

**Comment by wolfbeast** [comment]
It doesn't matter what your specific settings are - Any change to the title bar area metrics making them different from default system metrics will cause this effect. If you want to tweak your UI this way, then you'll have to use the system-supplied window-frame, meaning you have to use the menu bar and not the AppMenu. There is no way around this on the browser side as it is drawn because the browser can't easily get these metrics from the active window.

This is something that might be solved by way of solving #160 - although that will inherently mean that your aero tweaks won't be honored by Pale Moon.

**Comment by HonoredMule** [comment]
I get that Pale Moon is forced to make a compromise between two incorrect behaviors here (failing to match window theme vs failing to match window metrics).  But one issue is with aesthetics/consistency and the other is a real usability problem.

So mark me as a vote in favor of any titlebar behavior/content overrides being an all-or-nothing affair, ensuring that the titlebar is above all consistent with itself.

**Comment by Lootyhoof** [comment]
Matching window metrics for non-default configurations isn't achievable at **all** on Windows 10 though.

Please understand that with the way the caption buttons must be drawn (and the way we can understand how the system is currently setup theme-wise) we only really have two options: draw the window background and caption buttons ourselves (which we did, but this ignored the accent colours and custom system themes entirely), or leave the window background transparent (showing the system caption buttons that aren't really "there", so to speak) and overlay these non-functional caption buttons with our own (on hover, to achieve the illusion that the system-drawn ones are being used).

**Comment by evan-king** [comment]
> which we did, but this ignored the accent colours and custom system themes entirely

Right, and in that case, were not the titlebar's UI element behaviors consistent with their own appearance?  They just look completely different from any theming customization (metrics or colors).  But shoving stuff into the titlebar is already inconsistent with standard window controls and that was the point to push back and say it "can't" be done were that actually so.

However, Chrome puts tabs in the titlebar and respects system theme behavior (both colors and metrics) so clearly it is _not_ impossible.  It's probably as simple as reading the appropriate registry entries that control window metrics.

But again, completely disrespecting the windows theme and doing your own fixed-behavior titlebar is much more reasonable than trying to match appearance and being misleading with the result.  Since the workarounds are worse than the problem, it's very tempting to roll back to a version of Pale Moon that didn't make the ill-fated attempt at respecting win10's theme.

**Comment by HonoredMule** [comment]
> which we did, but this ignored the accent colours and custom system themes entirely

Right, and in that case, were not the titlebar's UI element behaviors consistent with their own appearance?  They just look completely different from any theming customization (metrics or colors).  But shoving stuff into the titlebar is already inconsistent with standard window controls and that was the point to push back and say it "can't" be done were that actually so.

However, Chrome puts tabs in the titlebar and respects system theme behavior (both colors and metrics) so clearly it is _not_ impossible.  It's probably as simple as reading the appropriate registry entries that control window metrics.

But again, completely disrespecting the windows theme and doing your own fixed-behavior titlebar is much more reasonable than trying to match appearance and being misleading with the result.  Since the workarounds are worse than the problem, it's very tempting to roll back to a version of Pale Moon that didn't make the ill-fated attempt at respecting win10's theme while the menu bar is off.

**Comment by wolfbeast** [comment]
**We are not Chrome** and our way of drawing windows and elements in the UI is _vastly_ different. You cannot compare what Chrome does with what we do. Our UI is built up with XUL, JS and CSS. It is not native to the OS no matter how close the default theme may look to being native. Considering the way Chrome handles and builds, I gather they actually use native windows objects and controls for their widgets, but for a Mozilla-platform based browser, that is simply not part of its design.

Because of this design, we have the customizability we do in the UI. Chrome does not.

There are no shortcuts or simple solutions here.
The solution is perfectly fine for anyone who doesn't insist on doing things that are not part of the Windows 10 OS. It doesn't cover all possible scenarios, because it can't. Our users have clearly chosen (when asked) that we should integrate and look like system-native with our UI as much as possible, and that is what we do.
Completely disrespecting the Windows theme will make the browser by definition _not_ do what our users want from it.

**Comment by mattatobin** [comment]
I would like to point out that if you use anything but default on Google Chrome it will skin the titlebar as well to match the browser's excuse for a theme.

![untitled](https://cloud.githubusercontent.com/assets/3889475/20375017/5e5731f8-ac4a-11e6-930b-2a49c6e9c9fc.png)

**Comment by HonoredMule** [comment]
I'm sorry you feel the need to talk down to me regarding this, but I wonder if it comes from the same place as copping out by claiming your users prefer a _broken, incomplete_ native UI emulation (as opposed to just "native appearance" which I believe we can agree is ideal to the majority) or that somehow changes to Windows 10's theme/configuration is not part of Windows 10.

I'd be a lot more understanding if you'd just be honest about the reasons a fix won't happen (cost-benefit, number of users affected, need someone with the knowledge to read and interpret the contents of HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics, not enough coding infrastructure to support that degree of OS-specific logic in place, etc.) rather than shifting blame to a technology stack which is most accommodating whatever rendering details you care to specify, or acting like what to specify is completely unknowable/unchangeable because it's not default values.

There's no need to be defensive.  No one expects you personally to be perfect or to have the time and resources to implement everything perfectly, especially if you have the transparency to admit it.  You'd have retained a lot more of my respect doing that instead of blaming your quite capable tools.

I'm just one of your users, expressing the kind of opinion that apparently informs and may influence your decisions.  I'm just not sure how, when you seem more focused on justifying a bug, so rather than waste any more of our time looking for a straight answer, I'll instead start investigating an _actual_ workaround via userChrome.css.

**Comment by wolfbeast** [comment]
Nobody is talking down on you. Sorry you feel that way.

Instead, you seem to be insistant on being very aggressive in complaining about the way we do things and have done thing by design ever since Netscape, resulting in a UI as desired by our users. 
We're not shifting blame here. I know for a fact the current Windows 10 solution is rather hack-y, but for anyone who doesn't insist on hacking their Windows UI to expose the incompatibility, this solution works and is "good enough". With how Microsoft has been tinkering with the UI and how it works with every major update since launch of Win10, we needed a **working** solution before looking at a **better** solution.

If you think you have a **better** solution or want to help us **create** a better solution, then please, **by all means, jump in and help!**

**Comment by wolfbeast** [comment]
Since we've re-done the Windows 10 styling and always draw our title caption buttons on it now, this should not longer be an issue.
