### ISSUE TITLE
Allow to run extensions with embedded SDK

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/Pale-Moon#649]
Please add an ability to prevent the disabling of extension, based on presence of files harness-options.json or package.json in xpi archive. This will allow to run extensions with embedded copy of SDK, who are targeted the both Firefox and Pale Moon 27, from the single installation package.

The proposed option for install.rdf: < em:palemoon27Compatible>true</em:palemoon27Compatible>. In case this is set, the extension should not be disabled, even if it contains the files, mentioned above.

Since this option intended to be set by developers after appropriate modifications and checks, no negative impacts on compatibility logic aren't expected.

**Comment by mattatobin** [comment]
No.

**Comment by JustOff** [comment]
Could you please provide any arguments? Without such option you force the devs to provide two separate installations for FF & PM, even if the extension itself is compatible with both browsers and has a copy of SDK inside.

And, btw, Moonchild [wrote](https://forum.palemoon.org/viewtopic.php?p=96204#p96204): 

> If you don't want to re-write specific things, please understand that anything in our code base is open source and you can copy it to your extension if you need it, you know, in the spirit of the way the SDK was originally envisioned (to have it included in extensions that built on it).

**Comment by mattatobin** [comment]
I updated previous post.

**Comment by JustOff** [comment]
There are many libs that aren't so good, the SDK is only one of them, but should we block them all, using file matching patterns? I supposed that SDK-based extensions were disabled only to avoid any confusions for users. None is preventing to rename SDK files and make repack that will work, but it's simple unnatural, isn't it?

**Comment by wolfbeast** [comment]
If you want to embed SDK files in a custom extension, then you still cannot use the SDK-style loading and initializing. I indicated that it is possible to copy _parts_ of the SDK to your XUL/overlay/bootstrap extension so you don't have to reinvent the wheel. Nothing else.

SDK extensions aren't compatible and won't be. The bits internally used for devtools in the source tree will likely be made conditional or completely go away over time. Don't rely on it. The necessity to block these extensions should be clear. If you rename things to make a custom extension then you are explicitly targeting Pale Moon -- that's a completely different story.

Closing this issue.

**Comment by JustOff** [comment]
I understand that this is unlikely will change anything, but nonetheless, just to be exact.

> If you want to embed SDK files in a custom extension, then you still cannot use the SDK-style loading and initializing.

I'm afraid you're wrong. I've the extension with SDK-style loading and initializing, using embedded copy of SDK, that works well under PM27. Nothing in its code was altered, except the bootstrap.js:

```
"use strict";

const { utils: Cu, interfaces: Ci, classes: Cc } = Components;
const rootURI = __SCRIPT_URI_SPEC__.replace("bootstrap.js", "");
const appInfo = Cc["@mozilla.org/xre/app-info;1"].getService(Ci.nsIXULAppInfo);
if (appInfo.ID == "{8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}") {
	const { require } = Cu.import(rootURI + "/jetpack/toolkit/require.js", {});
	const { Bootstrap } = require(rootURI + "/jetpack/sdk/addon/bootstrap.js");
	var { startup, shutdown, install, uninstall } = new Bootstrap(rootURI);
} else {
	const COMMONJS_URI = "resource://gre/modules/commonjs";
	const { require } = Cu.import(COMMONJS_URI + "/toolkit/require.js", {});
	const { Bootstrap } = require(COMMONJS_URI + "/sdk/addon/bootstrap.js");
	var { startup, shutdown, install, uninstall } = new Bootstrap(rootURI);
}
```
And this would work in Firefox too, if I didn't have to rename package.json to avoid disabling ...

**Comment by wolfbeast** [comment]
As you yourself stated though, you need to change the bootstrap if you want to do this. But then you are using a bootstrap init method, and not and SDK init method (which strictly dictates where these modules are located). Bootstrap works and will remain working. The SDK package method won't, because it implies that the generated bootstrap script be used as-is.

All of this is, however, besides the point. SDK extensions won't be compatible on the whole, because our FE is incompatible with what these toolkit modules and extensions expect. So, "allowing" this would create a support and quality nightmare, because they _will_ break; this _will_ reflect on the browser, because likely, the browser will break, too, if incompatible extensions are installed.

You're free to hack away on your own extension and browser, but I'm telling you right now beforehand that we will not take into account any extensions that hook into toolkit jetpack modules when developing, and it may at any point be yanked out from under you without warning.

**Comment by JustOff** [comment]
Thank you for spending your time for discussing my crazy wishes!

Believe me, the least I want to do harm to the whole project. This is why I still intentionally avoided the details about embedding SDK on the forum and tried to find some kind of official method here.

It's clear now (and clear why), that none of the ways will be ever accepted as official and all your warnings have been taken into account. 

At the same time, I hope I'll not break any rules if I'll share the way to run some of SDK extensions on PM27 (with all corresponding restrictions and warnings), cause I've been asked to do so.

**Comment by wolfbeast** [comment]
Feel free to share your knowledge, @JustOff :smile:

**The corresponding restrictions and warnings should however be made painfully clear**, yes. This should still be considered _hacking_, and we cannot and will not provide any guarantees that anything will work or keep working, or support for anyone running an SDK extension that has been hacked to make it to run with the toolkit modules. That includes all support, also for general browser use, because SDK-sourced extensions may break the browser if forced to run. The average user really should not attempt this.
