### ISSUE TITLE
'Download status button action' selections doesn't work (PM27)

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#700]
The 'Download status button action' selections doesn't do anyting (Tools > Status bar options > Download).
Clicking the button will show the new default download window (which I don't like at all) no matter what!

(Pale Moon v27.0.0,x64)

**Comment by janekptacijarabaci** [comment]
There are two different "downloads buttons" - do you use the "right" button?

But I have another problem:
![1](https://cloud.githubusercontent.com/assets/2373486/20560904/f4130d8a-b17b-11e6-8819-821e7bf0a542.png)

1. Status text is initially `null`.
2. After clicking to "Downloads" button (the original Downloads button) - the popup window is elsewhere.

**Comment by wolfbeast** [comment]
I tested this -- using the "download status" button, which is the status bar downloads indicator equivalent of the toolbar download button, making the selections in the status bar options window work as they should. I tested library and tab functions and they open the library and downloads tab, respectively.

If you have both indicators in your UI, the status bar one will be the priority anchor (by design); you should remove the one you don't want to use to have it be consistent.

In the customize window, the two entries are:
- `Downloads` - the default (panel) indicator as-used in Firefox.
- `Download status` - the status bar indicator which responds to the selections made in its options.

**Comment by wolfbeast** [comment]
Unless there's something specific that doesn't work as I said, this issue should be closed.

**Comment by THEtomaso** [comment]
Yeah, I figured this out a while ago, but forgot to post it here.
The settings are a bit confusing, that's all.
I posted some info here, in case anyone else wants it to work like I do:
https://forum.palemoon.org/viewtopic.php?f=3&t=14560/
