### ISSUE TITLE
about-dialogue: incorrect architecture info

### ISSUE THREAD

**Issue by MingcongBai** [MoonchildProductions/Pale-Moon#708]
When running Pale Moon 27.0.0 on PowerPC64, the about dialogue says that the browser was built for x64, which does not make sense as x64 really refers to x86_64 or x86 with 64-bit extension.

![snapshot7](https://cloud.githubusercontent.com/assets/5006263/20573245/8b4b1e5c-b174-11e6-8268-5dbce85d85f1.png)

**Comment by wolfbeast** [comment]
It will require a simple patch to adjust the aboutdialog XUL based on built architecture to correct this.
Should be self-evident :) patches welcome!

**Comment by MingcongBai** [comment]
https://github.com/MoonchildProductions/Pale-Moon/blob/5214789d035f4e4c08899a6e281116520f605ec6/browser/base/content/aboutDialog.xul#L45

But it is a simple 64-or-32 condition branch here... How could this possibly be simple?

**Comment by wolfbeast** [comment]
You can add more conditions to it! if x86/x64 only applies to certain architectures, then add a condition to use those terms for the applicable architectures, and use a "generic" term otherwise (32-bit/64-bit etc.)
The only "not simple" part of this is taking the time to research what conditions you need.

**Comment by MingcongBai** [comment]
Experimental PR opened here, https://github.com/MoonchildProductions/Pale-Moon/pull/710.
