### ISSUE TITLE
Alt+enter on awesomebar results doesn't switch to a new tab.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#717]
As reported on IRC, the following behavior (alt+enter on a result) no longer works in v27, and apparently worked in v26.*:

> "To turn off the "Switch to tab" option temporarily, press the ALT key while clicking on the page in the autocomplete list that appears below your address bar. This will open your page in a new tab instead of switching to an existing one."

https://support.mozilla.org/en-US/kb/awesome-bar-search-firefox-bookmarks-history-tabs

No errors thrown in the error console.

**Comment by Lorienna** [comment]
#### Steps to reproduce:
1. Open a non-private window.
2. Open some links in tabs.
3. In the location bar, start typing one of the opened page's title or URL address.
4. <i>Using the keyboard</i>, navigate the auto-complete list to highlight URL with <q>Switch to tab</q> indication.
5. Press `Alt`+`Enter`.

#### Actual result:
<dl><dd>PM 27 has switched tabs.</dd></dl>

#### Expected result:
<dl><dd>Apparently, PM 27 should have opened the link in a NEW active tab, overriding the switch-to-tab behavior.</dd></dl>

Repeat the steps above for `Shift`+`Enter` combination and see that the tabs have been switched again instead of URL opened in the CURRENT active tab regardless of switchability. See also <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=596485#c14">comment 14 for bug 596485</a>.

And yes, both key combinations work as expected on PM 26.5.0 (at least on Win7x64).



## Introduced by:
[Bug 754265](https://bugzilla.mozilla.org/show_bug.cgi?id=754265) - <q>Add a dedicated API to provide a final complete value different from the matching one</q>.
* Last good: [31.0a1 (2014-04-18)](https://hg.mozilla.org/mozilla-central/rev/7fe3ee0cf8be)
* First bad: [31.0a1 (2014-04-19)](https://hg.mozilla.org/mozilla-central/rev/582b2d81ebe1)
* [Pushlog](https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=7fe3ee0cf8be&tochange=582b2d81ebe1)
* [Changeset 179282](https://hg.mozilla.org/mozilla-central/rev/669dff46362f)



## Fixed by:
[Bug 1003461](https://bugzilla.mozilla.org/show_bug.cgi?id=1003461) - <q>Shift + Switch to Tab no longer respected</q>.

#### FF 32 central range:
* Last bad: [32.0a1 (2014-06-04)](https://hg.mozilla.org/mozilla-central/rev/668f29cd71b3)
* First good: [32.0a1 (2014-06-05)](https://hg.mozilla.org/mozilla-central/rev/51b428be6213)
* [Pushlog](https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=668f29cd71b3&tochange=51b428be6213)
* [Changeset 186568](https://hg.mozilla.org/mozilla-central/rev/035c1df29690)

#### FF 31 aurora range:
* Last bad: [31.0a2 (2014-06-06)](https://hg.mozilla.org/releases/mozilla-aurora/rev/fc83bcd4ed6d) + [files](https://archive.mozilla.org/pub/firefox/nightly/2014/06/2014-06-06-00-40-04-mozilla-aurora/)
* First good: [31.0a2 (2014-06-07)](https://hg.mozilla.org/releases/mozilla-aurora/rev/b982a8afab52) + [files](https://archive.mozilla.org/pub/firefox/nightly/2014/06/2014-06-07-00-40-02-mozilla-aurora/)
* [Pushlog](https://hg.mozilla.org/releases/mozilla-aurora/pushloghtml?fromchange=fc83bcd4ed6d&tochange=b982a8afab52)
* [Changeset 192953](https://hg.mozilla.org/releases/mozilla-aurora/rev/86894774b7e2)
