### ISSUE TITLE
Change default selection behavior of the address bar

### ISSUE THREAD

**Issue by elypter** [MoonchildProductions/Pale-Moon#731]
When you select text in a standard single line text field with a pointing device and you move the cursor out of the field then either the whole text left or right of the point where you began the drag'n'drop is being selected depending on where you move the pointer. the problem is that it bases the decision on whether the cursor is up or below the field instead of whether it is left or right. thats unintuitive and super annoying. it would be great seeing applications doing the first step of fixing this nightmare and palemoon could be an important candidate step because address bars are one of the text fields that are being selected quite often

**Comment by wolfbeast** [comment]
I'm not entirely sure I understand what you are suggesting. Please clarify.

**Comment by elypter** [comment]
open palemoon. move the mouse to the middle of the text in the urlbar and hold down the left mousebutton. then move cursor up and down out of the urlbar. watch the selection behavior

**Comment by wolfbeast** [comment]
It selects exactly as much or as little as you would expect based on horizontal mouse movement only. Vertical mouse movement is ignored because it is a single-line field.

**Comment by elypter** [comment]
unfortunately i cannot make a screenshot of the selection because pressing the hotkey removes the selection. maybe it behaves differently here on linux mint mate. could it be a gtk thing? i dont know how much control applications have over ui toolkits.

**Comment by wolfbeast** [comment]
It could be a GTK thing, in which case it would be a GTK bug treating a single-line element selection as-if it was a multi-line field. Not really much that can be done about that on the browser code side, I think.

**Comment by chaoskagami** [comment]
Since taking a screenshot is impossible, an explanation as I observe it.

Say the following text is in the URL bar: "https://github.com/MoonchildProductions/Pale-Moon/" If I click between the words "Moonchild" and "Productions" and drag up out of the URL bar, the text going to the beginning of the URL bar from click location is selected, e.g. "https://github.com/Moonchild", and conversely, dragging down selects to the end of the URL bar from click location, e.g. "Productions/Pale-Moon/"

I personally don't find this behaviour inconvenient. Rather, I like it - it allows quick deletion of the end of a URL and retyping. It's always behaved that way as far as I know, even before Tycho. I thought it was intentional.

**Comment by wolfbeast** [comment]
The behavior described was already clear. It has never behaved that way on Windows.
Dragging up or down on a single-line element should not behave as-if it was multi-line (which is the behavior you describe) -- convenient or not, if it behaved that way before, then that was a bug.
