### ISSUE TITLE
Regression: scaling/panning/zooming Chalkboard regression

### ISSUE THREAD

**Issue by win7-7** [MoonchildProductions/Pale-Moon#757]
https://testdrive-archive.azurewebsites.net/Performance/Chalkboard/Default.html

 scaling/panning/zooming of HTML5 drawing surfaces performance in this test has regressed because platform rebase doesn't have Pale Moon specific optimizations that were done previously.

**Comment by wolfbeast** [comment]
This is because we're now using a surface cache (needed for multiple scaling requests on a single page) and it indiscriminately caches all sizes of image (even if they are only going to be used once).

This does need to be improved though but we can't do it the same was as in Pale Moon 26 and before. So it's both a bug AND an enhancement ;)

**Comment by wolfbeast** [comment]
I've looked at several options, including a hard cap on image size and discarding faster or a lesser amount of the cache content, but none of it really improves this demo - we're hovering around 60s (on my system) irrespective of settings, and instating a hard cap actually makes it worse since it will create new drawing surfaces for each animation frame which is very expensive.

**Comment by wolfbeast** [comment]
I think I've found a way around the biggest bottleneck here. It'll still choke up here and there because of memory allocation and surface cache discards, but the zooming otherwise is fast now. This should cut the test time in half.

Probably as good as it's going to get, unless surface cache handling is changed.

**Comment by wolfbeast** [comment]
Considering this closed as "good enough" after commit a5b70c1b17a755412cb2649f56fb3377f1b35731

**Comment by wolfbeast** [comment]
Considering this closed as "good enough" after commit a5b70c1b17a755412cb2649f56fb3377f1b35731

**Comment by wolfbeast** [comment]
Ported to UXP.
