### ISSUE TITLE
Download bug (PM27)

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/Pale-Moon#775]
Sometimes when a download has finnished, Pale Moon v27.0.x fails to remove the .part extension.
This seems to happen when downloading multiple files simultaneously, like in this screenshot:
https://www.mediafire.com/convkey/2e80/8wh4hiwcvatyjxx6g.jpg

(Pale Moon v27.0.3,x64 / Win8.1Pro)

**Comment by THEtomaso** [comment]
After having encountered this issue many times now, I can say that it also happens when downloading single files.

**Comment by grumpygeek** [comment]
I have x64 on Win8.1(not-Pro) and I'm not seeing that.  I think the only times I've seen that is when a download doesn't finish for some reason like network connectivity issues.

**Comment by wolfbeast** [comment]
This is common if you have an anti-virus scanner that locks files on access to scan them. Pale Moon will then not be able to remove the .part after a download is finished because the file is locked in the file system until such time as the AV releases it. On the browser-side there's nothing that can be done about it.

In my multiple setups, I've never encountered this, but I also never use very aggressive AV that scans on-access or on-save.

**Comment by THEtomaso** [comment]
I don't have network connectivity issues, and my AV program is configured in the least aggressive manner possible (it only scans upon execution).
Also, on my system, I've removed 'Microsoft Windows Malicious Software Removal' and disabled both UAC and 'Windows Defender'.
In other words, things run pretty smooth.

**Comment by wolfbeast** [comment]
It is aggressive behavior from a programming point of view. It locks the file the moment it is written to immediately scan it, without giving the writing application a chance to rename/move/whatever. "lock and scan on write" is going to prevent Pale Moon from finishing file operations on it as-needed. This isn't a bug in the browser.
