### ISSUE TITLE
Restyle the permissions manager and make it more prominent

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#823]
Since we've been working on improving the permissions manager, we should also consider restyling it and hooking it up to the menu for easy discoverability.

- [x] Add title
- [x] Add a link to the AppMenu and classic Tools menu
- [x] Add/update icons

**Comment by janekptacijarabaci** [comment]
I leave it to you, or someone else :-)

**Comment by Lootyhoof** [comment]
Is this the permissions manager in `about:permissions`, the one in `Page Info`, or both?

**Comment by wolfbeast** [comment]
The permissions manager is the in-content all-site manager in `about:permissions`

**Comment by wolfbeast** [comment]
A quick look shows that it needs a title-heading, and less icons that are mere `?` icons. It could probably do with having its own, more elegant, icon set. The ones used now are very early-2000s. Not 2-tone/flat, though.

Categorization of the actual options and aligning controls would be a good improvement too.

**Comment by mattatobin** [comment]
Personally I would like to see this become more like SeaMonkey's Data Manager and spawned in a window.. In-content is terrible.. Though, that is my opinion.

**Comment by wolfbeast** [comment]
There has never been a XUL version of this so that would require to build something new from scratch entirely. That's really not very useful to invest time in right now. And in this case, I do think in-content at least works for its purpose.

**Comment by wolfbeast** [comment]
Actually, the in-content version of this is XUL -- I noticed when I got around to tinkering with it.
At the very least I'll add a title and hook it up to the AppMenu and classic menu. Icon restyling can be done later.

**Comment by wolfbeast** [comment]
Permissions manager is hooked up now and has a title to the page.
@JustOff - new label created for you to keep track of issues/PRs with string changes. Should make it easier for you.

**Comment by wolfbeast** [comment]
Basic icon updates done. It should be in an acceptable state now.

**Comment by JustOff** [comment]
> @JustOff - new label created for you to keep track of issues/PRs with string changes. Should make it easier for you.

Thanks!

> It should be in an acceptable state now.

I think that `about:permissions` page is too dangerous for common users. Mostly because two things are very confusing: 1) cookies correspond to strict urls, not to domains as on single page permissions 2) there are no easy way to find which permissions were changed on which pages. 

How about to hide the links to `about:permissions` from menu until special preference is set in `about:config`?

**Comment by wolfbeast** [comment]
Why is it too dangerous, exactly? I don't understand what the risk is.
The only difference with "Page Info" is that you don't have the "use default" setting. But if people go into the permissions manager, then they clearly want to control specifically what certain sites can or cannot do.

Cookies are the same, too. The cookie permissions apply to the specific domain, not strict URLs. I'm not sure where you get this idea.

**Comment by JustOff** [comment]
> Cookies are the same, too. The cookie permissions apply to the specific domain, not strict URLs. I'm not sure where you get this idea.

Sorry, but you are wrong. Thanks to @janekptacijarabaci for the [fixing proposal](https://github.com/MoonchildProductions/Pale-Moon/issues/1027) which seems solves this issue.

**Comment by JustOff** [comment]
> if people go into the permissions manager, then they clearly want to control specifically what certain sites can or cannot do. (or clear out specific per-site settings/data)

The problem is that `about:permissions` lists only 50 (hardcoded) most visited sites from history and there are no way to neither query all sites with modified permissions nor change the limit. Moreover, such behavior is completely undocumented so user can change permissions for some site and then have no easy path to find what's wrong. That's what I call dangerous.

**Comment by janekptacijarabaci** [comment]
> only 50

Yes. This should be configurable via user preference (IMHO).

**Comment by JustOff** [comment]
> This should be configurable via user preference

Probably it better to have control for this value from `about:permissions` directly, but I think it's not so important as ability to query all sites with modified permissions (and not only from history).

**Comment by wolfbeast** [comment]
So, why bring this up now after I put work in? The issue has been up on GitHub since january; you could have brought up your concerns sooner.

It's going to be an advanced feature anyway, and it does offer the kind of control Pale Moon users always ask for. I don't think hiding it behind a preference is going to help, because the whole point of this issue was to make it more visible to the users.
The list of domains is inevitably going to have and need entries that don't have page permissions attached because the permissions manager also includes cookies and passwords (and extends page info that way).

Having it list -everything- visited/with changed prefs is going to cause a lot of load on the user's system and isn't desirable. It already populates the list over time, but having a limit of 50 to stop at is reasonable...

What solution do you propose otherwise? What you want seems to require a complete rewrite of the logic behind the permissions manager... That is completely beyond this particular issue. If that's what you want to do then please open a new issue for re-implementing it, and make it blocking this issue, and I'll consider blocking access to it here through a pref.

**Comment by janekptacijarabaci** [comment]
> and not only from history

AFAIK: This function is internal only (in Permission Manager).

**Comment by JustOff** [comment]
> So, why bring this up now after I put work in?

Sorry, I didn't study the permissions manager in such detail until it appeared in menu right in front of my eyes. 

> What solution do you propose otherwise?

At first sight it seems rather simple to get the list of all sites with changed permissions via `nsIPermissionManager.enumerator` and use it as alternative or in combination with `getSitesFromPlaces()`. It will likely require only minor changes to the permissions manager and should not have a significant performance impact.

> If that's what you want to do then please open a new issue for re-implementing it, and make it blocking this issue, and I'll consider blocking access to it here through a pref.

Please let me think over it a little more. 

@janekptacijarabaci, what are your thoughts?

**Comment by janekptacijarabaci** [comment]
@JustOff 
e.g. public attribute `DBConnection`:
http://xref.palemoon.org/palemoon-trunk/source/toolkit/components/downloads/nsIDownloadManager.idl#240
http://xref.palemoon.org/palemoon-trunk/source/toolkit/components/places/nsPIPlacesDatabase.idl#24
which don’t exist in Permission Manager.

**Comment by JustOff** [comment]
@janekptacijarabaci 
Sorry, but I'm not sure I understand what did you mean in your last two comments ;) My point was to use [nsIPermissionManager.enumerator](http://xref.palemoon.org/palemoon-trunk/source/netwerk/base/nsIPermissionManager.idl#224) to get hosts from [nsIPermission](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIPermission) objects as additional source.

**Comment by janekptacijarabaci** [comment]
@JustOff 
I'm sorry, I understand it now :-)
https://github.com/janekptacijarabaci/Pale-Moon/blob/248229018be44049493f2e3ecb16959704afaa20/browser/components/preferences/aboutPermissions.js#L798

But I (personally) will not propose it as a PR now...

**Comment by JustOff** [comment]
> Sorry, I didn't study the permissions manager in such detail until it appeared in menu right in front of my eyes.

I spent some more time checking both `about:permissions` and `pageinfo>permissions` and found several significant shortcomings present in current implementation.

I opened `permissions.sqlite` and tested how the changes made using `about:permissions` and `pageinfo>permissions` are reflecting into the database. Here are my observations:

* `about:permissions` does not allow to set the permission for site if target value equals current default
* `about:permissions` does not allow to set the permission for site into 'use default' state
* Once set using `about:permissions` the plugin state can't be cleared from the database the same way
* `Forget About This Site` and `Remove Cookies` buttons immediately remove the corresponding data without any warnings or confirmation dialogs
* `about:permissions` does not provide the filter to display only sites with modified permissions that could help to easily find the culprit in case of any problems
* `pageinfo>permissions` has several mistakes in control logic which prevent to set specific permissions in case when global permissions for all sites differ from default values

> What solution do you propose otherwise? What you want seems to require a complete rewrite of the logic behind the permissions manager... That is completely beyond this particular issue. If that's what you want to do then please open a new issue for re-implementing it, and make it blocking this issue, and I'll consider blocking access to it here through a pref.

I'm not sure if I should open the separate issue for blocking this one, because I'm not going to work on it since actually I never used per-site permission control before and have no plans to start doing so.

I just feel I had to share my concerns in view of your intent to make permission manager more easily accessible to the users via main menu.

**Comment by wolfbeast** [comment]
> I'm not sure if I should open the separate issue for blocking this one, because I'm not going to work on it > since actually I never used per-site permission control before and have no plans to start doing so.

What a terrible attitude to have...

**Comment by JustOff** [comment]
Sorry, at least I try to be honest. With all due respect I see no reason to spend time to contribute to the feature I personally find almost useless.

**Comment by wolfbeast** [comment]
I hope you realize that if everyone involved here adopts that attitude, we may as well toss Pale Moon in the bin. Being involved in a community project with a diverse user base, especially on a browser that focuses completely on customization, that you CANNOT be selective in what you want to spend time on. This browser is not here for your individual enjoyment alone.

**Comment by wolfbeast** [comment]
I'm going to consider this closed. I did what i set out to do, which is expose the permissions manager. If it can use enhancements in the future, then that can be a separate issue; I'm not going to have that block this next release.
