### ISSUE TITLE
X11 primary buffer gets overwritten with autofilled URL text.

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#852]
Pale Moon 27 copies autofilled and auto-selected URL text to the X primary buffer. This would be because of a spec implementation on the HTML input element: `setRangeText(DOMString)`.
The problem here is that in the URL bar, these selection events are getting fires with content of a selection that is not user-initiated.

The new behavior in v27 is in fact more according to spec (and the URL bar is in essence an HTML input element) but should probably not dispatch the normal `setRangeText(DOMString)` event in the case of the URL bar auto-completing, because these selections aren't made by the user.

This can probably be fixed in the FE relatively easily.

**Comment by wolfbeast** [comment]
According to https://forum.palemoon.org/viewtopic.php?f=37&t=14648 this is still an issue...?
Can someone check and verify please?

**Comment by neneko-kun** [comment]
It was my forum post. I can  confirm that issue was resolved in git version i compiled but only for one straight forward use case.
And does not work in the following:
1) select text somewhere
2) open any search engine site to paste (this works with autocomplete and i have my buffer)
3) now i want to search same buffer in another search engine in the same tab, click to address bar to enter new site (you now have URL in your buffer and not previously selected text, although you didn't specially select any text)

**Comment by wolfbeast** [comment]
That is a completely different thing you are talking about and has nothing to do with this, also isn't what you described in the forum.
The issue you want to prevent is auto-select on focusing the address bar -- Pale Moon does this differently by default because the users in general has indicated they prefer this (aligning it with Windows' behavior). You want to toggle `browser.urlbar.clickSelectsAll` and `browser.urlbar.doubleClickSelectsAll` if you want Firefox-alike Linux behavior there.

**Comment by wolfbeast** [comment]
Re-closing this issue as the solution has been verified.
