### ISSUE TITLE
Implement ES6 block-level functions

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#900]
Willy-nilly post-declarations of functions inside blocks without any structure as permitted by ES6 and Annex B nonsense are being used in the wild in increasing numbers.
Considering this works in Chrome, sites aren't going to step down from their bad coding, so we'll have to give this attention.

Reference BMO: https://bugzilla.mozilla.org/show_bug.cgi?id=1071646

This will take a strap-in session of Spidermonkey wrangling.
Anyone feel up to the challenge? Or will it be me again? ;)

**Comment by wolfbeast** [comment]
I guess this one will be me.

**Comment by wolfbeast** [comment]
Oh Mozilla.. Why, oh why the constant renaming & refactoring? 45 minutes in and I already have a headache.

**Comment by wolfbeast** [comment]
Can't do this right now. This will need some reworking.
This is bounty material if anyone wants to have a crack at it.

**Comment by Gpower2** [comment]
I run into the same problems when I gave #176 a try a few weeks ago. Mozilla has refactored a lot of the code, using lots of new structs instead of primitive types for function arguments and return values, making porting of bugs and new features almost impossible without also porting the refactored code even when it's totally irrelevant to the problem/feature in hand.
Unfortunately I have no real experience in the Mozilla or PaleMoon codebase, so I can't even make a decent proposal as to how PaleMoon should address this...

**Comment by wolfbeast** [comment]
I looked a little closer at the Mozilla patches and I do think it's at least possible to get the non-Annex B parts across with some on-the-fly translation of structs and pointer references. I'll see if I can manage that today.

**Comment by wolfbeast** [comment]
Nope, scratch that. Too much shifting around of functions between different modules makes this too much of a spaghetti code thing to do. Looks like this will simple need to be written in from definition as a new implementation; it's not possible to rely on the Mozilla code here.

**Comment by wolfbeast** [comment]
If anyone feels up to this, there *will* be a substantial bounty for resolving this issue. You should be able to draw at least inspiration from the Mozilla patches for this, just don't expect anything to be directly portable.

**Comment by wolfbeast** [comment]
Clearing the milestone for now. Unless we actually have someone working on this, it's pointless to move it back each release, no matter how important.

**Comment by BrenBarn** [comment]
I think this issue has unfortunate visibility to users.  The browser capability test at http://html5test.com/ appears to use this functionality, at least on its "compare" page.  Users who are considering using Pale Moon may reasonably google something like "browser capability test" to see how Pale Moon stacks up in terms of support for HTML5.  If they then try to compare their Pale Moon version with other browsers, they'll find that the comparison can't even be done at all due to this browser problem.

I in fact did this several months ago and set Pale Moon aside as a result.  Just now, having forgotten why I'd set Pale Moon aside, I again started it up and went to check its capabilities, and this happened again, reminding me why I'd dropped it before.

This is not to say that this bug has to be the highest priority.  I realize this is a tough bug and I'm still rooting for Pale Moon as the Firefox XUL-deprecation fiasco unfolds.  Basically I just wanted to point out that features that are used in browser-test web pages may have a disproportionate effect in terms of attracting or repelling users.  A significant worry for people moving away from one of the "big-name" browsers is whether the smaller alternatives (like Pale Moon) lag behind in terms of being able to handle what websites are doing.  If someone goes to test their browser and finds that missing browser features not only give disappointing results, but prevent the test from even beginning, that is likely to turn them off Pale Moon for a long time.

**Comment by Sa-Ja-Di** [comment]
@BrenBarn Like the answer was in the comment above yours... There is the need for someone to work on that, as stuff like that really needs special knowledge as ES stuff can't compared with any other tasks. Pretty sure things would speed up if someone could be found who has some special knowledge like that. No one stops you from asking on irc or coding boards for details or suggestions which you could forward then to @wolfbeast

**Comment by wolfbeast** [comment]
We'll have this solved in a UXP-based Pale Moon. Closing.
