### ISSUE TITLE
Broken/outdated TLS Cipher suite and TLS Version

### ISSUE THREAD

**Issue by leedoyle** [MoonchildProductions/Pale-Moon#917]
I was surprised to see a red warning on a secure website, a social network [VK.COM](https://vk.com/)(mentioned on the palemoon start/welcome page), see picture 1.
![warning](https://cloud.githubusercontent.com/assets/25978190/23312315/ba6135da-fad2-11e6-9b3d-ae52713ee291.png)

Then I investigated the situation using the [SSLeuth addon](https://addons.mozilla.org/en-US/firefox/addon/ssleuth/) and compared the behaviour of Firefox 51 and Palemoon 27.1 on the same webpage.
Here's the comparison:
![palemoonTLS](https://cloud.githubusercontent.com/assets/25978190/23312368/ee773fa4-fad2-11e6-9cd2-ea4dbb169aae.png)
![firefoxTLS](https://cloud.githubusercontent.com/assets/25978190/23312379/faae8eda-fad2-11e6-8b2a-086c4522d79b.png)

It turned out that:
- TLS Version Pale Moon uses appears to be outdated
- Pale Moon doesn't provide Perfect Forward Secrecy as opposed to Firefox 51
- Pale Moon uses outdated 128 bits Cipher Suite

Please note that the warning appears in Pale Moon's interface, without any interference from SSleuth.

**Comment by wolfbeast** [comment]
The extension simply doesn't ask for the correct (full suite) string from our API. It assumes Firefox which dumps the entire string in the "Name" field which is a bug but which whining users complained about when fixed because they wanted to see the ugly suite string.

This is a bug in the extension in use. If you use an extension that properly supports Pale Moon, like Cipherfox, then you will see the correct data on VK.COM: TLS 1.2, AES-GCM 128-bit, PFS (TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256)

**Comment by leedoyle** [comment]
@wolfbeast thanks for the information. Could you please explain why does the exclamation mark appear in the first place?
And why does Pale Moon use 
- VK.COM: TLS 1.2, AES-GCM 128-bit, PFS (TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256) whereas Firefox 51 uses
- TLS_ECDHE_RSA_with_AES_256_GCM_SHA384

**Comment by wolfbeast** [comment]
> why does the red exclamation mark appear in the first place?!

Because the extension doesn't know how to handle _not_ getting the full suite in the "Name" field, and thinks it's broken as a result!! Once more, your extension expects the Firefox bug to present and relies on it.

Pale Moon uses 128-bit AES-GCM encryption because I haven't implemented 256-bit AES-GCM (yet), considering the performance/benefit tradeoff is **really** poor for AES between 128-bit and 256-bit (as in: it makes insignificant security difference but has a heavy computational cost -- see plenty of documents on the 'net about this)

**Comment by leedoyle** [comment]
@wolfbeast I see. Still, there must be a reson it's the preferred Cipher Suite on many websites. I hope to see it one day in Pale Moon :)
