### ISSUE TITLE
Rewrite padlock code

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#940]
The padlock code we're using is relying on very old nsIWebProgressListener code that makes assumptions about old IDL specifics and not using additional pieces of info it provides (e.g. weak cipher info). The platform has also done away with always providing a security level along with "is_secure" so the padlock code needs to get a once-over to modernize it based on our current API.

**Comment by mattatobin** [comment]
Specifically, anytime STATE_IS_SECURE it also returns STATE_SECURE_HIGH in most cases (STATE_SECURE_MED and STATE_SECURE_LOW were removed at some point along the way).

 This makes STATE_SECURE_HIGH basically worthless and the other two still being bitwise values in the IDL seems to have been kept around only to satisfy consumers of nsIWebProgressListener in a rare case of not breaking extensions but most likely so internal consumers didn't have to be rewritten at the time.

What needs to happen in my view is either STATE_SECURE_HIGH and the idl bitwise definitions that aren't valid anymore need to be removed or they need restored to working order. Otherwise we need to make notes and keep in mind that if STATE_IS_SECURE we should also set STATE_SECURE_HIGH to maintain consistancy.

As for the padlock component in browser base this simply needs aligned to what is actually being used in cpp and a condition should be added to switch logic for the possibility of being STATE_IS_SECURE but not having STATE_SECURE_HIGH. Which very well might be desirable for the case of local injection on a secure site in the uBO data: uri case.
